### ISSUE TITLE
 gpssh-exkeys:Traceback (most recent call last):

### ISSUE THREAD

**Issue by clmyyclm** [greenplum-db/gpdb#1067]
[root@mdw config]# gpssh-exkeys -f allhosts 
[STEP 1 of 5] create local ID and authorize on local host

[STEP 2 of 5] keyscan all hosts and update known_hosts file

[STEP 3 of 5] authorize current user on remote hosts
  ... send to sdw3
Traceback (most recent call last):
  File "/opt/gpdb/gpsql_old/bin/gpssh-exkeys", line 751, in <module>
    send_local_id = h.sendLocalID(localID, GV.passwd, tempDir if isExistingHost else None)
  File "/opt/gpdb/gpsql_old/bin/gpssh-exkeys", line 191, in sendLocalID
    p.load_system_host_keys()
  File "/usr/lib/python2.6/site-packages/paramiko/client.py", line 101, in load_system_host_keys
    self._system_host_keys.load(filename)
  File "/usr/lib/python2.6/site-packages/paramiko/hostkeys.py", line 101, in load
    e = HostKeyEntry.from_line(line, lineno)
  File "/usr/lib/python2.6/site-packages/paramiko/hostkeys.py", line 331, in from_line
    key = RSAKey(data=decodebytes(key))
  File "/usr/lib/python2.6/site-packages/paramiko/rsakey.py", line 58, in __init__
    ).public_key(default_backend())
  File "/usr/lib64/python2.6/site-packages/cryptography/hazmat/backends/**init**.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/usr/lib64/python2.6/site-packages/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
AttributeError: 'EntryPoint' object has no attribute 'resolve'

[root@mdw config]# ping sdw3
PING sdw3 (192.168.0.23) 56(84) bytes of data.
64 bytes from sdw3 (192.168.0.23): icmp_seq=1 ttl=64 time=0.280 ms

I need help.

**Comment by kaknikhil** [comment]
This may be because of an older version of setup tools (see https://github.com/pyca/cryptography/commit/30e199e0fb220a17b3089508a59d29a2924f10e4)  , can you try upgrading setuptools 
`pip install -U setuptools` ?

**Comment by clmyyclm** [comment]
Done, thanks for the consideration

**Comment by kaknikhil** [comment]
@clmyyclm : did the upgrade fix your issue ? If yes , can you close the issue ?

**Comment by andreasscherbaum** [comment]
If that fixes the error, can we catch that problem earlier, and not let gpssh-exkeys proceed with an outdated module?
