### ISSUE TITLE
planner crash when run group by cube on partition table

### ISSUE THREAD

**Issue by lambgong** [greenplum-db/gpdb#10710]
### Greenplum version or build
6.5 

### OS version and uname -a
centos 7

### Step to reproduce the behavior

create a partition table as follow:
```
CREATE TABLE t_partition
(
    uid int, 
	channel int,
	game_type int,
    fdate date
) DISTRIBUTED BY (uid)
PARTITION BY RANGE(fdate) 
(
    PARTITION pn START ('2020-08-25'::date) END ('2020-08-27'::date) EVERY ('1 day'::interval), 
    DEFAULT PARTITION pdefaul
);
```

run sql as follow:
```
SELECT COUNT(DISTINCT uid) AS CNT_1 FROM t_partition WHERE fdate = '20200826' GROUP BY CUBE(channel, game_type)
```

planner will crash, and the coredump backtrace as follow:
```
#0  0x00007f4a2a1944ab in raise () from /lib64/libpthread.so.0
#1  0x00000000009daf26 in StandardHandlerForSigillSigsegvSigbus_OnMainThread (processName=<optimized out>, postgres_signal_arg=11)
    at elog.c:5585
#2  <signal handler called>
#3  build_simple_rel (root=root@entry=0x2396b18, relid=2, reloptkind=reloptkind@entry=RELOPT_OTHER_MEMBER_REL) at relnode.c:127
#4  0x00000000007e3a6b in build_simple_rel (root=root@entry=0x2396b18, relid=relid@entry=1, reloptkind=reloptkind@entry=RELOPT_BASEREL)
    at relnode.c:223
#5  0x00000000007c0c3d in rebuild_append_simple_rel_and_rte (subroots=0x236f050, subplans=0x236f0a0, rtable=<optimized out>,
    root=0x2396b18) at plangroupext.c:2277
#6  plan_list_rollup_plans (lefttree=<optimized out>, context=0x7ffcb88bc910, root=<optimized out>) at plangroupext.c:2535
#7  plan_grouping_extension (root=root@entry=0x2396b18, path=path@entry=0x2363440, tuple_fraction=tuple_fraction@entry=0,
    use_hashed_grouping=use_hashed_grouping@entry=0 '\000', p_tlist=p_tlist@entry=0x7ffcb88bcd00, sub_tlist=<optimized out>,
    twostage=twostage@entry=0 '\000', qual=0x0, p_numGroupCols=p_numGroupCols@entry=0x7ffcb88bcbf0,
    p_grpColIdx=p_grpColIdx@entry=0x7ffcb88bcc50, p_grpOperators=p_grpOperators@entry=0x7ffcb88bcc60,
    agg_costs=agg_costs@entry=0x7ffcb88bccc0, canonical_grpsets=canonical_grpsets@entry=0x2399888,
    p_dNumGroups=p_dNumGroups@entry=0x7ffcb88bcc10, querynode_changed=querynode_changed@entry=0x7ffcb88bcc80 "",
    p_current_pathkeys=p_current_pathkeys@entry=0x7ffcb88bcc00, lefttree=0x2366130, lefttree@entry=0x2364ee8) at plangroupext.c:493
#8  0x00000000007b55a1 in grouping_planner (root=root@entry=0x2396b18, tuple_fraction=tuple_fraction@entry=0) at planner.c:2444
#9  0x00000000007b67cd in subquery_planner (glob=glob@entry=0x2183cc8, parse=parse@entry=0x2396280, parent_root=parent_root@entry=0x0,
    hasRecursion=hasRecursion@entry=0 '\000', tuple_fraction=tuple_fraction@entry=0, subroot=subroot@entry=0x7ffcb88bce70,
    config=<optimized out>) at planner.c:875
#10 0x00000000007b6ba1 in standard_planner (parse=0x2396280, cursorOptions=0, boundParams=0x0) at planner.c:345
#11 0x00000000007b7335 in planner (parse=parse@entry=0x224cc40, cursorOptions=cursorOptions@entry=0, boundParams=boundParams@entry=0x0)
    at planner.c:200
#12 0x00000000008784cf in pg_plan_query (boundParams=0x0, cursorOptions=0, querytree=0x224cc40) at postgres.c:958
#13 pg_plan_queries (cursorOptions=0, boundParams=0x0, querytrees=<optimized out>) at postgres.c:1017
#14 exec_simple_query (query_string=0x224b968 "SELECT COUNT(DISTINCT uid) AS CNT_1 FROM t_partition GROUP BY CUBE(channel,game_type)\r")
    at postgres.c:1763
#15 0x000000000087b620 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x2189888, dbname=0x2189738 "etl_cashcow",
    username=<optimized out>) at postgres.c:5257
#16 0x00000000004cc5ae in BackendRun (port=0x21817d0) at postmaster.c:4796
#17 BackendStartup (port=0x21817d0) at postmaster.c:4453
#18 ServerLoop () at postmaster.c:1938
#19 0x00000000008037f7 in PostmasterMain (argc=argc@entry=6, argv=argv@entry=0x2157a30) at postmaster.c:1508
#20 0x00000000004ce7eb in main (argc=6, argv=0x2157a30) at main.c:245
```

**Comment by kainwen** [comment]
I can reproduce this in latest 6X(top commit now is 1dc23be25e54e86a4f4f2c6bbc438f2e02fd724c).

**Comment by lambgong** [comment]
Bye the way, this works fine in gp5

**Comment by hlinnaka** [comment]
Possibly the same issue as https://github.com/greenplum-db/gpdb/pull/10685

**Comment by kainwen** [comment]
> Possibly the same issue as #10685

Yes. I test on that branch, this issue runs correctly.

So let's help push that pr to fix all these issues.
