### ISSUE TITLE
Assert failed in CREATE TABLE ... PARTITION BY ...

### ISSUE THREAD

**Issue by hidva** [greenplum-db/gpdb#10960]
### Greenplum version or build

```
postgres=# select version();
PostgreSQL 12beta2 (Greenplum Database 7.0.0-alpha.0+dev.13963.g1d991e47cc build dev) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 6.5.1 20190307 (Alibaba 6.5.1-1 2.17), 64-bit compiled on Oct  9 2020 11:38:05 (with assert checking)
```

### OS version and uname -a

```
$ uname -a
Linux gpdb 4.9.151-015.ali3000.alios7.x86_64 #1 SMP Tue Mar 12 19:10:26 CST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

### autoconf options used ( config.status --config )

```
$ ./config.status --config
'--prefix=/u01/user/zhanyi/DBBIN/DB' '--enable-gpfdist' '--disable-pxf' '--enable-debug' '--enable-depend' '--without-zstd' '--enable-cassert' '--disable-gpcloud' 'CFLAGS=-O0 -ggdb -fsanitize=address' 'CXXFLAGS=-O0 -ggdb -fsanitize=address' 'LIBS=-ldl'
```

### Installation information ( pg_config )

```
$ pg_config
BINDIR = /u01/user/zhanyi/DBBIN/DB/bin
DOCDIR = /u01/user/zhanyi/DBBIN/DB/share/doc/postgresql
HTMLDIR = /u01/user/zhanyi/DBBIN/DB/share/doc/postgresql
INCLUDEDIR = /u01/user/zhanyi/DBBIN/DB/include
PKGINCLUDEDIR = /u01/user/zhanyi/DBBIN/DB/include/postgresql
INCLUDEDIR-SERVER = /u01/user/zhanyi/DBBIN/DB/include/postgresql/server
LIBDIR = /u01/user/zhanyi/DBBIN/DB/lib
PKGLIBDIR = /u01/user/zhanyi/DBBIN/DB/lib/postgresql
LOCALEDIR = /u01/user/zhanyi/DBBIN/DB/share/locale
MANDIR = /u01/user/zhanyi/DBBIN/DB/share/man
SHAREDIR = /u01/user/zhanyi/DBBIN/DB/share/postgresql
SYSCONFDIR = /u01/user/zhanyi/DBBIN/DB/etc/postgresql
PGXS = /u01/user/zhanyi/DBBIN/DB/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--prefix=/u01/user/zhanyi/DBBIN/DB' '--enable-gpfdist' '--disable-pxf' '--enable-debug' '--enable-depend' '--without-zstd' '--enable-cassert' '--disable-gpcloud' 'CFLAGS=-O0 -ggdb -fsanitize=address' 'CXXFLAGS=-O0 -ggdb -fsanitize=address' 'LIBS=-ldl'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-but-set-variable -g -ggdb -O0 -ggdb -fsanitize=address  -Werror=uninitialized -Werror=implicit-function-declaration
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/u01/user/zhanyi/DBBIN/DB/lib',--enable-new-dtags
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lnuma -lxerces-c -lbz2 -lrt -lz -lreadline -lrt -lcrypt -lm -ldl -lcurl
VERSION = PostgreSQL 12beta2
```

### Step to reproduce the behavior

```sql
CREATE TABLE parttable(col1 int, col2 int, col3 int, col4 int)
PARTITION BY RANGE (col2)
    SUBPARTITION BY RANGE (col3)
    SUBPARTITION TEMPLATE (START (1) END (2) EVERY (1))
        SUBPARTITION BY LIST (col4)
        SUBPARTITION TEMPLATE (SUBPARTITION val1 VALUES (1), SUBPARTITION val2 VALUES (2))
( START (2008) END (2009) EVERY (1)) distributed by (col1);
```

```
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.1.alios7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /u01/user/zhanyi/DBBIN/DB/bin/postgres...done.
[New LWP 103735]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `postgres:  7000, zhanyi postgres [local] cmd1 CREATE TABLE                    '.
Program terminated with signal 6, Aborted.
#0  0x00007f22d5ffe277 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.1.alios7.x86_64 cyrus-sasl-lib-2.1.26-19.2.1.alios7.x86_64 glibc-2.17-260.alios7.x86_64 keyutils-libs-1.5.8-3.1.alios7.x86_64 krb5-libs-1.15.1-37.2.alios7.x86_64 libasan-6.5.1-1.alios7.x86_64 libcom_err-1.43.5-8.alios7.x86_64 libcurl-7.29.0-54.3.alios7.1.x86_64 libgcc-6.5.1-1.alios7.x86_64 libidn-1.28-4.1.alios7.x86_64 libselinux-2.5-14.1.1.alios7.x86_64 libssh2-1.8.0-3.1.alios7.x86_64 libstdc++-6.5.1-1.alios7.x86_64 nspr-4.21.0-1.1.alios7.x86_64 nss-3.44.0-7.1.alios7.x86_64 nss-softokn-freebl-3.44.0-8.1.alios7.x86_64 nss-util-3.44.0-4.1.alios7.x86_64 numactl-libs-2.0.9-5.1.alios7.x86_64 openldap-2.4.44-5.alios7.x86_64 openssl-libs-1.0.2k-19.alios7.x86_64 pcre-8.32-15.1.alios7.x86_64 zlib-1.2.7-16.2.alios7.x86_64
(gdb) bt
#0  0x00007f22d5ffe277 in raise () from /lib64/libc.so.6
#1  0x00007f22d5fff968 in abort () from /lib64/libc.so.6
#2  0x0000000001a06063 in ExceptionalCondition (conditionName=0x2557700 "!(policy->ptype != POLICYTYPE_ENTRY)", errorType=0x254a7e0 "FailedAssertion", fileName=0x254b8c0 "tablecmds.c", lineNumber=17109) at assert.c:44
#3  0x0000000000e6f53d in make_distributedby_for_rel (rel=0x7f22bec0ddc0) at tablecmds.c:17109
#4  0x0000000000d0d606 in makePartitionCreateStmt (parentrel=0x7f22bec0ddc0, partname=0x0, boundspec=0x625000071c68, subPart=0x625000071dd0, elem=0x61900003dce0, partnamecomp=0x7fffb1ddcb80) at parse_partition_gp.c:867
#5  0x0000000000d0ea69 in generateRangePartitions (pstate=0x625000073cb0, parentrel=0x7f22bec0ddc0, elem=0x61900003dce0, subPart=0x625000076950, partnamecomp=0x7fffb1ddcb80, hasImplicitRangeBounds=0x7fffb1ddcb40) at parse_partition_gp.c:1008
#6  0x0000000000d11961 in generatePartitions (parentrelid=16384, gpPartSpec=0x621000016b10, subPartSpec=0x621000016e38, queryString=0x625000007a50 "CREATE TABLE parttable(col1 int, col2 int, col3 int, col4 int)\nPARTITION BY RANGE (col2) \n    SUBPARTITION BY RANGE (col3) \n    SUBPARTITION TEMPLATE (START (1) END (2) EVERY (1)) \n        SUBPARTITION BY LIST (col4)     \n        SUBPARTITION TEMPLATE (SUBPARTITION val1 VALUES (1), SUBPARTITION val2 VALUES (2)) \n( START (2008) END (2009) EVERY (1));", parentoptions=0x0, parentaccessmethod=0x0, parentattenc=0x0, forvalidationonly=false) at parse_partition_gp.c:1593
#7  0x00000000016342da in ProcessUtilitySlow (pstate=0x61900002e0d0, pstmt=0x625000064b90, queryString=0x625000007a50 "CREATE TABLE parttable(col1 int, col2 int, col3 int, col4 int)\nPARTITION BY RANGE (col2) \n    SUBPARTITION BY RANGE (col3) \n    SUBPARTITION TEMPLATE (START (1) END (2) EVERY (1)) \n        SUBPARTITION BY LIST (col4)     \n        SUBPARTITION TEMPLATE (SUBPARTITION val1 VALUES (1), SUBPARTITION val2 VALUES (2)) \n( START (2008) END (2009) EVERY (1));", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x625000064e80, completionTag=0x7fffb1ddd620 "") at utility.c:1235
#8  0x0000000001633943 in standard_ProcessUtility (pstmt=0x625000064b90, queryString=0x625000007a50 "CREATE TABLE parttable(col1 int, col2 int, col3 int, col4 int)\nPARTITION BY RANGE (col2) \n    SUBPARTITION BY RANGE (col3) \n    SUBPARTITION TEMPLATE (START (1) END (2) EVERY (1)) \n        SUBPARTITION BY LIST (col4)     \n        SUBPARTITION TEMPLATE (SUBPARTITION val1 VALUES (1), SUBPARTITION val2 VALUES (2)) \n( START (2008) END (2009) EVERY (1));", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x625000064e80, completionTag=0x7fffb1ddd620 "") at utility.c:1084
#9  0x0000000001631698 in ProcessUtility (pstmt=0x625000064b90, queryString=0x625000007a50 "CREATE TABLE parttable(col1 int, col2 int, col3 int, col4 int)\nPARTITION BY RANGE (col2) \n    SUBPARTITION BY RANGE (col3) \n    SUBPARTITION TEMPLATE (START (1) END (2) EVERY (1)) \n        SUBPARTITION BY LIST (col4)     \n        SUBPARTITION TEMPLATE (SUBPARTITION val1 VALUES (1), SUBPARTITION val2 VALUES (2)) \n( START (2008) END (2009) EVERY (1));", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x625000064e80, completionTag=0x7fffb1ddd620 "") at utility.c:381
#10 0x000000000162f177 in PortalRunUtility (portal=0x625000043a50, pstmt=0x625000064b90, isTopLevel=true, setHoldSnapshot=false, dest=0x625000064e80, completionTag=0x7fffb1ddd620 "") at pquery.c:1352
#11 0x000000000162f8ad in PortalRunMulti (portal=0x625000043a50, isTopLevel=true, setHoldSnapshot=false, dest=0x625000064e80, altdest=0x625000064e80, completionTag=0x7fffb1ddd620 "") at pquery.c:1498
#12 0x000000000162dc13 in PortalRun (portal=0x625000043a50, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x625000064e80, altdest=0x625000064e80, completionTag=0x7fffb1ddd620 "") at pquery.c:966
#13 0x000000000161dc52 in exec_simple_query (query_string=0x625000007a50 "CREATE TABLE parttable(col1 int, col2 int, col3 int, col4 int)\nPARTITION BY RANGE (col2) \n    SUBPARTITION BY RANGE (col3) \n    SUBPARTITION TEMPLATE (START (1) END (2) EVERY (1)) \n        SUBPARTITION BY LIST (col4)     \n        SUBPARTITION TEMPLATE (SUBPARTITION val1 VALUES (1), SUBPARTITION val2 VALUES (2)) \n( START (2008) END (2009) EVERY (1));") at postgres.c:1889
#14 0x0000000001627a30 in PostgresMain (argc=1, argv=0x629000025538, dbname=0x62500000e8f8 "postgres", username=0x629000025380 "zhanyi") at postgres.c:5246
#15 0x00000000014568dc in BackendRun (port=0x61400000da40) at postmaster.c:4923
#16 0x00000000014556d1 in BackendStartup (port=0x61400000da40) at postmaster.c:4608
#17 0x000000000144df88 in ServerLoop () at postmaster.c:1964
#18 0x000000000144cd06 in PostmasterMain (argc=9, argv=0x60700000dc30) at postmaster.c:1589
#19 0x00000000010d5fd8 in main (argc=9, argv=0x60700000dc30) at main.c:240
```

**Comment by ashwinstar** [comment]
Thanks for reporting @hidva I tried and I am not hitting the assertion or any failure somehow for the provided sql on latest master as of commit 1d991e47

```sql
CREATE TABLE parttable(col1 int, col2 int, col3 int, col4 int)
PARTITION BY RANGE (col2)
    SUBPARTITION BY RANGE (col3)
    SUBPARTITION TEMPLATE (START (1) END (2) EVERY (1))
        SUBPARTITION BY LIST (col4)
        SUBPARTITION TEMPLATE (SUBPARTITION val1 VALUES (1), SUBPARTITION val2 VALUES (2))
( START (2008) END (2009) EVERY (1)) distributed by (col1);
CREATE TABLE

select localoid::regclass,* from gp_distribution_policy;
               localoid               | localoid | policytype | numsegments | distkey | distclass 
--------------------------------------+----------+------------+-------------+---------+-----------
 parttable                            |    16400 | p          |           3 | 1       | 10054
 parttable_1_prt_1                    |    16403 | p          |           3 | 1       | 10054
 parttable_1_prt_1_2_prt_1            |    16406 | p          |           3 | 1       | 10054
 parttable_1_prt_1_2_prt_1_3_prt_val1 |    16409 | p          |           3 | 1       | 10054
 parttable_1_prt_1_2_prt_1_3_prt_val2 |    16412 | p          |           3 | 1       | 10054
(5 rows)
```

**Comment by hidva** [comment]
After a clean build, I can't reproduce this case too. Sorry to bother you.

**Comment by ashwinstar** [comment]
No probs @hidva, you playing/hacking with gpdb7 and reporting issues is encouraging.
