### ISSUE TITLE
gpcheckcat needs to reset GV.retcode before starting to check a database

### ISSUE THREAD

**Issue by asimrp** [greenplum-db/gpdb#11044]
### Greenplum version or build
Version 7 (seen on PR pipeline for PR #10983)

### Expected behavior
If catalog check for a database passed without any issues, gpcheckcat should not report any assertion failure.

### Actual behavior
```
Connected as user 'gpadmin' to database 'isolation2test', port '7000', gpdb version '7.0'
    ...
SUMMARY REPORT: FAILED
===================================================================
Completed 14 test(s) on database 'isolation2test' at 2020-10-22 10:46:35 with elapsed time 0:00:19
Found a total of 1 issue(s)

----------------------------------------------------
Relation oid: 49221
Relation schema: N/A
Relation name: N/A

    Name of test which found this issue: foreign_key_pg_class
        No pg_class {'oid': 49221} entry for gp_fastsequence {'objid': 49221, 'objmod': 2} on content 0 (b13863e2-2572-4ff0-6009-61b2cb737f51:7002) 

Connected as user 'gpadmin' to database 'mapred_regression', port '7000', gpdb version '7.0'
    ...
SUMMARY REPORT: PASSED
===================================================================
Completed 14 test(s) on database 'mapred_regression' at 2020-10-22 10:46:49 with elapsed time 0:00:13
Found no catalog issue

Traceback (most recent call last):
  File "/usr/local/greenplum-db-devel/bin/gpcheckcat", line 3357, in <module>
    main()
  File "/usr/local/greenplum-db-devel/bin/gpcheckcat", line 3347, in main
    checkcatReport()
  File "/usr/local/greenplum-db-devel/bin/gpcheckcat", line 3186, in checkcatReport
    assert(GV.retcode == SUCCESS)
AssertionError
```

### Step to reproduce the behavior
Looks like when gpcheckcat is run against all databases, catalog issues found on one database cause an assertion failure if the next database in the list has no catalog issues.

**Comment by lij55** [comment]
closing this issue because it seems fixed: https://github.com/greenplum-db/gpdb/blob/422d9c634077e397bcd87befb380e9a580651fc5/gpMgmt/bin/gpcheckcat#L3353
