### ISSUE TITLE
Use analyzedb  failed with table name contained ":" character

### ISSUE THREAD

**Issue by tangyibo** [greenplum-db/gpdb#11299]
### Greenplum version or build

```
Greenplum Version: 'PostgreSQL 9.4.24 (Greenplum Database 6.10.1 build commit:efba04ce26ebb29b535a255a5e95d1f5ebfde94e) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Aug 13 2020 15:39:16'
```

### OS version and uname -a

```
CentOS Linux release 7.5.1804 (Core)

Linux XXXXX 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Installation information ( pg_config )
```
BINDIR = /usr/local/greenplum-db-6.10.1/bin
DOCDIR = /usr/local/greenplum-db-6.10.1/share/doc/postgresql
HTMLDIR = /usr/local/greenplum-db-6.10.1/share/doc/postgresql
INCLUDEDIR = /usr/local/greenplum-db-6.10.1/include
PKGINCLUDEDIR = /usr/local/greenplum-db-6.10.1/include/postgresql
INCLUDEDIR-SERVER = /usr/local/greenplum-db-6.10.1/include/postgresql/server
LIBDIR = /usr/local/greenplum-db-6.10.1/lib
PKGLIBDIR = /usr/local/greenplum-db-6.10.1/lib/postgresql
LOCALEDIR = /usr/local/greenplum-db-6.10.1/share/locale
MANDIR = /usr/local/greenplum-db-6.10.1/man
SHAREDIR = /usr/local/greenplum-db-6.10.1/share/postgresql
SYSCONFDIR = /usr/local/greenplum-db-6.10.1/etc/postgresql
PGXS = /usr/local/greenplum-db-6.10.1/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--disable-debug-extensions' '--disable-tap-tests' '--enable-orca' '--with-zstd' '--with-gssapi' '--with-libxml' '--with-perl' '--with-python' '--with-openssl' '--with-pam' '--with-ldap' '--prefix=/usr/local/greenplum-db-oss' '--mandir=/usr/local/greenplum-db-oss/man' 'CC=gcc' 'CFLAGS=-O3 -fargument-noalias-global -fno-omit-frame-pointer -g'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/greenplum-db-6.10.1/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/greenplum-db-6.10.1/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/greenplum-db-oss/lib',--enable-new-dtags -L/usr/local/greenplum-db-6.10.1/lib
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lxerces-c -lxml2 -lpam -lrt -lgssapi_krb5 -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/greenplum-db-6.10.1/lib
VERSION = PostgreSQL 9.4.24
```

### Step to reproduce the behavior

Step 1. Create table with name contained ":" character, then can analyze this table: 
```
# psql
psql (9.4.24)
Type "help" for help.

postgres=# create table "test:aaa"( "id" int8, "aa" text ) DISTRIBUTED BY(id);
CREATE TABLE
postgres=# ANALYZE "public"."test:aaa";
ANALYZE
postgres=# \q
```

Step 2. Use tool analyzedb to analyze this table failed:
```
[gpadmin@master1 ~]$ analyzedb -d postgres -t "public"."test:aaa"
20201222:11:22:53:008322 analyzedb:master1:gpadmin-[INFO]:-Starting analyzedb with args: -d postgres -t public.test:aaa
20201222:11:22:53:008322 analyzedb:master1:gpadmin-[INFO]:-Getting and verifying input tables...
20201222:11:22:53:008322 analyzedb:master1:gpadmin-[INFO]:-Checking for tables with stale stats...
20201222:11:22:53:008322 analyzedb:master1:gpadmin-[ERROR]:-Table name has an invalid character "\n", ":", "," : "test:aaa"
Traceback (most recent call last):
  File "/usr/local/greenplum-db-6.10.1/bin/analyzedb", line 405, in execute
    candidates = self._get_valid_candidates(candidates)
  File "/usr/local/greenplum-db-6.10.1/bin/analyzedb", line 637, in _get_valid_candidates
    raise Exception('Table name has an invalid character "\\n", ":", "," : "%s"' % table)
Exception: Table name has an invalid character "\n", ":", "," : "test:aaa"
20201222:11:22:53:008322 analyzedb:master1:gpadmin-[CRITICAL]:-analyzedb failed. (Reason='Table name has an invalid character "\n", ":", "," : "test:aaa"') exiting...
```

Who can help me? Thanks!

**Comment by ashwinstar** [comment]
@tangyibo thanks for reporting the issue. We will fix it
