### ISSUE TITLE
ERROR: unrecognized node type: 137

### ISSUE THREAD

**Issue by gfphoenix78** [greenplum-db/gpdb#12382]
### Greenplum version or build
GPDB 7X
6X/5X ??

### Expected behavior
The expected node branch should be handled properly.
### Actual behavior
The node branch is not caught and raise an error.
### Step to reproduce the behavior
```
java.lang.AssertionError: CREATE TABLE t0(c0 int4range  DEFAULT (CAST(CAST(0.69666113898683701410874391513061709702014923095703125 AS VARC$
AR(343)) AS int4range)), CHECK(((NOT (FALSE))::VARCHAR(67)!~*lower('Nh__')) IS FALSE), UNIQUE(c0), EXCLUDE (c0 ASC WITH =) WHERE ((((((B'1$
11111111111111111111111111111111110111010100011000000100110111')#(B'1111111111111111111111111111111111101101111100100001101110101101')))::$
ARCHAR(905) COLLATE "C") SIMILAR TO translate(CAST(num_nulls(FALSE, t0.c0, -716067457, -824727920) AS VARCHAR), (CAST(B'111111111111111111$
111111111111110000000110100001000110000011111' AS VARCHAR) COLLATE "C"), upper('Tt')))), PRIMARY KEY(c0));
        at sqlancer.common.query.SQLQueryAdapter.checkException(SQLQueryAdapter.java:100)
        at sqlancer.common.query.SQLQueryAdapter.execute(SQLQueryAdapter.java:93)
        at sqlancer.Main$QueryManager.execute(Main.java:238)
        at sqlancer.GlobalState.executeStatement(GlobalState.java:108)
        at sqlancer.postgres.PostgresProvider.createTables(PostgresProvider.java:286)
        at sqlancer.postgres.PostgresProvider.generateDatabase(PostgresProvider.java:192)
        at sqlancer.postgres.PostgresProvider.generateDatabase(PostgresProvider.java:1)
        at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:40)
        at sqlancer.Main$DBMSExecutor.run(Main.java:326)
        at sqlancer.Main$2.run(Main.java:510)
        at sqlancer.Main$2.runThread(Main.java:488)
        at sqlancer.Main$2.run(Main.java:478)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: unrecognized node type: 137 (parse_expr.c:394)  (seg0 172.17.0.2:7002 pid=2081382) (pa
rse_expr.c:394)
```

**Comment by gfphoenix78** [comment]
I didn't check whether this error exists in other GPDB versions in code. We should recheck it when fixing the bug.
