### ISSUE TITLE
Gang clean up code coredump (null pointer reference)

### ISSUE THREAD

**Issue by kainwen** [greenplum-db/gpdb#12399]
### Greenplum version or build

Below reproduce-step is based on gpdb master branch (b6024c99b6a89b33cf12d68cf5afce2585de8555).

I believe the issue exists in all versions of Greenplum.

### Expected behavior

Not Core dump

### Actual behavior

Coredump

The stack in the core is:

```
(gdb) bt
#0  0x00005649e54a09fd in cdbdisp_resetResult (dispatchResult=0x5649e65113c8) at cdbdispatchresult.c:171
#1  0x00005649e54a0992 in cdbdisp_termResult (dispatchResult=0x5649e65113c8) at cdbdispatchresult.c:150
#2  0x00005649e549dfd1 in cdbdisp_destroyDispatcherState (ds=0x5649e64fb1d8) at cdbdisp.c:366
#3  0x00005649e549e33c in cleanup_dispatcher_handle (h=0x5649e64fb1a0) at cdbdisp.c:503
#4  0x00005649e549e474 in cdbdisp_cleanupDispatcherHandle (owner=0x5649e6451560) at cdbdisp.c:567
#5  0x00005649e543914f in CdbResourceOwnerWalker (owner=0x5649e6451560, callback=0x5649e549e429 <cdbdisp_cleanupDispatcherHandle>) at resowner.c:1380
#6  0x00005649e549e392 in AtAbort_DispatcherState () at cdbdisp.c:526
#7  0x00005649e4cee427 in AbortTransaction () at xact.c:3477
#8  0x00005649e4cf152e in AbortOutOfAnyTransaction () at xact.c:5698
#9  0x00005649e53fb6af in ShutdownPostgres (code=1, arg=0) at postinit.c:1398
#10 0x00005649e51d59be in shmem_exit (code=1) at ipc.c:266
#11 0x00005649e51d5874 in proc_exit_prepare (code=1) at ipc.c:221
#12 0x00005649e51d5730 in proc_exit (code=1) at ipc.c:109
#13 0x00005649e53dcedb in errfinish (filename=0x5649e57abc60 "cdbdisp_async.c", lineno=306, funcname=0x5649e57ac330 <__func__.22488> "cdbdisp_dispatchToGang_async")
    at elog.c:689
#14 0x00005649e549eb8f in cdbdisp_dispatchToGang_async (ds=0x5649e64fb1d8, gp=0x5649e64fb740, sliceIndex=-1) at cdbdisp_async.c:306
#15 0x00005649e549d958 in cdbdisp_dispatchToGang (ds=0x5649e64fb1d8, gp=0x5649e64fb740, sliceIndex=-1) at cdbdisp.c:81
#16 0x00005649e54a3023 in cdbdisp_dispatchCommandInternal (pQueryParms=0x5649e6493608, flags=0, segments=0x5649e6493580, cdb_pgresults=0x7ffe3e20f3d0) at cdbdisp_query.c:496
#17 0x00005649e54a2e3d in CdbDispatchCommandToSegments (strCommand=0x7ffe3e20f520 "select gid from pg_prepared_xacts where prepared < now() - interval'120 seconds'", flags=0,
    segments=0x5649e6493580, cdb_pgresults=0x7ffe3e20f3d0) at cdbdisp_query.c:405
#18 0x00005649e54a2d69 in CdbDispatchCommand (strCommand=0x7ffe3e20f520 "select gid from pg_prepared_xacts where prepared < now() - interval'120 seconds'", flags=0,
    cdb_pgresults=0x7ffe3e20f3d0) at cdbdisp_query.c:377
```

### Step to reproduce the behavior

1. apply the following patch to add a fault inject to help reproduce

```diff
diff --git a/src/backend/cdb/dispatcher/cdbdispatchresult.c b/src/backend/cdb/dispatcher/cdbdispatchresult.c
index 5a7af771fb..9a36700e3e 100644
--- a/src/backend/cdb/dispatcher/cdbdispatchresult.c
+++ b/src/backend/cdb/dispatcher/cdbdispatchresult.c
@@ -76,6 +76,19 @@ cdbdisp_makeResult(struct CdbDispatchResults *meleeResults,
        dispatchResult->numrowsrejected = 0;
        dispatchResult->numrowscompleted = 0;

+#ifdef FAULT_INJECTOR
+       if (SIMPLE_FAULT_INJECTOR("make_dispatch_result_error") == FaultInjectorTypeSkip)
+       {
+               /*
+                * Inject a fault to simulate the createPQExpBuffer return NULL (maybe because of
+                * malloc failure, this will lead to enter the below if block and return NULL in
+                * this function. We need to test this code path to verify the gang clean up code
+                * is correct.
+                */
+               dispatchResult->resultbuf = NULL;
+       }
+#endif
+
        if (PQExpBufferBroken(dispatchResult->resultbuf) ||
                PQExpBufferBroken(dispatchResult->error_message))
        {
```

2. run the following SQL and it will crash and generate a coredump (if your OS config allows):

```sql
create extension if not exists gp_inject_fault;

select gp_inject_fault('make_dispatch_result_error', 'skip', dbid)
from gp_segment_configuration where role = 'p' and content = -1;

select * from gp_dist_random('pg_class');

psql: FATAL:  could not allocate resources for segworker communication (cdbdisp_async.c:306)
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
```

**Comment by kainwen** [comment]
I do not reproduce this in 5X.

6X and master branch have been fixed by:

* https://github.com/greenplum-db/gpdb/pull/12430
* https://github.com/greenplum-db/gpdb/pull/12434
