### ISSUE TITLE
Null Pointer reference during parse-analyze in function `fixup_unknown_vars_in_setop`

### ISSUE THREAD

**Issue by kainwen** [greenplum-db/gpdb#12407]
### Greenplum version or build

6X,  5X both have this issue.

The Master branch is OK does not have the issue.

### Expected behavior

Work correctly, do not core dump.

### Actual behavior

Core dump if compiling without cassert. The core's stack is:

```
#0  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00005603c22edbf5 in StandardHandlerForSigillSigsegvSigbus_OnMainThread (processName=0x5603c254fd5b "Master process", postgres_signal_arg=11) at elog.c:5579
#2  0x00005603c216c088 in CdbProgramErrorHandler (postgres_signal_arg=11) at postgres.c:3551
#3  <signal handler called>
#4  0x00005603c1e4fd39 in GetRTEByRangeTablePosn (pstate=0x0, varno=1, sublevels_up=-1) at parse_relation.c:494
#5  0x00005603c1e3ae4a in coerce_unknown_var (pstate=0x5603c3c8beb0, var=0x5603c3c8cab0, targetTypeId=25, targetTypeMod=-1, ccontext=COERCION_IMPLICIT,
    cformat=COERCE_EXPLICIT_CALL, levelsup=0) at parse_coerce.c:630
#6  0x00005603c1e3b2a8 in fixup_unknown_vars_in_RangeTblRef (pstate=0x5603c3c8beb0, rtr=0x5603c3c8cd80, colTypes=0x5603c3c695e0, colTypmods=0x5603c3c69630) at parse_coerce.c:801
#7  0x00005603c1e3b45d in fixup_unknown_vars_in_setop (pstate=0x5603c3c8beb0, stmt=0x5603c3c8c950) at parse_coerce.c:850
#8  0x00005603c1dfb44c in transformSetOperationStmt (pstate=0x5603c3c8beb0, stmt=0x5603c3b596b8) at analyze.c:2179
#9  0x00005603c1df7b41 in transformStmt (pstate=0x5603c3c8beb0, parseTree=0x5603c3b596b8) at analyze.c:309
#10 0x00005603c1df791a in parse_sub_analyze (parseTree=0x5603c3b596b8, parentParseState=0x5603c3b59a98, parentCTE=0x0, lockclause_from_parent=0x0) at analyze.c:222
#11 0x00005603c1e44ad6 in transformSubLink (pstate=0x5603c3b59a98, sublink=0x5603c3b597c8) at parse_expr.c:1649
#12 0x00005603c1e42043 in transformExprRecurse (pstate=0x5603c3b59a98, expr=0x5603c3b597c8) at parse_expr.c:284
#13 0x00005603c1e43a1e in transformAExprOpAny (pstate=0x5603c3b59a98, a=0x5603c3b59818) at parse_expr.c:1051
#14 0x00005603c1e41edc in transformExprRecurse (pstate=0x5603c3b59a98, expr=0x5603c3b59818) at parse_expr.c:245
#15 0x00005603c1e41abd in transformExpr (pstate=0x5603c3b59a98, expr=0x5603c3b59818, exprKind=EXPR_KIND_JOIN_ON) at parse_expr.c:126
#16 0x00005603c1e36530 in transformWhereClause (pstate=0x5603c3b59a98, clause=0x5603c3b59818, exprKind=EXPR_KIND_JOIN_ON, constructName=0x5603c24e00d2 "JOIN/ON")
    at parse_clause.c:1653
#17 0x00005603c1e345f2 in transformJoinOnClause (pstate=0x5603c3b59a98, j=0x5603c3b59868, namespace=0x5603c3c8bd08) at parse_clause.c:671
#18 0x00005603c1e35d5e in transformFromClauseItem (pstate=0x5603c3b59a98, n=0x5603c3b59868, top_rte=0x7fff4e8f8f08, top_rti=0x7fff4e8f8f04, namespace=0x7fff4e8f8f10)
    at parse_clause.c:1368
#19 0x00005603c1e33a30 in transformFromClause (pstate=0x5603c3b59a98, frmList=0x5603c3b598d8) at parse_clause.c:161
#20 0x00005603c1dfa225 in transformSelectStmt (pstate=0x5603c3b59a98, stmt=0x5603c3b59908) at analyze.c:1640
#21 0x00005603c1df7b25 in transformStmt (pstate=0x5603c3b59a98, parseTree=0x5603c3b59908) at analyze.c:307
#22 0x00005603c1df7a10 in transformTopLevelStmt (pstate=0x5603c3b59a98, parseTree=0x5603c3b59908) at analyze.c:271
#23 0x00005603c1dfd5f6 in transformExplainStmt (pstate=0x5603c3b59a98, stmt=0x5603c3b59a18) at analyze.c:3264
#24 0x00005603c1df7b76 in transformStmt (pstate=0x5603c3b59a98, parseTree=0x5603c3b59a18) at analyze.c:322
#25 0x00005603c1df7a10 in transformTopLevelStmt (pstate=0x5603c3b59a98, parseTree=0x5603c3b59a18) at analyze.c:271
#26 0x00005603c1df77de in parse_analyze (parseTree=0x5603c3b59a18,
    sourceText=0x5603c3b57ed8 "explain select * from (select 'asdas' tc) xxx left join t2 on t2.c = any (array(select xxx.tc union all select t1.a::text from t1));",
    paramTypes=0x0, numParams=0) at analyze.c:164
```

Hit Assert Fail if compiling with cassert.

```
psql:w.sql:4: FATAL:  Unexpected internal error (parse_relation.c:491)
DETAIL:  FailedAssertion("!(pstate != ((void *)0))", File: "parse_relation.c", Line: 491)
HINT:  Process 113121 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
psql:w.sql:4: connection to server was lost
```

### Step to reproduce the behavior

```sql
create table t(a int, b int, c varchar(32));
create table t1(a int, b int, c int);
create table t2(a int, b int, c text);
explain select * from (select 'asdas' tc) xxx left join 
t2 on t2.c = any (array(select xxx.tc union all select t1.a::text from t1));
```

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/12412
