### ISSUE TITLE
EvalPlanQual PANIC if subplans not belong to planqual contain motion.

### ISSUE THREAD

**Issue by kainwen** [greenplum-db/gpdb#12902]
### Greenplum version or build

6X_STABLE (top commit: a762f295d8113881384504a654df9aae147a748f).

Master does not have the issue (thanks to the refactor commit 1c2489d).

5X dose not have the issue since 5X dose not have GDD.

### Expected behavior

Error out, not PANIC

### Actual behavior

PANIC. The stack of the coredump is:

```
(gdb) bt
#0  0x00007f56db6d6269 in raise (sig=11) at ../sysdeps/unix/sysv/linux/pt-raise.c:35
#1  0x0000000000b41e43 in StandardHandlerForSigillSigsegvSigbus_OnMainThread (processName=0xe412fa "Segment process", postgres_signal_arg=11) at elog.c:5581
#2  0x00000000009b5a3d in CdbProgramErrorHandler (postgres_signal_arg=11) at postgres.c:3556
#3  <signal handler called>
#4  0x00000000007c3c93 in ExecInitMotion (node=0x2ec5450, estate=0x2ef8008, eflags=0) at nodeMotion.c:981
#5  0x000000000076c83e in ExecInitNode (node=0x2ec5450, estate=0x2ef8008, eflags=0) at execProcnode.c:752
#6  0x000000000078d361 in ExecInitAgg (node=0x2ec5060, estate=0x2ef8008, eflags=0) at nodeAgg.c:1954
#7  0x000000000076c519 in ExecInitNode (node=0x2ec5060, estate=0x2ef8008, eflags=0) at execProcnode.c:675
#8  0x0000000000769596 in EvalPlanQualStart (epqstate=0x2ee9aa8, parentestate=0x2ed19e8, planTree=0x2e1ccf8) at execMain.c:4239
#9  0x0000000000768fd3 in EvalPlanQualBegin (epqstate=0x2ee9aa8, parentestate=0x2ed19e8) at execMain.c:4046
#10 0x00000000007682bd in EvalPlanQual (estate=0x2ed19e8, epqstate=0x2ee9aa8, relation=0x2ea6da8, rti=1, lockmode=2, tid=0x7fffafc92980, priorXmax=721) at execMain.c:3571
#11 0x00000000007a44a1 in ExecUpdate (tupleid=0x7fffafc92a00, segid=1, oldtuple=0x0, slot=0x2ef15e8, planSlot=0x2eee058, epqstate=0x2ee9aa8, estate=0x2ed19e8, canSetTag=1 '\001')
    at nodeModifyTable.c:1536
#12 0x00000000007a4ea3 in ExecModifyTable (node=0x2ee9880) at nodeModifyTable.c:1890
#13 0x000000000076d171 in ExecProcNode (node=0x2ee9880) at execProcnode.c:974
#14 0x00000000007672d5 in ExecutePlan (estate=0x2ed19e8, planstate=0x2ee9880, operation=CMD_UPDATE, sendTuples=0 '\000', numberTuples=0, direction=ForwardScanDirection,
    dest=0x2e24310) at execMain.c:2990
#15 0x0000000000763937 in standard_ExecutorRun (queryDesc=0x2e1ef08, direction=ForwardScanDirection, count=0) at execMain.c:1003
#16 0x000000000076351d in ExecutorRun (queryDesc=0x2e1ef08, direction=ForwardScanDirection, count=0) at execMain.c:869
#17 0x00000000009b9a72 in ProcessQuery (portal=0x2ec1a98, stmt=0x2e1c808,
    sourceText=0x2e1b84c "update t_epq_subplans set b = b + 1 where a > -1.5 * (select max(a) from t_epq_subplans);", params=0x2e24218, dest=0x2e24310,
    completionTag=0x7fffafc93080 "") at pquery.c:288
#18 0x00000000009bb8a5 in PortalRunMulti (portal=0x2ec1a98, isTopLevel=1 '\001', dest=0x2e24310, altdest=0x2e24310, completionTag=0x7fffafc93080 "") at pquery.c:1473
#19 0x00000000009badd1 in PortalRun (portal=0x2ec1a98, count=9223372036854775807, isTopLevel=1 '\001', dest=0x2e24310, altdest=0x2e24310, completionTag=0x7fffafc93080 "")
    at pquery.c:1018
#20 0x00000000009b1d72 in exec_mpp_query (query_string=0x2e1b84c "update t_epq_subplans set b = b + 1 where a > -1.5 * (select max(a) from t_epq_subplans);",
    serializedQuerytree=0x0, serializedQuerytreelen=0, serializedPlantree=0x2e1b8a6 "\275\002\002", serializedPlantreelen=2333, serializedParams=0x2e1c1c3 "\220\002\002",
    serializedParamslen=48, serializedQueryDispatchDesc=0x2e1c1f3 "\027", serializedQueryDispatchDesclen=370) at postgres.c:1381
#21 0x00000000009b8409 in PostgresMain (argc=1, argv=0x2e29a70, dbname=0x2e29970 "gpadmin", username=0x2e29950 "gpadmin") at postgres.c:5400
```

### Step to reproduce the behavior

The following SQL is running under isolation2 framework.

First turn on gdd:

```bash
gpconfig -c gp_enable_global_deadlock_detector -v on
gpstop -rai
```

```sql
-- test eval planqual with initPlan
-- EvalPlanQualStart will init all subplans even if it does
-- not use it. If such subplan contains Motion nodes, we should
-- error out just like the behavior in EvalPlanQual.
1: create table t_epq_subplans(a int, b int);
1: insert into t_epq_subplans values (1, 1);
1: begin;
1: update t_epq_subplans set b = b + 1;

-- make sure planner will contain InitPlan
-- NOTE: orca does not generate InitPlan.
2: explain update t_epq_subplans set b = b + 1 where a > -1.5 * (select max(a) from t_epq_subplans);
2&: update t_epq_subplans set b = b + 1 where a > -1.5 * (select max(a) from t_epq_subplans);

1: end;
```

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/12888
