### ISSUE TITLE
Segmentation fault on column orientation ctas with no data tables

### ISSUE THREAD

**Issue by efimkin** [greenplum-db/gpdb#12936]
## Bug Report
Hi!
Using **CTAS with NO DATA** with **gp_default_storage_options=AO and CO** crash the server, pg_attribute_encoding is empty
```
CREATE TABLE test AS (SELECT 'test' as test) WITH NO DATA;

postgres=# select oid,reloptions from pg_class where relname = 'test';
   oid    |                       reloptions
----------+--------------------------------------------------------
 22060376 | {appendonly=true,compresstype=zstd,orientation=column}
(1 row)

postgres=# select * from pg_attribute_encoding where attrelid=22060376;
 attrelid | attnum | attoptions
----------+--------+------------
(0 rows)

```
### Greenplum version or build
6.17.5
### OS version and uname -a
Linux gp6master 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
### Expected behavior
no segmentation fault 
### Actual behavior
Segmentation fault 
### Step to reproduce the behavior
```
postgres=# set  gp_default_storage_options to 'appendonly=true,compresstype=zstd,compresslevel=1,checksum=true'
;
SET

postgres=#  CREATE TABLE test AS (SELECT 'test' as test) WITH NO DATA;
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause. Creating a NULL policy entry.
WARNING:  column "test" has type "unknown"
DETAIL:  Proceeding with relation creation anyway.
CREATE TABLE AS
postgres=# select * from test;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.

```
in log
```
2021-12-15 17:04:53.092095 MSK,,,p835953,th-1166072640,,,,0,,,seg-1,,,,,"LOG","00000","server process (PID 2542445) was terminated by signal 11: Segmentation fault","Failed process was running: select * from test;",,,,,,0,,"postmaster.c",3970,
```
back trace
```
#0  raise (sig=sig@entry=11) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x0000557bcce00ee0 in StandardHandlerForSigillSigsegvSigbus_OnMainThread (processName=<optimized out>, postgres_signal_arg=11) at elog.c:5579
#2  <signal handler called>
#3  open_ds_read (checksum=<optimized out>, num_proj_atts=<optimized out>, proj_atts=<optimized out>, relationTupleDesc=0x557bd095bfb8, ds=0x557bcfc044c8, rel=0x557bd095bc98) at aocsam.c:206
#4  aocs_initscan (scan=scan@entry=0x557bcfc04528) at aocsam.c:267
#5  0x0000557bcca5a3c6 in aocs_beginscan_internal (relation=relation@entry=0x557bd095bc98, seginfo=0x0, total_seg=0, snapshot=snapshot@entry=0x557bcfdffa08,
    appendOnlyMetaDataSnapshot=appendOnlyMetaDataSnapshot@entry=0x557bcfdffa08, relationTupleDesc=0x557bd095bfb8, relationTupleDesc@entry=0x0, proj=0x557bd0648bf0 "\001\001\001\320{U") at aocsam.c:492
#6  0x0000557bcca5ae2e in aocs_beginscan (relation=relation@entry=0x557bd095bc98, snapshot=0x557bcfdffa08, appendOnlyMetaDataSnapshot=0x557bcfdffa08, relationTupleDesc=relationTupleDesc@entry=0x0,
    proj=proj@entry=0x557bd0648bf0 "\001\001\001\320{U") at aocsam.c:423
#7  0x0000557bccba4057 in InitScanRelation (estate=0x557bd0646c28, eflags=16, currentRelation=0x557bd095bc98, node=0x557bcfc03bf8) at nodeSeqscan.c:182
#8  ExecInitSeqScanForPartition (node=node@entry=0x557bcff5ac28, estate=estate@entry=0x557bd0646c28, eflags=eflags@entry=16, currentRelation=0x557bd095bc98) at nodeSeqscan.c:268
#9  0x0000557bccba40d0 in ExecInitSeqScan (node=node@entry=0x557bcff5ac28, estate=estate@entry=0x557bd0646c28, eflags=eflags@entry=16) at nodeSeqscan.c:217
#10 0x0000557bccb7cb50 in ExecInitNode (node=0x557bcff5ac28, estate=estate@entry=0x557bd0646c28, eflags=eflags@entry=16) at execProcnode.c:403
#11 0x0000557bccbb3a8f in ExecInitMotion (node=node@entry=0x557bcff5a858, estate=estate@entry=0x557bd0646c28, eflags=eflags@entry=16) at nodeMotion.c:1023
#12 0x0000557bccb7dc52 in ExecInitNode (node=node@entry=0x557bcff5a858, estate=estate@entry=0x557bd0646c28, eflags=eflags@entry=16) at execProcnode.c:752
#13 0x0000557bccb7b9fe in InitPlan (eflags=16, queryDesc=0x557bcfd5f518) at execMain.c:2077
#14 standard_ExecutorStart (queryDesc=0x557bcfd5f518, eflags=16) at execMain.c:560
#15 0x0000557bcccf3a82 in PortalStart (portal=portal@entry=0x557bcfd5d508, params=params@entry=0x0, eflags=eflags@entry=0, snapshot=snapshot@entry=0x0, ddesc=ddesc@entry=0x0) at pquery.c:732
#16 0x0000557bcccedba5 in exec_simple_query (query_string=0x557bcfbfb158 "select * from test;") at postgres.c:1796
#17 0x0000557bcccf1965 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x557bcfc4f7d8, dbname=<optimized out>, username=<optimized out>) at postgres.c:5257
#18 0x0000557bcc9a72ab in BackendRun (port=0x557bcfc3f300) at postmaster.c:4811
#19 BackendStartup (port=0x557bcfc3f300) at postmaster.c:4468
#20 ServerLoop () at postmaster.c:1948
#21 0x0000557bccc8ac7d in PostmasterMain (argc=6, argv=0x557bcfbd8990) at postmaster.c:1518
#22 0x0000557bcc9a8c28 in main (argc=6, argv=0x557bcfbd8990) at main.c:245
```

**Comment by efimkin** [comment]
6.19: reproduce
master: do not reproduce

**Comment by saaarenadataio** [comment]
Steps to reproduce are a bit incomplete. There should be:

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/issues/12947

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/12937
