### ISSUE TITLE
Error when planning multi-column NOT IN with NULL value

### ISSUE THREAD

**Issue by khannaekta** [greenplum-db/gpdb#13212]
### Greenplum version or build
master

### OS version and uname -a
OSX (11.4) 
### Expected behavior
No error and generate a plan
```
explain  select 1 from t1 where (NULL, b) not in (select a, b from t2);
                                              QUERY PLAN
------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice2; segments: 3)  (cost=10000000000.00..10000000002.11 rows=4 width=0)
   ->  Nested Loop Left Anti Semi (Not-In) Join  (cost=10000000000.00..10000000002.11 rows=2 width=0)
         Join Filter: ((t1_12930.b = t2_12930.b) AND NULL::boolean)
         ->  Seq Scan on t1_12930  (cost=0.00..1.01 rows=1 width=4)
         ->  Materialize  (cost=0.00..1.06 rows=1 width=4)
               ->  Broadcast Motion 3:3  (slice1; segments: 3)  (cost=0.00..1.05 rows=1 width=4)
                     ->  Seq Scan on t2_12930  (cost=0.00..1.01 rows=1 width=4)
 Optimizer: Postgres query optimizer
 ```

### Actual behavior
```
explain  select 1 from t1 where (NULL, b) not in (select a, b from t2);
ERROR:  unexpected join qual in JOIN_LASJ_NOTIN join (nodeNestloop.c:769)
```
### Step to reproduce the behavior
```
create table t1(a int not null, b int not null);
create table t2(a int not null, b int not null);
explain  select 1 from t1 where (NULL, b) not in (select a, b from t2);

```

**Comment by kainwen** [comment]
Thanks for reporting this with detailed reproducible steps.

ORCA will fallback to planner. Both 6X and master branch has the bug.

Master branch  (top commit 36a5b3de20 )will raise an error as desc in the issue's context.

6X (top commit 39cf4398730d) will hit assert fail:
```
gpadmin=# explain  select 1 from t1 where (NULL, b) not in (select a, b from t2);
INFO:  GPORCA failed to produce a plan, falling back to planner
DETAIL:  Feature not supported: Non-Scalar Subquery
FATAL:  Unexpected internal error (nodeNestloop.c:658)
DETAIL:  FailedAssertion("!(((((const Node*)(fstate))->type) == T_FuncExprState))", File: "nodeNestloop.c", Line: 658)
HINT:  Process 23227 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fced3ad2ffb in __GI___select (nfds=0, readfds=0x0, writefds=0x0, exceptfds=0x0, timeout=0x7ffe4bfcaa50) at ../sysdeps/unix/sysv/linux/select.c:41
41      ../sysdeps/unix/sysv/linux/select.c: No such file or directory.
(gdb) bt
#0  0x00007fced3ad2ffb in __GI___select (nfds=0, readfds=0x0, writefds=0x0, exceptfds=0x0, timeout=0x7ffe4bfcaa50) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x0000557f4ce848b6 in pg_usleep (microsec=30000000) at pgsleep.c:56
#2  0x0000557f4c9655ff in elog_debug_linger (edata=0x557f4d5fb8c0 <errordata>) at elog.c:5294
#3  0x0000557f4c95aed7 in errfinish (dummy=0) at elog.c:670
#4  0x0000557f4c959539 in ExceptionalCondition (conditionName=0x557f4d0056f8 "!(((((const Node*)(fstate))->type) == T_FuncExprState))",
    errorType=0x557f4d0054b9 "FailedAssertion", fileName=0x557f4d0055ba "nodeNestloop.c", lineNumber=658) at assert.c:46
#5  0x0000557f4c5ac504 in splitJoinQualExpr (nlstate=0x557f54f61ea8) at nodeNestloop.c:658
#6  0x0000557f4c5ac313 in ExecInitNestLoop (node=0x557f54f5f450, estate=0x557f54f61008, eflags=19) at nodeNestloop.c:543
#7  0x0000557f4c56fdc3 in ExecInitNode (node=0x557f54f5f450, estate=0x557f54f61008, eflags=17) at execProcnode.c:604
#8  0x0000557f4c5cc536 in ExecInitMotion (node=0x557f54f60580, estate=0x557f54f61008, eflags=17) at nodeMotion.c:1103
#9  0x0000557f4c5703e8 in ExecInitNode (node=0x557f54f60580, estate=0x557f54f61008, eflags=17) at execProcnode.c:752
#10 0x0000557f4c568fd5 in InitPlan (queryDesc=0x557f54f60a40, eflags=17) at execMain.c:2172
#11 0x0000557f4c56619d in standard_ExecutorStart (queryDesc=0x557f54f60a40, eflags=17) at execMain.c:567
```

-----------

A quick try locally to reject converting such case can fix the issue. Need more time to look deep into and then give a fix.

**Comment by kainwen** [comment]
6X's code is not the same as master branch, I see https://github.com/greenplum-db/gpdb-postgres-merge/commit/f10a125fe2cd6c10d34b17640c3694e3423bbc15 in merge repo changes the logic.

Need more time to see how to fix this in 6X.

**Comment by lij55** [comment]
I got a crash on 6X
```sql
test=# explain  select 1 from t1 where (NULL, b) not in (select a, b from t2);
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```
 the log are:
```
2022-03-24 20:59:29.059420 UTC,"gpadmin","test",p1814,th-1702377344,"[local]",,2022-03-24 20:59:28 UTC,0,con4,cmd1,seg-1,,,,sx1,"LOG","00000","statement: explain  select 1 from t1 where (NULL, b) not in (select a, b from t2);",,,,,,"explain  select 1 from t1 where (NULL, b) not in (select a, b from t2);",0,,"postgres.c",1667,
2022-03-24 20:59:29.069029 UTC,"gpadmin","test",p1814,th-1702377344,"[local]",,2022-03-24 20:59:28 UTC,0,con4,cmd1,seg-1,,,,sx1,"LOG","00000","2022-03-24 20:59:29:068869 UTC,THD000,NOTICE,""Feature not supported: Non-Scalar Subquery"",
",,,,,,"explain  select 1 from t1 where (NULL, b) not in (select a, b from t2);",0,,"COptTasks.cpp",271,
2022-03-24 20:59:29.160011 UTC,,,p1814,th0,,,2022-03-24 20:59:28 UTC,0,con4,cmd2,seg-1,,,,,"PANIC","XX000","Unexpected internal error: Master process received signal SIGSEGV",,,,,,,0,,,,"1    0x7f2c97e73630 libpthread.so.0 <symbol not found> + 0x97e73630
2    0x8bcdbb postgres ExecInitNode (execProcnode.c:607)
3    0x8fe8af postgres ExecInitMotion (nodeMotion.c:1100)
4    0x8bd85d postgres ExecInitNode (execProcnode.c:755)
5    0x8b82f1 postgres standard_ExecutorStart (execMain.c:2079)
6    0x84ad77 postgres ExplainOnePlan (explain.c:589)
7    0x84b49e postgres <symbol not found> (explain.c:425)
8    0x84b9f5 postgres ExplainQuery (explain.c:260)
9    0xa8f5bc postgres standard_ProcessUtility (utility.c:801)
10   0x7f2c9350965a metrics_collector.so AdaptorProcessUtility + 0x72
11   0x7f2c9350999d metrics_collector.so EmitUtilityQueryInfo + 0x340
12   0xa8bc01 postgres <symbol not found> (palloc.h:158)
13   0xa8c91f postgres <symbol not found> (pquery.c:1262)
14   0xa8dfb7 postgres PortalRun (pquery.c:987)
15   0xa88510 postgres <symbol not found> (postgres.c:1855)
16   0xa8accd postgres PostgresMain (postgres.c:5266)
```
