### ISSUE TITLE
ERROR: DTX RollbackAndReleaseCurrentSubTransaction dispatch failed

### ISSUE THREAD

**Issue by vzaigrin** [greenplum-db/gpdb#13407]
### Greenplum version or build
PostgreSQL 9.4.26 (Greenplum Database 6.19.3 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit compiled on Mar 11 2022 16:58:17

### Actual behavior
From time to time we get this error message:

ERROR:CODE=23098
error in postgresql
Error:ERROR: DTX RollbackAndReleaseCurrentSubTransaction dispatch failed
Where: PL/pgSQL function s_grnplm_as_cib_cc360_dmp4dfnsegr_tmd.sp_ext2stg(character varying,character varying,character varying,text,text,text,bigint,integer,integer) line 82 during exception cleanup
Exception:org.postgresql.util.PSQLException: ERROR: DTX RollbackAndReleaseCurrentSubTransaction dispatch failed
Where: PL/pgSQL function s_grnplm_as_cib_cc360_dmp4dfnsegr_tmd.sp_ext2stg(character varying,character varying,character varying,text,text,text,bigint,integer,integer) line 82 during exception cleanup
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2427)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2169)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:224)
at sbt.etl.common.GreenplumMigrationUtils.executeGreenplumFunctionOutParameters(GreenplumMigrationUtils.java:209)
at sbt.etl.Thread.run_R_EtlThread.runR(run_R_EtlThread.java:905)
at sbt.etl.Thread.run_R_EtlThread.run(run_R_EtlThread.java:222)
at java.lang.Thread.run(Thread.java:748)

**Comment by ashwinstar** [comment]
Without information on repro steps or mini-repro for the query next to impossible to help. Please can you provide more context on the error you are facing and then team can help out. Thanks.
