### ISSUE TITLE
format string used in pg_log_error() should not end with '\n'

### ISSUE THREAD

**Issue by ppggff** [greenplum-db/gpdb#13700]
### Greenplum version or build
master 59eb92381d

### OS version and uname -a
Linux 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior
no coredump

### Actual behavior
coredump

### Step to reproduce the behavior
run initdb, datadir in sharedfolder of virtualbox (host macos, guest centos)

init coredump
```
#0  0x00007fdb19452387 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-325.el7_9.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-51.el7_9.x86_64 libcom_err-1.42.9-19.el7.x86_64 libselinux-2.5-15.el7.x86_64 pcre-8.32-17.el7.x86_64
(gdb) bt
#0  0x00007fdb19452387 in raise () from /lib64/libc.so.6
#1  0x00007fdb19453a78 in abort () from /lib64/libc.so.6
#2  0x00007fdb1944b1a6 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007fdb1944b252 in __assert_fail () from /lib64/libc.so.6
#4  0x0000000000411dcc in pg_log_generic_v (level=PG_LOG_ERROR, fmt=0x418cb4 "%s: error %d from: %s", ap=0x7ffde5c78e08) at logging.c:148
#5  0x0000000000411d01 in pg_log_generic (level=PG_LOG_ERROR, fmt=0x418cb4 "%s: error %d from: %s") at logging.c:131
#6  0x00000000004049ed in test_config_settings () at initdb.c:1029
#7  0x0000000000408643 in initialize_data_directory () at initdb.c:3206
#8  0x0000000000409126 in main (argc=14, argv=0x7ffde5c79c68) at initdb.c:3579
(gdb) f 4
#4  0x0000000000411dcc in pg_log_generic_v (level=PG_LOG_ERROR, fmt=0x418cb4 "%s: error %d from: %s", ap=0x7ffde5c78e08) at logging.c:148
148		Assert(fmt[strlen(fmt) - 1] != '\n');
(gdb) f 6
#6  0x00000000004049ed in test_config_settings () at initdb.c:1029
warning: Source file is more recent than executable.
1029				pg_log_error("%s: error %d from: %s\n",
```

**Comment by higuoxing** [comment]
Fixed in 2eda3855b1ece046d672c7662da9aed9d5afc7a3. If there's any problem, feel free to re-open this issue.
