### ISSUE TITLE
[7X] Assertion failure happens in src/backend/access/common/relation.c

### ISSUE THREAD

**Issue by higuoxing** [greenplum-db/gpdb#14417]
### Greenplum version or build

`main` branch.

### OS version and uname -a

```
➜ uname -a
Linux laptop 6.0.7-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 03 Nov 2022 18:02:00 +0000 x86_64 GNU/Linux
```

### autoconf options used ( config.status --config )

```
➜ ./config.status --config
'--with-perl' '--with-python' '--with-libxml' '--with-gssapi' '--enable-debug' '--enable-cassert' '--enable-debug-extensions' '--with-uuid=e2fs' '--prefix=/home/v/.local/gpdb7' 'CC=/usr/bin/clang' 'CXX=/usr/bin/clang++'
```

### Installation information ( pg_config )

```
➜ pg_config
BINDIR = /home/v/.local/gpdb7/bin
DOCDIR = /home/v/.local/gpdb7/share/doc/postgresql
HTMLDIR = /home/v/.local/gpdb7/share/doc/postgresql
INCLUDEDIR = /home/v/.local/gpdb7/include
PKGINCLUDEDIR = /home/v/.local/gpdb7/include/postgresql
INCLUDEDIR-SERVER = /home/v/.local/gpdb7/include/postgresql/server
LIBDIR = /home/v/.local/gpdb7/lib
PKGLIBDIR = /home/v/.local/gpdb7/lib/postgresql
LOCALEDIR = /home/v/.local/gpdb7/share/locale
MANDIR = /home/v/.local/gpdb7/share/man
SHAREDIR = /home/v/.local/gpdb7/share/postgresql
SYSCONFDIR = /home/v/.local/gpdb7/etc/postgresql
PGXS = /home/v/.local/gpdb7/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-perl' '--with-python' '--with-libxml' '--with-gssapi' '--enable-debug' '--enable-cassert' '--enable-debug-extensions' '--with-uuid=e2fs' '--prefix=/home/v/.local/gpdb7' 'CC=/usr/bin/clang' 'CXX=/usr/bin/clang++'
CC = /usr/bin/clang
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-but-set-variable -Wno-unused-command-line-argument -g -O3  -Werror=uninitialized -Werror=implicit-function-declaration
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/home/v/.local/gpdb7/lib',--enable-new-dtags
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lnuma -lxerces-c -lbz2 -lxml2 -lrt -lgssapi_krb5 -lz -lreadline -lcrypt -lm  -lcurl -lzstd
VERSION = PostgreSQL 12beta2
```

### Step to reproduce the behavior

```sql
CREATE EXTERNAL WEB TABLE dummy(x int) EXECUTE 'touch /tmp/dummy2.csv;cat /tmp/dummy2.csv' ON MASTER FORMAT 'csv';
CREATE TABLE foo(x int);
DELETE FROM foo WHERE x IN (SELECT x FROM dummy);
```

### Actual behavior

```
ERROR:  XX000: Unexpected internal error (assert.c:48)  (seg0 127.0.0.1:7002 pid=102797) (assert.c:48)
DETAIL:  FailedAssertion("!(lockmode != 0 || (Mode == BootstrapProcessing) || CheckRelationLockedByMe(r, 1, 1))", File: "relation.c", Line: 74)
LOCATION:  ExceptionalCondition, assert.c:48
Time: 2392.942 ms (00:02.393)
```

**Comment by Aegeaner** [comment]
The stack trace of dumped core is:
```
(gdb) bt
#0  0x00007f6580aa154c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007f6580a54d46 in raise () from /lib64/libc.so.6
#2  0x00007f6580a287f3 in abort () from /lib64/libc.so.6
#3  0x0000000000d415d3 in ExceptionalCondition (conditionName=0xe8ce1d "!(lockmode != 0 || (Mode == BootstrapProcessing) || CheckRelationLockedByMe(r, 1, 1))", 
    errorType=0xe8606c "FailedAssertion", fileName=0xfe6357 "relation.c", lineNumber=74) at assert.c:44
#4  0x00000000004d048d in relation_open (relationId=17002, lockmode=0) at relation.c:72
#5  0x00000000005bab99 in table_open (relationId=17002, lockmode=0) at table.c:48
#6  0x00000000008a0ca2 in ExecInitModifyTable (node=0x28b8c88, estate=0x29c0010, eflags=0) at nodeModifyTable.c:3000
#7  0x0000000000861fe1 in ExecInitNode (node=0x28b8c88, estate=0x29c0010, eflags=0) at execProcnode.c:238
#8  0x000000000085626f in InitPlan (queryDesc=0x28e47d0, eflags=0) at execMain.c:1973
#9  0x0000000000854e57 in standard_ExecutorStart (queryDesc=0x28e47d0, eflags=0) at execMain.c:581
#10 0x00000000008540c0 in ExecutorStart (queryDesc=0x28e47d0, eflags=0) at execMain.c:203
#11 0x0000000000b5b786 in ProcessQuery (portal=0x29742c0, stmt=0x28f9c58, sourceText=0x28b7897 "DELETE FROM foo WHERE x IN (SELECT x FROM dummy);", params=0x0, 
    queryEnv=0x0, dest=0x29be0f0, completionTag=0x7fff84630950 "") at pquery.c:237
```
And I found a GPDB_91_MERGE FIXME left around range table locking code: https://github.com/greenplum-db/gpdb/blob/05b333dfdc03d0477fafe132b10c0cfa2a19d5ae/src/backend/executor/nodeModifyTable.c#L2991~L2993

I guess we should call `CheckRelationLockedByMe()` before using the `NoLock` mode to open the relation, to make the assertion happy:
https://github.com/greenplum-db/gpdb/blob/05b333dfdc03d0477fafe132b10c0cfa2a19d5ae/src/backend/access/common/relation.c#L74

**Comment by Aegeaner** [comment]
Close this as 7X only and got fixed.
