### ISSUE TITLE
installing madlib for Greenplum crashes with a Python error

### ISSUE THREAD

**Issue by dmitrynovik** [greenplum-db/gpdb#14514]
### Greenplum version or build
6.21.3

### OS version and uname -a
Linux ubuntu 5.4.0-132-generic #148~18.04.1-Ubuntu SMP Mon Oct 24 20:41:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
no such thing:
```
 which config.status
```
returns nothing. Possibly the root cause of the issue, but it would be nice to have a more meaningful error message than the crash below.

### Installation information ( pg_config )
```
BINDIR = /usr/local/greenplum-db-6.21.3/bin
DOCDIR = /usr/local/greenplum-db-6.21.3/share/doc/postgresql
HTMLDIR = /usr/local/greenplum-db-6.21.3/share/doc/postgresql
INCLUDEDIR = /usr/local/greenplum-db-6.21.3/include
PKGINCLUDEDIR = /usr/local/greenplum-db-6.21.3/include/postgresql
INCLUDEDIR-SERVER = /usr/local/greenplum-db-6.21.3/include/postgresql/server
LIBDIR = /usr/local/greenplum-db-6.21.3/lib
PKGLIBDIR = /usr/local/greenplum-db-6.21.3/lib/postgresql
LOCALEDIR = /usr/local/greenplum-db-6.21.3/share/locale
MANDIR = /usr/local/greenplum-db-6.21.3/man
SHAREDIR = /usr/local/greenplum-db-6.21.3/share/postgresql
SYSCONFDIR = /usr/local/greenplum-db-6.21.3/etc/postgresql
PGXS = /usr/local/greenplum-db-6.21.3/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--disable-debug-extensions' '--disable-tap-tests' '--enable-orca' '--with-zstd' '--with-gssapi' '--with-libxml' '--with-perl' '--with-python' '--with-openssl' '--with-pam' '--with-ldap' '--with-extra-version= Open Source' '--prefix=/usr/local/greenplum-db-6.21.3' '--mandir=/usr/local/greenplum-db-6.21.3/man' 'CC=gcc' 'CFLAGS=-O3 -fargument-noalias-global -fno-omit-frame-pointer -g'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/greenplum-db-6.21.3/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -Werror=implicit-fallthrough=3 -Wno-format-truncation -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/greenplum-db-6.21.3/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/greenplum-db-6.21.3/lib',--enable-new-dtags -L/usr/local/greenplum-db-6.21.3/lib
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lxerces-c -lxml2 -lpam -lrt -lgssapi_krb5 -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/greenplum-db-6.21.3/lib
VERSION = PostgreSQL 9.4.26

```

### Expected behavior
Installation to complete

### Actual behavior
```
gppkg -i madlib-1.20.0+1-gp6-rhel8-x86_64.gppkg  -v
20221121:18:43:47:123639 gppkg:ubuntu:dmitry-[INFO]:-Starting gppkg with args: -i madlib-1.20.0+1-gp6-rhel8-x86_64.gppkg -v
20221121:18:43:47:123639 gppkg:ubuntu:dmitry-[DEBUG]:-Connecting to dbname='postgres'
20221121:18:43:47:123639 gppkg:ubuntu:dmitry-[DEBUG]:-Running Command: dpkg --version
20221121:18:43:47:123639 gppkg:ubuntu:dmitry-[DEBUG]:-Running Command: fakeroot --version
20221121:18:43:47:123639 gppkg:ubuntu:dmitry-[DEBUG]:-_get_master_port
20221121:18:43:47:123639 gppkg:ubuntu:dmitry-[DEBUG]:-_get_gpdb_host_list
20221121:18:43:47:123639 gppkg:ubuntu:dmitry-[DEBUG]:-Connecting to dbname='template1'
20221121:18:43:47:123639 gppkg:ubuntu:dmitry-[DEBUG]:-from_package_path
20221121:18:43:47:123639 gppkg:ubuntu:dmitry-[ERROR]:-gppkg failed.  exiting...
Traceback (most recent call last):
  File "/usr/local/greenplum-db-6.21.3/lib/python/gppylib/mainUtils.py", line 342, in simple_main_locked
    exitCode = commandObject.run()
  File "/usr/local/greenplum-db-6.21.3/lib/python/gppylib/programs/gppkg.py", line 229, in run
    pkg = Gppkg.from_package_path(self.install)
  File "/usr/local/greenplum-db-6.21.3/lib/python/gppylib/operations/package.py", line 284, in from_package_path
    gppkg = Gppkg(**pkg)
TypeError: __init__() takes exactly 17 arguments (16 given)

```
### Step to reproduce the behavior
gppkg -i madlib-1.20.0+1-gp6-rhel8-x86_64.gppkg  -v

NOTE: a similar issue was opened in 2019 but closed without an explanation:
https://github.com/greenplum-db/gpdb/issues/9220

**Comment by gpopt** [comment]
@orhankislal please take a look.

**Comment by ashwinstar** [comment]
@orhankislal any findings/hint on the issue?

**Comment by orhankislal** [comment]
This seems like a python version issue. Considering it is rhel8, python3 might be set as default. In addition, the error comes from the gppkg tool, not the madlib package. We need the outputs of the following commands:
- which python
- python --version
- gppkg --version

**Comment by ashwinstar** [comment]
@dmitrynovik let us know if still facing the problem and if yes please provide the requested info above. If not still facing the problem, please feel free to close the issue. Thanks.

**Comment by dmitrynovik** [comment]
may I suggest that in your installation script you use `python3` in place of `python` - ?

**Comment by orhankislal** [comment]
1- As I mentioned, this is a gppkg error. You'll need a Greenplum installation with python3 support which starts with GP7. GP6 has python3 support via an extension but this is only for the database, not the utilities like gppkg. 
2- MADlib support for python3 (GP6, GP7 and PG13) is currently in the works. The code has been merged to https://github.com/apache/madlib/tree/madlib2-master and we are working towards a release. 
Could you provide the outputs of the three aforementioned commands?
