### ISSUE TITLE
PANIC under legacy planner of NOT-IN SQL.

### ISSUE THREAD

**Issue by kainwen** [greenplum-db/gpdb#14858]
### Greenplum version or build

Both 
* main  (top commit: 98e79490a26d0d9db4c9239ee1c4b33d8af65ec0), and 
* 6X_STABLE (top commit: 99e46e42d9e7e1aae1dde044238d068e08fec0dc).

### Step to reproduce the behavior

```sql
create table t1(a varchar(32), b varchar(32), c int, d int);
create table t2(a varchar(32), b varchar(32), c int, d int);
create table t3(a varchar(32), b varchar(32), c int, d int);

create view mv as select * from t1 full join
(select a, b, count(c) from t2 group by a,b union
 select a, b, count(c) from t3 group by a, b) x using (a, b);

-- PANIC or AssertFail
explain select * from mv where a not in (select a from t1);
```

Run it will lead to:

```
gpadmin@zlyu:~$ psql -f a.sql
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE VIEW
psql:a.sql:10: FATAL:  Unexpected internal error (assert.c:44)
DETAIL:  FailedAssertion("!(n < list->length)", File: "list.c", Line: 392)
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
psql:a.sql:10: fatal: connection to server was lost
```

the coredump's stack is:

```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140182525505280) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140182525505280) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140182525505280, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f7ecc859476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f7ecc83f7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000555e122f298b in ExceptionalCondition (conditionName=0x555e125f374c "!(n < list->length)", errorType=0x555e125f34a7 "FailedAssertion",
    fileName=0x555e125f34a0 "list.c", lineNumber=392) at assert.c:44
#6  0x0000555e11ee7ef5 in list_nth_cell (list=0x555e12d10ee0, n=1042) at list.c:392
#7  0x0000555e11ee8026 in list_nth (list=0x555e12d10ee0, n=1042) at list.c:428
#8  0x0000555e123fe8a1 in cdb_map_to_base_var (var=0x555e12d16eb8, rtable=0x555e12d10ee0) at cdbsubselect.c:1628
#9  0x0000555e123fe7e4 in cdb_find_all_vars_walker (node=0x555e12d10318, context=0x7ffe7b7d0b80) at cdbsubselect.c:1609
#10 0x0000555e11ee1873 in expression_tree_walker (node=0x555e12d18008, walker=0x555e123fe782 <cdb_find_all_vars_walker>, context=0x7ffe7b7d0b80)
    at nodeFuncs.c:2224
```

**Comment by kainwen** [comment]
Fixed by:

* main branch: https://github.com/greenplum-db/gpdb/pull/14859
* 6X branch: https://github.com/greenplum-db/gpdb/pull/14895
