### ISSUE TITLE
Python's module Hashlib error while deploying Greenplum DB v. 6.23.0 in Debian Linux 10-like OS

### ISSUE THREAD

**Issue by mshta** [greenplum-db/gpdb#14932]
### Greenplum version or build
6.23.0.

### OS version and uname -a
OS: Astra Linux SE 1.7 (based on OS Debian Linux 10.0).
uname -a data: Linux osalse173 5.15.0-33-generic #astra2+ci96 SMP Fri Oct 28 18:23:37 UTC 2022 x86_64 GNU/Linux.

### autoconf options used ( config.status --config )
N/a.

### Installation information ( pg_config )
N/a.

### Expected behavior
Normal running of application gpssh-exkeys in following OS.

### Actual behavior
Error while execution following command:

\# gpssh-exkeys -f hostfile 
Traceback (most recent call last):
  File "/usr/local/greenplum-db-6.23.0/bin/gpssh-exkeys", line 49, in <module>
    import tempfile, filecmp
  File "/usr/local/greenplum-db-6.23.0/ext/python/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "/usr/local/greenplum-db-6.23.0/ext/python/lib/python2.7/random.py", line 49, in <module>
    import hashlib as _hashlib
  File "/usr/local/greenplum-db-6.23.0/ext/python/lib/python2.7/hashlib.py", line 127, in <module>
    new = __py_new
NameError: name '__py_new' is not defined

### Step to reproduce the behavior
Installing Greenplum in following OS with YouTube-video guide (https://www.youtube.com/watch?v=-T3zl7aE0Yk) and trying to run in OS gpssh-exkeys (at 7:39 in the video).

**Comment by mshta** [comment]
This bug is fixed via installing in the OS following deb-package [libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb](http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0/_1.0.2n-1ubuntu5/_amd64.deb).
