### ISSUE TITLE
Master went into recovery from SIGSEGV

### ISSUE THREAD

**Issue by Aegeaner** [greenplum-db/gpdb#15112]
### Greenplum version or build
5.29.5

### Step to reproduce the behavior

The master went into recovery twice. It seems to have been caused by users cancelling queries.

There are 2 dumps:

packcore-core.11234
packcore-core.28006

Backtrace from thread 2 of packcore-core.11234:

```
(gdb) bt
#0  0x00007fc025ab1630 in sigprocmask () from /data/logs/340100/packcore-core.11234/lib64/libc.so.6
#1  0x00007fc025ab1219 in siglongjmp () from /data/logs/340100/packcore-core.11234/lib64/libc.so.6
#2  0x00007fc02670338b in siglongjmp () from /data/logs/340100/packcore-core.11234/lib64/libpthread.so.0
#3  0x0000000000968efa in pg_re_throw () at elog.c:1673
#4  0x00000000005ef98a in parserOpenTable (pstate=pstate@entry=0x3a764f8, relation=relation@entry=0x3a479d8, lockmode=lockmode@entry=1, lockUpgraded=0x0) at parse_relation.c:771
#5  0x00000000005f04c5 in addRangeTableEntry (pstate=pstate@entry=0x3a764f8, relation=relation@entry=0x3a479d8, alias=0x3a47aa8, inh=<optimized out>, inFromCl=inFromCl@entry=1 '\001') at parse_relation.c:812
#6  0x00000000005e1c0e in transformTableEntry (r=0x3a479d8, pstate=0x3a764f8) at parse_clause.c:1087
#7  transformFromClauseItem (pstate=pstate@entry=0x3a764f8, n=0x3a479d8, top_rte=top_rte@entry=0x7ffc65b3c818, top_rti=top_rti@entry=0x7ffc65b3c814, relnamespace=relnamespace@entry=0x7ffc65b3c820, containedRels=containedRels@entry=0x7ffc65b3c828) at parse_clause.c:1378
#8  0x00000000005e34db in transformFromClause (pstate=pstate@entry=0x3a764f8, frmList=<optimized out>) at parse_clause.c:148
#9  0x00000000005bbdbc in transformSelectStmt (stmt=0x3494d48, pstate=0x3a764f8) at analyze.c:1552
#10 transformStmt (pstate=pstate@entry=0x3a764f8, parseTree=parseTree@entry=0x3494d48) at analyze.c:301
#11 0x00000000005bdc2c in parse_sub_analyze (parentParseState=0x3a5c220, parseTree=0x3494d48) at analyze.c:232
#12 transformSetOperationTree_internal (pstate=pstate@entry=0x3a5c220, stmt=0x3494d48, setop_types=setop_types@entry=0x7ffc65b3cf80) at analyze.c:2359
#13 0x00000000005bde5b in transformSetOperationTree_internal (pstate=pstate@entry=0x3a5c220, stmt=0x3483908, setop_types=setop_types@entry=0x7ffc65b3cf80) at analyze.c:2460
#14 0x00000000005bde41 in transformSetOperationTree_internal (pstate=pstate@entry=0x3a5c220, stmt=0x34837f8, setop_types=setop_types@entry=0x7ffc65b3cf80) at analyze.c:2458
#15 0x00000000005bde41 in transformSetOperationTree_internal (pstate=pstate@entry=0x3a5c220, stmt=0x34836e8, setop_types=setop_types@entry=0x7ffc65b3cf80) at analyze.c:2458
#16 0x00000000005bde41 in transformSetOperationTree_internal (pstate=pstate@entry=0x3a5c220, stmt=0x34835d8, setop_types=setop_types@entry=0x7ffc65b3cf80) at analyze.c:2458
#17 0x00000000005bde41 in transformSetOperationTree_internal (pstate=pstate@entry=0x3a5c220, stmt=0x34834c8, setop_types=setop_types@entry=0x7ffc65b3cf80) at analyze.c:2458
#18 0x00000000005bde41 in transformSetOperationTree_internal (pstate=pstate@entry=0x3a5c220, stmt=0x34833b8, setop_types=setop_types@entry=0x7ffc65b3cf80) at analyze.c:2458
#19 0x00000000005bde41 in transformSetOperationTree_internal (pstate=pstate@entry=0x3a5c220, stmt=stmt@entry=0x34832a8, setop_types=setop_types@entry=0x7ffc65b3cf80) at analyze.c:2458
#20 0x00000000005bc4dc in transformSetOperationTree (stmt=0x34832a8, pstate=0x3a5c220) at analyze.c:2169
#21 transformSetOperationStmt (stmt=0x34832a8, pstate=0x3a5c220) at analyze.c:1986
#22 transformStmt (pstate=pstate@entry=0x3a5c220, parseTree=parseTree@entry=0x34832a8) at analyze.c:303
#23 0x00000000005bd9f8 in parse_analyze_varparams (parseTree=0x34832a8, 
    sourceText=sourceText@entry=0x336b2e9 ""..., 
    paramTypes=paramTypes@entry=0x7ffc65b3d0d8, numParams=numParams@entry=0x7ffc65b3d0d4) at analyze.c:200
#24 0x0000000000841da2 in exec_parse_message (numParams=<optimized out>, paramTypes=<optimized out>, stmt_name=0x336b2e8 "", 
    query_string=0x336b2e9 ...) at postgres.c:2017
#25 PostgresMain (argc=<optimized out>, argv=argv@entry=0x2e02798, dbname=<optimized out>, username=<optimized out>) at postgres.c:5263
#26 0x00000000007e11c5 in BackendRun (port=0x2e03e90) at postmaster.c:6743
#27 BackendStartup (port=0x2e03e90) at postmaster.c:6419
#28 ServerLoop () at postmaster.c:2444
#29 0x00000000007e399a in PostmasterMain (argc=argc@entry=15, argv=argv@entry=0x2dc2bc0) at postmaster.c:1528
#30 0x00000000004cde27 in main (argc=15, argv=0x2dc2bc0) at main.c:206
```

From the master log.

```
2023-02-24 01:53:32.357051 GMT,"client","merit",p11234,th710518656,"10.3.6.124","62062",2023-02-24 01:50:01 GMT,0,con60377956,cmd17,seg-1,,dx2555360,,sx1,"LOG","00000","execute <unnamed>: SET client_min_messages TO NOTICE",,,,,,"SET client_min_messages TO NOTICE",0,,"postgres.c",275
6,
2023-02-24 02:09:02.033372 GMT,"client","merit",p11234,th237397760,"10.3.6.124","62062",2023-02-24 01:50:01 GMT,0,con60377956,cmd17,seg-1,,dx2555361,,sx1,"LOG","00000","Process interrupt for 'query cancel pending' (postgres.c:3523)",,,,,,"
   :
   :
2023-02-24 02:09:02.036436 GMT,"client","merit",p11234,th245790464,"10.3.6.124","62062",2023-02-24 01:50:01 GMT,0,con60377956,cmd17,seg-1,,dx2555361,,sx1,"LOG","00000","
Unexpected internal error: Master 11234 received signal 11 in worker thread 140462856238848 (forwarding signal to main thread)

",,,,,,,0,,,,
2023-02-24 02:09:02.162090 GMT,,,p11234,th0,,,2023-02-24 01:50:01 GMT,0,con60377956,cmd17,seg-1,,,,,"PANIC","XX000","Unexpected internal error: Master process received signal SIGSEGV",,,,,,,0,,,,"1    0x7fc026704630 libpthread.so.0 <symbol not found> + 0x26704630
2    0x965c1c postgres errfinish (elog.c:640)
3    0x9680f0 postgres elog_finish (discriminator 10)
4    0x83ae29 postgres <symbol not found> (postgres.c:3699)
5    0x83b381 postgres StatementCancelHandler (postgres.c:3629)
6    0x7fc026704630 libpthread.so.0 <symbol not found> + 0x26704630
7    0x82e0c2 postgres ProcSleep (proc.c:1110)
8    0x8297a9 postgres <symbol not found> (discriminator 2)
9    0x82a70d postgres LockAcquire (lock.c:946)
10   0x828a1e postgres LockRelationOid (lmgr.c:96)
11   0x4f72de postgres CdbOpenRelationRv (heapam.c:996)
12   0x5ef9b2 postgres <symbol not found> (parse_relation.c:773)
13   0x5f04c5 postgres addRangeTableEntry (parse_relation.c:813)
14   0x5e1c0e postgres <symbol not found> (parse_clause.c:1381)
15   0x5e34db postgres transformFromClause (discriminator 3)
16   0x5bbdbc postgres transformStmt (analyze.c:1555)
17   0x5bdc2c postgres <symbol not found> (analyze.c:232)
18   0x5bde5b postgres <symbol not found> (discriminator 8)
19   0x5bde41 postgres <symbol not found> (discriminator 8)
20   0x5bde41 postgres <symbol not found> (discriminator 8)
21   0x5bde41 postgres <symbol not found> (discriminator 8)
22   0x5bde41 postgres <symbol not found> (discriminator 8)
23   0x5bde41 postgres <symbol not found> (discriminator 8)
24   0x5bde41 postgres <symbol not found> (discriminator 8)
25   0x5bc4dc postgres transformStmt (analyze.c:2186)
26   0x5bd9f8 postgres parse_analyze_varparams (analyze.c:200)
"
2023-02-24 02:13:17.569693 GMT,"data_owner","merit",p11234,th710518656,"127.0.0.1","57482",2023-02-24 02:13:17 GMT,0,con60385120,,seg-1,,,,sx1,"LOG","00000","rejecting TCP connection to master using internalconnection protocol",,,,,,,0,,"auth.c",362,
```

Log on another day is similar to the above for the packcore packcore-core.28006.
It seems to have been cancelled during the PARSE phase.

```
2023-02-26 02:30:33.704430 GMT,"client","merit",p28006,th710518656,"10.3.6.124","58859",2023-02-26 02:25:34 GMT,0,con61850005,cmd19,seg-1,,dx1688097,,sx1,"LOG","00000","execute <unnamed>:",0,,"postgres.c",2756,
2023-02-26 02:46:02.804770 GMT,"client","merit",p28006,th134215424,"10.3.6.124","58859",2023-02-26 02:25:34 GMT,0,con61850005,cmd19,seg-1,,dx1688099,,sx1,"LOG","00000",,,,,,,"
  :
  :
  2023-02-26 02:46:02.805398 GMT,"client","merit",p28006,th125822720,"10.3.6.124","58859",2023-02-26 02:25:34 GMT,0,con61850005,cmd19,seg-1,,dx1688099,,sx1,"LOG","00000","Process interrupt for 'query cancel pending' (postgres.c:3523)",,,,,,"
    :
    :
2023-02-26 02:46:02.805964 GMT,"client","merit",p28006,th125822720,"10.3.6.124","58859",2023-02-26 02:25:34 GMT,0,con61850005,cmd19,seg-1,,dx1688099,,sx1,"LOG","00000","
Unexpected internal error: Master 28006 received signal 11 in worker thread 140462736271104 (forwarding signal to main thread)

",,,,,,,0,,,,
2023-02-26 02:46:02.806002 GMT,"client","merit",p28006,th125822720,"10.3.6.124","58859",2023-02-26 02:25:34 GMT,0,con61850005,cmd19,seg-1,,dx1688099,,sx1,"LOG","00000","
Unexpected internal error: Master 28006 received signal 11 in worker thread 140462736271104 (forwarding signal to main thread)

",,,,,,,0,,,,
2023-02-26 02:46:02.806032 GMT,"client","merit",p28006,th134215424,"10.3.6.124","58859",2023-02-26 02:25:34 GMT,0,con61850005,cmd19,seg-1,,dx1688099,,sx1,"ERROR","57014","canceling statement due to user request",,,,,,,0,,"postgres.c",3729,
```

**Comment by Aegeaner** [comment]
> @Aegeaner what's the next step for this issue? If we don't have RCA or artifacts to RCA then lets close it.

Sure.
