### ISSUE TITLE
gpfdist crashed by passing null session->requests

### ISSUE THREAD

**Issue by hslightdb** [greenplum-db/gpdb#15202]
## Bug Report
(gdb) where
#0  0x00007f07221fb324 in find_entry () from /lib64/libapr-1.so.0
#1  0x00007f07221fb70f in apr_hash_set () from /lib64/libapr-1.so.0
#2  0x0000000000406d7e in session_attach (r=0x23d5100) at gpfdist.c:1784
#3  0x00000000004079af in do_read_request (fd=8, event=2, arg=0x23d5100) at gpfdist.c:2149
#4  0x00007f072242aa14 in event_base_loop () from /lib64/libevent-2.0.so.5
#5  0x000000000040ba43 in gpfdist_run () at gpfdist.c:3889
#6  0x000000000040ba83 in main (argc=9, argv=0x7ffe99c6f488) at gpfdist.c:3898
(gdb) f 2
#2  0x0000000000406d7e in session_attach (r=0x23d5100) at gpfdist.c:1784
1784		apr_hash_set(`session->requests`, &r->id, sizeof(r->id), r);
(gdb) p session
$1 = (session_t *) 0x23f6160
(gdb) p *session
$2 = {id = 1, pool = 0x23f60e8, 
  key = 0x23f62e0 "316397.c.0.1:/home/fj/gpsources/gpMgmt/bin/gpload_test/gpload/data/lineitem.tbl.small", 
  tid = 0x23f6280 "316397.c.0.1", path = 0x23f6290 "/home/fj/gpsources/gpMgmt/bin/gpload_test/gpload/data/lineitem.tbl.small", 
  fstream = 0x23d4d60, is_error = 0, nrequest = 1, is_get = 1, active_segids = 0x23f6258, seq_segs = 0x23f6268, maxsegs = 3, 
  mtime = 1678934630028928, tm = {tv_sec = 0, tv_usec = 0}, ev = {ev_evcallback = {evcb_active_next = {tqe_next = 0x0, 
        tqe_prev = 0x0}, evcb_flags = 0, evcb_pri = 0 '\000', evcb_closure = 0 '\000', evcb_cb_union = {evcb_callback = 0x0, 
        evcb_selfcb = 0x0, evcb_evfinalize = 0x0, evcb_cbfinalize = 0x0}, evcb_arg = 0xffffffff}, ev_timeout_pos = {
      ev_next_with_common_timeout = {tqe_next = 0x0, tqe_prev = 0x0}, min_heap_idx = 0}, ev_fd = 37569184, ev_base = 0x0, ev_ = {
      ev_io = {ev_io_next = {le_next = 0x0, le_prev = 0x0}, ev_timeout = {tv_sec = 0, tv_usec = 1407924639367168}}, ev_signal = {
        ev_signal_next = {le_next = 0x0, le_prev = 0x0}, ev_ncalls = 0, ev_pncalls = 0x5008000000000}}, ev_events = 0, ev_res = 0, 
    ev_timeout = {tv_sec = 0, tv_usec = 0}}, `requests = 0x0`}

**Comment by Hlinbit** [comment]
What's more, can you give me a core dump file of when the crash came?

**Comment by ashwinstar** [comment]
No further into shared to help RCA closing.
