### ISSUE TITLE
crash with MERGE JOIN in subquery

### ISSUE THREAD

**Issue by hli1992** [greenplum-db/gpdb#1536]
```
postgres=# CREATE TABLE txx (f1 int) DISTRIBUTED RANDOMLY;
CREATE TABLE
postgres=# 
postgres=# insert into txx values(123456), (-2147483647), (0), (-123456), (2147483647);
INSERT 0 5
postgres=# set enable_hashjoin to off;
SET
postgres=# set enable_nestloop to off;
SET
postgres=# set enable_mergejoin to on;
SET
postgres=# explain select * from txx a join txx b on (a.f1 = (select f1 from txx c where c.f1=b.f1));
FATAL:  Unexpected internal error (nodeMotion.c:943)
DETAIL:  FailedAssertion("!(recvSlice->gangSize == 1)", File: "nodeMotion.c", Line: 943)
HINT:  Process 31304 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
postgres=# 
```

**error stack:**

```
(gdb) bt
#0  0x00007f0cbe3e0da3 in select () at ../sysdeps/unix/syscall-template.S:81
#1  0x0000000000ba83d8 in pg_usleep (microsec=5000000) at pgsleep.c:43
#2  0x0000000000a2c3ed in elog_debug_linger (edata=0x1173c80 <errordata>) at elog.c:4345
#3  0x0000000000a23b2a in errfinish (dummy=0) at elog.c:616
#4  0x0000000000a2230d in ExceptionalCondition (conditionName=0xd0295f "!(recvSlice->gangSize == 1)", errorType=0xd021a5 "FailedAssertion", fileName=0xd022f9 "nodeMotion.c", 
    lineNumber=943) at assert.c:48
#5  0x0000000000741008 in ExecInitMotion (node=0x2e94438, estate=0x2e98300, eflags=1) at nodeMotion.c:943
#6  0x00000000006ff004 in ExecInitNode (node=0x2e94438, estate=0x2e98300, eflags=1) at execProcnode.c:677
#7  0x000000000072a57f in ExecInitMaterial (node=0x2e93b98, estate=0x2e98300, eflags=1) at nodeMaterial.c:350
#8  0x00000000006fe957 in ExecInitNode (node=0x2e93b98, estate=0x2e98300, eflags=3) at execProcnode.c:573
#9  0x000000000072f70a in ExecInitResult (node=0x2e93600, estate=0x2e98300, eflags=3) at nodeResult.c:414
#10 0x00000000006fd6e4 in ExecInitNode (node=0x2e93600, estate=0x2e98300, eflags=3) at execProcnode.c:279
#11 0x00000000006f6078 in InitPlan (queryDesc=0x2e95dc8, eflags=1) at execMain.c:1847
#12 0x00000000006f3a2c in ExecutorStart (queryDesc=0x2e95dc8, eflags=1) at execMain.c:542
#13 0x0000000000668715 in ExplainOnePlan (plannedstmt=0x2e95b18, params=0x0, stmt=0x2d85a38, 
    queryString=0x2d838e0 "explain select * from txx a join txx b on (a.f1 = (select f1 from txx c where c.f1=b.f1));", tstate=0x2e79248) at explain.c:454
#14 0x00000000006683ca in ExplainOneQuery (query=0x2e762b8, stmt=0x2d85a38, 
    queryString=0x2d838e0 "explain select * from txx a join txx b on (a.f1 = (select f1 from txx c where c.f1=b.f1));", params=0x0, tstate=0x2e79248) at explain.c:294
#15 0x000000000066827e in ExplainQuery (stmt=0x2d85a38, queryString=0x2d838e0 "explain select * from txx a join txx b on (a.f1 = (select f1 from txx c where c.f1=b.f1));", 
    params=0x0, dest=0x2e181f0) at explain.c:170
#16 0x00000000008f80fa in ProcessUtility (parsetree=0x2d85a38, 
    queryString=0x2d838e0 "explain select * from txx a join txx b on (a.f1 = (select f1 from txx c where c.f1=b.f1));", params=0x0, isTopLevel=1 '\001', dest=0x2e181f0, 
    completionTag=0x7fff7926b060 "") at utility.c:1559
#17 0x00000000008f4a54 in PortalRunUtility (portal=0x2d88100, utilityStmt=0x2d85a38, isTopLevel=1 '\001', dest=0x2e181f0, completionTag=0x7fff7926b060 "") at pquery.c:1393
#18 0x00000000008f476b in FillPortalStore (portal=0x2d88100, isTopLevel=1 '\001') at pquery.c:1266
#19 0x00000000008f4078 in PortalRun (portal=0x2d88100, count=9223372036854775807, isTopLevel=1 '\001', dest=0x2d841c8, altdest=0x2d841c8, completionTag=0x7fff7926b2e0 "")
    at pquery.c:1007
#20 0x00000000008ec28a in exec_simple_query (query_string=0x2d838e0 "explain select * from txx a join txx b on (a.f1 = (select f1 from txx c where c.f1=b.f1));", 
    seqServerHost=0x0, seqServerPort=-1) at postgres.c:1808
#21 0x00000000008f0f39 in PostgresMain (argc=1, argv=0x2c88da0, dbname=0x2c88d58 "postgres", username=0x2c88d18 "hli") at postgres.c:4965
#22 0x0000000000882a2d in BackendRun (port=0x2c90e70) at postmaster.c:6667
#23 0x00000000008820a1 in BackendStartup (port=0x2c90e70) at postmaster.c:6353
#24 0x000000000087ab14 in ServerLoop () at postmaster.c:2437
#25 0x000000000087927e in PostmasterMain (argc=15, argv=0x2c66060) at postmaster.c:1523
#26 0x0000000000794f58 in main (argc=15, argv=0x2c66060) at main.c:206
(gdb) 
```

**Comment by vraghavan78** [comment]
On the latest master the query seems to work:

```
vraghavan=# CREATE TABLE txx (f1 int) DISTRIBUTED RANDOMLY;
CREATE TABLE
vraghavan=# insert into txx values(123456), (-2147483647), (0), (-123456), (2147483647);
INSERT 0 5
vraghavan=# set enable_hashjoin to off;
SET
vraghavan=# set enable_nestloop to off;
SET
vraghavan=# set enable_mergejoin to on;
SET
vraghavan=# explain select * from txx a join txx b on (a.f1 = (select f1 from txx c where c.f1=b.f1));
                                                    QUERY PLAN
------------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice3; segments: 3)  (cost=4.65..46.15 rows=5 width=8)
   ->  Merge Join  (cost=4.65..46.15 rows=2 width=8)
         Merge Cond: a.f1 = ((subplan))
         ->  Sort  (cost=2.11..2.12 rows=2 width=4)
               Sort Key: a.f1
               ->  Seq Scan on txx a  (cost=0.00..2.05 rows=2 width=4)
         ->  Sort  (cost=2.54..2.58 rows=5 width=4)
               Sort Key: ((subplan))
               ->  Result  (cost=0.00..2.25 rows=5 width=4)
                     ->  Broadcast Motion 3:3  (slice2; segments: 3)  (cost=0.00..2.25 rows=5 width=4)
                           ->  Seq Scan on txx b  (cost=0.00..2.05 rows=2 width=4)
                     SubPlan 1
                       ->  Result  (cost=2.06..2.07 rows=1 width=4)
                             Filter: c.f1 = $0
                             ->  Materialize  (cost=2.06..2.07 rows=1 width=4)
                                   ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..2.06 rows=1 width=4)
                                         ->  Seq Scan on txx c  (cost=0.00..2.06 rows=1 width=4)
 Settings:  enable_hashjoin=off; enable_mergejoin=on; enable_nestloop=off
 Optimizer status: legacy query optimizer
(19 rows)

vraghavan=# select * from txx a join txx b on (a.f1 = (select f1 from txx c where c.f1=b.f1));
     f1      |     f1
-------------+-------------
 -2147483647 | -2147483647
           0 |           0
(2 rows)
```

@hli1992 can you please check on your side.

**Comment by hlinnaka** [comment]
This is no longer reproducable on 'master'. Not sure if it's been fixed, or there are some other changes that hide the issue.

**Comment by paul-guo-** [comment]
I tried on both master and merge branch (master + pg 9.4.19), no assert failure now for this case. We could close this one if nobody objects.

**Comment by BaiShaoqi** [comment]
Closing per @paul-guo-
