### ISSUE TITLE
gpcheckperf fails with verbose (-V) flag when running netperf test in full-matrix mode

### ISSUE THREAD

**Issue by grandsuri** [greenplum-db/gpdb#15388]
## Bug Report
Running the gpcheckperf with Verbose flag for running netperf test in full matrix fails with an error "Too many values to unpack"

### Greenplum version or build
 6.23.4

### OS version and uname -a
CentOS Linux release 7.7.1908 (Core)
Linux <machine name>5.1.0 #4 SMP Fri May 24 19:19:46 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

### Installation information ( pg_config )
bash-4.2$ pg_config
BINDIR = /usr/local/greenplum-db-6.23.4/bin
DOCDIR = /usr/local/greenplum-db-6.23.4/share/doc/postgresql
HTMLDIR = /usr/local/greenplum-db-6.23.4/share/doc/postgresql
INCLUDEDIR = /usr/local/greenplum-db-6.23.4/include
PKGINCLUDEDIR = /usr/local/greenplum-db-6.23.4/include/postgresql
INCLUDEDIR-SERVER = /usr/local/greenplum-db-6.23.4/include/postgresql/server
LIBDIR = /usr/local/greenplum-db-6.23.4/lib
PKGLIBDIR = /usr/local/greenplum-db-6.23.4/lib/postgresql
LOCALEDIR = /usr/local/greenplum-db-6.23.4/share/locale
MANDIR = /usr/local/greenplum-db-6.23.4/man
SHAREDIR = /usr/local/greenplum-db-6.23.4/share/postgresql
SYSCONFDIR = /usr/local/greenplum-db-6.23.4/etc/postgresql
PGXS = /usr/local/greenplum-db-6.23.4/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--disable-debug-extensions' '--disable-tap-tests' '--enable-orca' '--with-zstd' '--with-gssapi' '--with-libxml' '--with-perl' '--with-python' '--with-openssl' '--with-pam' '--with-ldap' '--with-pythonsrc-ext' '--with-uuid=e2fs' '--with-extra-version= Open Source' '--prefix=/usr/local/greenplum-db-6.23.4' '--mandir=/usr/local/greenplum-db-6.23.4/man' 'CC=gcc' 'CFLAGS=-O3 -fargument-noalias-global -fno-omit-frame-pointer -g'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/greenplum-db-6.23.4/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/greenplum-db-6.23.4/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/greenplum-db-6.23.4/lib',--enable-new-dtags -L/usr/local/greenplum-db-6.23.4/lib
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lxerces-c -lxml2 -lpam -lrt -lgssapi_krb5 -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/greenplum-db-6.23.4/lib
VERSION = PostgreSQL 9.4.26

### Expected behavior
gpcheckperf should succeed irrespective of Verbose flag and display the results of netperf test in full matrix mode.

### Actual behavior
bash-4.2$ gpcheckperf -V -S <size> -h <hostname1_ip1> -h <hostname1_ip2> -d /mnt/primary/gpseg0 -d /mnt/primary/gpseg1 -rM

Traceback (most recent call last):
  File "/usr/local/greenplum-db-6.23.4/bin/gpcheckperf", line 944, in <module>
    netResult, seglist = runNetPerfTestMatrix()
  File "/usr/local/greenplum-db-6.23.4/bin/gpcheckperf", line 779, in runNetPerfTestMatrix
    seglist, uniqhosts = get_host_map(hostlist)
  File "/usr/local/greenplum-db-6.23.4/bin/gpcheckperf", line 741, in get_host_map
    seg, host = line.translate(None, '[]').split()
ValueError: too many values to unpack

Adding "-V" flag prints additional debug information like 
**'Using delaybeforesend 0.05 and prompt_validation_timeout 1.0\n\n[Reset ...]\n[INFO] login m29-tcp-1\n[m29-tcp-1] m29\r\n[INFO] completed successfully\n\n[Cleanup...]\n'**
causing the get_host_map fail in parsing the output

### Step to reproduce the behavior
1. Run the gpcheckperf command with  or without -V flag and -rM for full-matrix mode
2. See the output to make sure the results are reported properly

**Comment by grandsuri** [comment]
Just checked the latest code and seems it is fixed. Closing this
