### ISSUE TITLE
SQLancer: SIGSEGV in ApplyCorrelatedStatsToScaleFactorFilterCalculation

### ISSUE THREAD

**Issue by bmdoil** [greenplum-db/gpdb#15462]
## Bug Report
Attempt to dereference null pointer in `ApplyCorrelatedStatsToScaleFactorFilterCalculation`
```
#5  gpnaucrates::CExtendedStatsProcessor::ApplyCorrelatedStatsToScaleFactorFilterCalculation (scale_factors=0x55b46af98358, conjunctive_pred_stats=<optimized out>, md_statsinfo=<optimized out>, colid_to_attno_mapping=0x55b46af8c828, mp=0x55b469a477f0, result_histograms=0x55b46b3c86c8) at CExtendedStatsProcessor.cpp:364
364				if (dependency_implies_attribute(dependency, *attnum))
(gdb) l
359				 * the list for this attnum. If the attnum happens to be compared
360				 * to a different Const in another clause then no rows will match
361				 * anyway. If it happens to be compared to the same Const, then
362				 * ignoring the additional clause is just the thing to do.
363				 */
364				if (dependency_implies_attribute(dependency, *attnum))
365				{
366					s2 = 1 / result_histograms->Find(&colid)->GetFrequency().Get();
367	
368					/* mark this one as done, so we don't touch it again. */
(gdb) p attnum
$3 = (gpos::INT *) 0x0
```
### Greenplum version or build
```
postgres=# select version();
                                                                                                            version                                                                                                            
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12.12 (Greenplum Database 7.0.0-beta.2+dev.205.g363887e4d6a build dev) on x86_64-pc-linux-gnu, compiled by Ubuntu clang version 15.0.6, 64-bit compiled on May  3 2023 13:02:29 (with assert checking) Bhuvnesh C.
(1 row)
```

### OS version and uname -a
```
Ubuntu 22.04 LTS
Linux bdoil-ub 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
### Installation information ( pg_config )
```
BINDIR = /usr/local/gpdb7/bin
DOCDIR = /usr/local/gpdb7/share/doc/postgresql
HTMLDIR = /usr/local/gpdb7/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb7/include
PKGINCLUDEDIR = /usr/local/gpdb7/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb7/include/postgresql/server
LIBDIR = /usr/local/gpdb7/lib
PKGLIBDIR = /usr/local/gpdb7/lib/postgresql
LOCALEDIR = /usr/local/gpdb7/share/locale
MANDIR = /usr/local/gpdb7/share/man
SHAREDIR = /usr/local/gpdb7/share/postgresql
SYSCONFDIR = /usr/local/gpdb7/etc/postgresql
PGXS = /usr/local/gpdb7/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--prefix=/usr/local/gpdb7' '--with-libxml' '--enable-cassert' '--with-python' '--enable-dtrace' '--enable-debug' '--enable-depend' '--enable-tap-tests' '--disable-gpcloud' 'CC=/usr/bin/clang' 'CFLAGS=-O0 -g -fno-omit-frame-pointer'
CC = /usr/bin/clang
CPPFLAGS = -D_GNU_SOURCE -I/usr/local/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-but-set-variable -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -g -O0 -g -fno-omit-frame-pointer  -Werror=uninitialized -Werror=implicit-function-declaration
CFLAGS_SL = -fPIC
LDFLAGS = -L/usr/local/lib -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb7/lib',--enable-new-dtags
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lxerces-c -lbz2 -lxml2 -lrt -lz -lreadline -lcrypt -lm  -lcurl -lzstd
VERSION = PostgreSQL 12.12
```
### Expected behavior
No crash, planner explain analyze output:
```
                                                            QUERY PLAN                                                            
----------------------------------------------------------------------------------------------------------------------------------
 Merge Full Join  (cost=10000000000.00..10000000002.34 rows=10 width=9) (actual time=0.484..0.490 rows=10 loops=1)
   ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..1.17 rows=10 width=9) (actual time=0.162..0.164 rows=10 loops=1)
         ->  Seq Scan on t1  (cost=0.00..1.03 rows=3 width=9) (actual time=0.010..0.014 rows=10 loops=1)
   ->  Materialize  (cost=0.00..1.06 rows=1 width=0) (actual time=0.319..0.319 rows=0 loops=1)
         ->  Gather Motion 3:1  (slice2; segments: 3)  (cost=0.00..1.05 rows=1 width=0) (actual time=0.316..0.316 rows=0 loops=1)
               ->  Seq Scan on t1 t1_1  (cost=0.00..1.03 rows=1 width=0) (actual time=0.000..0.014 rows=0 loops=1)
                     Filter: c2
 Optimizer: Postgres query optimizer
 Planning Time: 1.138 ms
   (slice0)    Executor memory: 40K bytes.  Work_mem: 17K bytes max.
   (slice1)    Executor memory: 36K bytes avg x 3 workers, 36K bytes max (seg0).
   (slice2)    Executor memory: 37K bytes avg x 3 workers, 37K bytes max (seg0).
 Memory used:  128000kB
 Execution Time: 3.401 ms
(14 rows)
```

### Actual behavior
Crash with following stack trace
```
(gdb) bt
#0  0x00007fca98c96a7c in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fca98c42476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00005596a009ea99 in StandardHandlerForSigillSigsegvSigbus_OnMainThread (processName=0x5596a0873624 "Coordinator process", postgres_signal_arg=11) at elog.c:5106
#3  0x000055969fead309 in CdbProgramErrorHandler (postgres_signal_arg=11) at postgres.c:3631
#4  <signal handler called>
#5  gpnaucrates::CExtendedStatsProcessor::ApplyCorrelatedStatsToScaleFactorFilterCalculation (scale_factors=0x5596a706d9f8, conjunctive_pred_stats=<optimized out>, md_statsinfo=<optimized out>, colid_to_attno_mapping=0x5596a7061ec8, mp=0x5596a6e82610, result_histograms=0x5596a893b4d8) at CExtendedStatsProcessor.cpp:364
#6  0x00005596a032f80e in gpnaucrates::CFilterStatsProcessor::MakeHistHashMapConjFilter (mp=0x5596a6e82610, stats_config=0x5596a86b3bf0, input_histograms=0x5596a8941460, input_rows=..., conjunctive_pred_stats=0x5596a8511bf0, scale_factor=0x7fff0b5b9260, input_stats=0x5596a8916c30)
    at ../../../../../../src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatistics.h:334
#7  0x00005596a033108d in gpnaucrates::CFilterStatsProcessor::MakeStatsFilter (mp=0x5596a6e82610, input_stats=0x5596a8916c30, base_pred_stats=0x5596a8511bf0, do_cap_NDVs=<optimized out>) at CFilterStatsProcessor.cpp:233
#8  0x00005596a0331476 in gpnaucrates::CFilterStatsProcessor::MakeStatsFilterForScalarExpr (mp=mp@entry=0x5596a6e82610, exprhdl=..., child_stats=child_stats@entry=0x5596a8916c30, local_scalar_expr=<optimized out>, outer_refs_scalar_expr=0x5596a8925cf0, all_outer_stats=0x5596a8505988) at CFilterStatsProcessor.cpp:53
#9  0x00005596a048a2c8 in gpopt::CLogicalSelect::PstatsDerive (this=<optimized out>, mp=0x5596a6e82610, exprhdl=..., stats_ctxt=<optimized out>) at CLogicalSelect.cpp:173
#10 0x00005596a0446195 in gpopt::CExpressionHandle::DeriveRootStats (this=this@entry=0x7fff0b5b9420, stats_ctxt=stats_ctxt@entry=0x5596a8505988) at CExpressionHandle.cpp:400
#11 0x00005596a044ce28 in gpopt::CExpressionHandle::DeriveStats (this=0x7fff0b5b9420, stats_ctxt=0x5596a8505988, fComputeRootStats=<optimized out>) at CExpressionHandle.cpp:474
#12 0x00005596a0438320 in gpopt::CExpression::PstatsDerive (this=this@entry=0x5596a7060690, prprel=<optimized out>, stats_ctxt=stats_ctxt@entry=0x5596a8505988) at CExpression.cpp:598
#13 0x00005596a044c9cd in gpopt::CExpressionHandle::DeriveStats (this=0x7fff0b5b9530, stats_ctxt=0x5596a8512aa0, fComputeRootStats=<optimized out>) at CExpressionHandle.cpp:444
#14 0x00005596a0438320 in gpopt::CExpression::PstatsDerive (this=this@entry=0x5596a70621d8, prprel=prprel@entry=0x5596a8512a30, stats_ctxt=stats_ctxt@entry=0x0) at CExpression.cpp:598
#15 0x00005596a038024e in gpopt::CCTEInfo::DeriveProducerStats (this=<optimized out>, popConsumer=<optimized out>, pcrsStat=0x5596a893b588) at CCTEInfo.cpp:332
#16 0x00005596a0448b44 in gpopt::CExpressionHandle::ComputeChildReqdProps (ulOptReq=0, pdrgpdpCtxt=0x0, child_index=1, this=0x7fff0b5b96b0) at CExpressionHandle.cpp:761
```
### Step to reproduce the behavior
SQLancer script
```
CREATE TABLE t0(c0 name  NOT NULL DEFAULT (((((CAST(0.66676387577865714462177493260242044925689697265625 AS VARCHAR(676)) COLLATE "C"))||(0.194692790497615675349152297712862491607666015625)) COLLATE "C")), c1 money  NULL, c2 boolean ); -- 35ms;
CREATE TABLE IF NOT EXISTS t1(LIKE t0); -- 11ms;
CREATE STATISTICS  IF NOT EXISTS s0 (mcv) ON c2, c0 FROM t1; -- 3ms;
INSERT INTO t1(c0) VALUES('tC'), (((lower(('' COLLATE "C")))||('167.36.214.241'))); -- 3ms;
VACUUM VERBOSE ANALYZE t1; -- 35ms;
SELECT t1.c1, t1.c2 FROM t1* FULL OUTER JOIN (SELECT ALL 0.12591235, '84.5.144.200', ((t1.c0)=(t1.c0)) FROM t1* WHERE t1.c2) AS sub0 ON CAST(- (((CAST(0.06916979906540821065874524720129556953907012939453125 AS INT))-(+ (468930185)))) AS BOOLEAN);
```

**Comment by dgkimura** [comment]
Awesome find!

Slightly smaller repro to reduce moving parts:
```sql
CREATE TABLE t1(c0 name, c2 boolean);
CREATE STATISTICS IF NOT EXISTS s0 (mcv) ON c2, c0 FROM t1;
INSERT INTO t1 VALUES('tC', true);
VACUUM VERBOSE ANALYZE t1;
SELECT 1 FROM t1 t11 FULL JOIN t1 t12 ON t12.c2;
```
Ultimately, I think the crux of the issue is that ORCA doesn't support FULL JOIN. Instead it fails to generate a plan and falls back to PLANNER. However, the extended statistics code path runs before the fallback and assumes that reasonable column ids were set up. That doesn't seem to be the case.

I suspect that implementing FULL JOIN may correct this issue.  However, that's a large scoped change.  So, I think it's also reasonable to add the null check before the SIGSEGV. In that case, if the colid to attnum mapping is messed up, then we should not try to use correlated stats.

**Comment by nimish350** [comment]
Crash reproducible on latest Main:
```
F6_BDC=# SELECT t1.c1, t1.c2 FROM t1* FULL OUTER JOIN (SELECT ALL 0.12591235, '84.5.144.200', ((t1.c0)=(t1.c0)) FROM t1* WHERE t1.c2) AS sub0 ON CAST(- (((CAST(0.06916979906540821065874524720129556953907012939453125 AS INT))-(+ (468930185)))) AS BOOLEAN);
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!?> 
!?> \q
```
