### ISSUE TITLE
The execution plans of `field1=value1` and `value1=field1` are different.

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpdb#15624]
## Bug Report

The execution plans of field1=value1 and value1=field1 are different

### Greenplum version or build

6.23.0

### Actual behavior

```sql
CREATE TABLE inframinio.archive_zip_info
(
    s3site_id smallint NOT NULL,
    path text COLLATE pg_catalog."default" NOT NULL,
    archiveds3site_id smallint,
    archivedpath character varying(256) COLLATE pg_catalog."default",
    path_hash character varying(10) COLLATE pg_catalog."default" NOT NULL,
    cdt bigint NOT NULL,
    deleted boolean
)
WITH (
    OIDS = FALSE,
    APPENDONLY = TRUE,
    COMPRESSLEVEL = 5,
    COMPRESSTYPE = ZLIB
)
TABLESPACE tbs_ssd01
DISTRIBUTED BY (path)
PARTITION BY LIST(s3site_id) 
          (
          PARTITION pics VALUES(11) WITH (appendonly='true', compresstype=zlib, compresslevel='5')  TABLESPACE tbs_ssd01, 
          PARTITION testlog VALUES(17) WITH (appendonly='true', compresstype=zlib, compresslevel='5')  TABLESPACE tbs_ssd01, 
          DEFAULT PARTITION other  WITH (appendonly='true', compresstype=zlib, compresslevel='5')  TABLESPACE tbs_ssd01
          ); ;

CREATE INDEX idx_inframinio_archive_zip_info_path_hash
    ON inframinio.archive_zip_info USING btree
    (path_hash ASC NULLS LAST)
    TABLESPACE tbs_ssd01;

select archivedpath ,archiveds3site_id from inframinio.archive_zip_info where 
 path_hash = substring(MD5('DIMM/P19/LF3067701A09-B@/2020-7/23/P19/GW07NP3789_DOWN_202007DD1823469054.png'),1,8)  order by cdt desc limit 1

"Result  (cost=0.00..393.45 rows=1 width=50)"
"  ->  Limit  (cost=0.00..393.45 rows=1 width=50)"
"        ->  Gather Motion 20:1  (slice1; segments: 20)  (cost=0.00..393.45 rows=1 width=58)"
"              Merge Key: cdt"
"              ->  Limit  (cost=0.00..393.45 rows=1 width=58)"
"                    ->  Result  (cost=0.00..393.45 rows=501 width=58)"
"                          ->  Sort  (cost=0.00..393.45 rows=501 width=58)"
"                                Sort Key: cdt"
"                                ->  Sequence  (cost=0.00..391.89 rows=501 width=67)"
"                                      ->  Partition Selector for archive_zip_info (dynamic scan id: 1)  (cost=10.00..100.00 rows=5 width=4)"
"                                            Partitions selected: 3 (out of 3)"
"                                      ->  Dynamic Bitmap Heap Scan on archive_zip_info (dynamic scan id: 1)  (cost=0.00..391.89 rows=501 width=67)"
"                                            Recheck Cond: ((path_hash)::text = '233ac9f9'::text)"
"                                            ->  Dynamic Bitmap Index Scan on idx_inframinio_archive_zip_info_path_hash  (cost=0.00..0.00 rows=0 width=0)"
"                                                  Index Cond: ((path_hash)::text = '233ac9f9'::text)"
"Optimizer: Pivotal Optimizer (GPORCA)"

select archivedpath ,archiveds3site_id from inframinio.archive_zip_info where 
 substring(MD5('DIMM/P19/LF3067701A09-B@/2020-7/23/P19/GW07NP3789_DOWN_202007DD1823469054.png'),1,8) = path_hash order by cdt desc limit 1

"Result  (cost=0.00..1193757.69 rows=1 width=50)"
"  ->  Limit  (cost=0.00..1193757.69 rows=1 width=50)"
"        ->  Gather Motion 20:1  (slice1; segments: 20)  (cost=0.00..1193757.69 rows=1 width=58)"
"              Merge Key: cdt"
"              ->  Limit  (cost=0.00..1193757.69 rows=1 width=58)"
"                    ->  Result  (cost=0.00..1193757.69 rows=127974257 width=58)"
"                          ->  Sort  (cost=0.00..1193757.69 rows=127974257 width=58)"
"                                Sort Key: cdt"
"                                ->  Sequence  (cost=0.00..60338.31 rows=127974257 width=67)"
"                                      ->  Partition Selector for archive_zip_info (dynamic scan id: 1)  (cost=10.00..100.00 rows=5 width=4)"
"                                            Partitions selected: 3 (out of 3)"
"                                      ->  Dynamic Seq Scan on archive_zip_info (dynamic scan id: 1)  (cost=0.00..60338.31 rows=127974257 width=67)"
"                                            Filter: ('233ac9f9'::text = (path_hash)::text)"
"Optimizer: Pivotal Optimizer (GPORCA)"
```

**Comment by chrishajas** [comment]
Thanks for the report. Can you provide the minirepro, as it needs stats to reproduce: https://community.pivotal.io/s/article/How-to-Collect-DDL-and-Statistics-Information-Using-the-Minirepro-Utility?language=en_US

**Comment by cobolbaby** [comment]
- demo1.sql

```sql
select archivedpath ,archiveds3site_id from inframinio.archive_zip_info where 
 path_hash = substring(MD5('DIMM/P19/LF3067701A09-B@/2020-7/23/P19/GW07NP3789_DOWN_202007DD1823469054.png'),1,8)  order by cdt desc limit 1;

select archivedpath ,archiveds3site_id from inframinio.archive_zip_info where 
 substring(MD5('DIMM/P19/LF3067701A09-B@/2020-7/23/P19/GW07NP3789_DOWN_202007DD1823469054.png'),1,8) = path_hash order by cdt desc limit 1;
```
- minirepro

```bash
[gpadmin@gp6mdw tmp]$ minirepro F6_BDC -q demo1.sql -f minirepro.log -l
Traceback (most recent call last):
  File "/usr/local/greenplum-db-6.23.0/bin/minirepro", line 459, in <module>
    main()
  File "/usr/local/greenplum-db-6.23.0/bin/minirepro", line 334, in main
    user = options.user or ('PGUSER' in envOpts and envOpts['PGUSER']) or os.getlogin()
OSError: [Errno 6] No such device or address
[gpadmin@gp6mdw tmp]$ minirepro F6_BDC -U gpadmin -q demo1.sql -f /tmp/minirepro.log -l
Connecting to database: host=gp6mdw, port=5432, user=gpadmin, db=F6_BDC ...
Extracting metadata from query file demo1.sql ...
psql F6_BDC --pset footer --no-psqlrc -Atq -h gp6mdw -p 5432 -U gpadmin -f /tmp/20230529105336/toolkit.sql
Invoking pg_dump to dump DDL ...
pg_dump -h gp6mdw -p 5432 -U gpadmin -sxO F6_BDC --relation-oids 157277938,157277948,157277961,157277973 --function-oids 0 -f /tmp/20230529105336/pg_dump_out.sql
Writing schema DDLs ...
Writing relation and function DDLs ...
Writing table statistics ...
Writing column statistics ...
Attaching raw query text ...
--- MiniRepro completed! ---
WARNING: This tool collects statistics about your data, including most common values, which requires some data elements to be included in the output file.
Please review output file to ensure it is within corporate policy to transport the output file.
```
- minirepro.log

[minirepro.log](https://github.com/greenplum-db/gpdb/files/11587839/minirepro.log)

**Comment by kainwen** [comment]
Fixed by:
* main branch https://github.com/greenplum-db/gpdb/pull/15880
* 6X: https://github.com/greenplum-db/gpdb/pull/15944
