### ISSUE TITLE
pg_ctl stop -m fast on master fails with infinite lock

### ISSUE THREAD

**Issue by Smyatkin-Maxim** [greenplum-db/gpdb#16081]
## Bug Report
In some failover/switchover tests with send pg_ctl stop -m fast to coordinator. Occasionally we get into a problem which appears to be a deadlock. The stacktrace looks like this:
```
Wed Jul 26 17:07:46 2023
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
__lll_lock_wait_private () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:95
#0  __lll_lock_wait_private () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:95
#1  0x00007fd481c905d5 in __check_pf (seen_ipv4=0x7ffec2731ed2, seen_ipv6=0x7ffec2731ed3, in6ai=0x7ffec2731ee0, in6ailen=0x7fd481c7f50c <__lll_lock_wait_private+28>) at ../sysdeps/unix/sysv/linux/check_pf.c:307
#2  0x00007fd481c56d55 in __libc_use_alloca (size=140732160746416) at ../sysdeps/pthread/allocalim.h:27
#3  __GI_getaddrinfo (name=<optimized out>, service=<optimized out>, service@entry=0x7ffec27323e0 "45946", hints=<optimized out>, pai=0x7ffec27323a8) at ../sysdeps/posix/getaddrinfo.c:2338
#4  0x000056187486e63e in pg_getaddrinfo_all (hostname=<optimized out>, servname=servname@entry=0x7ffec27323e0 "45946", hintp=hintp@entry=0x7ffec27323b0, result=result@entry=0x7ffec27323a8) at ip.c:78
#5  0x0000561874b2d0cf in SendDummyPacket () at ic_udpifc.c:6899
#6  WaitInterconnectQuitUDPIFC () at ic_udpifc.c:6860
#7  0x0000561874b1d716 in WaitInterconnectQuit () at ic_common.c:746
#8  0x0000561874976af0 in proc_exit_prepare (code=code@entry=1) at ipc.c:209
#9  0x0000561874976bf1 in proc_exit (code=code@entry=1) at ipc.c:104
#10 0x0000561874ab55aa in errfinish (dummy=<optimized out>) at elog.c:749
#11 0x0000561874924c38 in bgworker_die (postgres_signal_arg=<optimized out>) at bgworker.c:562
#12 <signal handler called>
#13 0x00007fd481c71607 in bind () at ../sysdeps/unix/syscall-template.S:78
#14 0x00007fd481c9064c in __check_pf (seen_ipv4=seen_ipv4@entry=0x7ffec2733482, seen_ipv6=seen_ipv6@entry=0x7ffec2733483, in6ai=in6ai@entry=0x7ffec2733490, in6ailen=in6ailen@entry=0x7ffec2733498) at ../sysdeps/unix/sysv/linux/check_pf.c:326
#15 0x00007fd481c57531 in __GI_getaddrinfo (name=<optimized out>, service=<optimized out>, service@entry=0x7ffec27339e0 "7000", hints=<optimized out>, pai=0x7ffec2733968) at ../sysdeps/posix/getaddrinfo.c:2354
#16 0x000056187486e63e in pg_getaddrinfo_all (hostname=hostname@entry=0x561877028f78 "rc1a-prhl05eerdkl0443.mdb.cloud-preprod.yandex.net", servname=servname@entry=0x7ffec27339e0 "7000", hintp=hintp@entry=0x7ffec2733970, result=result@entry=0x7ffec2733968) at ip.c:78
#17 0x0000561874b791eb in getDnsCachedAddress (name=0x561877028f78 "rc1a-prhl05eerdkl0443.mdb.cloud-preprod.yandex.net", port=7000, elevel=elevel@entry=15, use_cache=use_cache@entry=1 '\001') at cdbutil.c:1260
#18 0x0000561874b79e03 in getAddressesForDBid (elevel=<optimized out>, c=0x56187701a398) at cdbutil.c:1405
#19 getCdbComponentInfo () at cdbutil.c:393
#20 0x0000561874b7a7d5 in cdbcomponent_getCdbComponents () at cdbutil.c:720
#21 0x000056187485cc85 in readCdbComponentInfoAndUpdateStatus (probeContext=0x561876fbcdd8) at fts.c:167
#22 FtsLoop () at fts.c:332
#23 FtsProbeMain (main_arg=<optimized out>) at fts.c:152
#24 0x00005618749255f6 in StartBackgroundWorker () at bgworker.c:753
#25 0x0000561874931fc3 in do_start_bgworker (rw=0x561876ef7e90) at postmaster.c:6142
#26 maybe_start_bgworker () at postmaster.c:6387
#27 0x000056187462efc9 in ServerLoop () at postmaster.c:2033
#28 0x0000561874934ce7 in PostmasterMain (argc=6, argv=0x561876e98210) at postmaster.c:1526
#29 0x0000561874631147 in main (argc=6, argv=0x561876e98210) at main.c:245
```

I guess here might be two problems:
1. memory allocations are not signal-safe, aren't they? https://stackoverflow.com/questions/40049751/malloc-inside-linux-signal-handler-cause-deadlock
2. getaddrinfo doesn't seem to be reliably in signal handler. Here are quite a few cases like this in quick google search: https://bugzilla.redhat.com/show_bug.cgi?id=1209433

### Greenplum version or build
6.22

### OS version and uname -a
Ubuntu 18.04
Linux **hostname** 5.4.210-39 #1 SMP Mon Aug 22 07:06:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior
Coordinator shuts down

### Actual behavior
Coordinator freezes

### Step to reproduce the behavior
Can't provide a predictable repro, but we see it quite often when testing our coordinator switchover/failover.

**Comment by kainwen** [comment]
Fixed by 
* https://github.com/greenplum-db/gpdb/pull/16353 (main branch)
* https://github.com/greenplum-db/gpdb/pull/16415 (6x branch)
