### ISSUE TITLE
APPENDONLY and ORIENTATION parameters absent in pg_class.reloptions

### ISSUE THREAD

**Issue by LonwoLonwo** [greenplum-db/gpdb#16093]
## Bug Report

I can not see any more special options APPENDONLY and ORIENTATION in the `pg_class.reloptions` system table starting Greenplum version 7.

![2023-07-28 14_08_43-Connection _postgres 5_ configuration](https://github.com/greenplum-db/gpdb/assets/45152336/beb08d01-fe43-436a-8bde-f7ab47ec0bb0)

![2023-07-28 14_09_34-Connection _dbeaver_db_ configuration](https://github.com/greenplum-db/gpdb/assets/45152336/976a4579-5db2-44fb-bcc6-7b2b0ef30480)

And we are using these options for table DDL generation in DBeaver for Greenplum tables.

Did they move somewhere? Or where can I find this info now?

### Greenplum version or build

PostgreSQL 12.12 (Greenplum Database 7.0.0-beta.4 build commit:f3782c6dd89c9b6565a84518174ed4dd448f3293) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit compiled on Jun 15 2023 00:59:29 Bhuvnesh C.

### Expected behavior

APPENDONLY and ORIENTATION (and maybe other options?) are in the `pg_class.reloptions` system table.

### Actual behavior

I see only {compresstype=zlib,compresslevel=9} in the `pg_class.reloptions` system table.

### Step to reproduce the behavior

```sql
CREATE TABLE RP_DATE
(
    RP_INT      INTEGER,
    RP_DATE DATE,
    RP_TIMESTAMP TIMESTAMP,
    RP_DIST_KEY INTEGER NOT NULL
)
WITH (
     APPENDONLY=TRUE
     ,COMPRESSTYPE=ZLIB
     ,COMPRESSLEVEL=9
     ,ORIENTATION=COLUMN
)
DISTRIBUTED BY (RP_DIST_KEY)
PARTITION BY RANGE(RP_DATE)
(
     START (DATE '2015-06-01') INCLUSIVE
     END (DATE '2016-01-01') EXCLUSIVE EVERY (INTERVAL '1 DAY')
);
```

**Comment by LonwoLonwo** [comment]
Also, please please tell me, what can I use instead of the `pg_get_partition_def(regclass, boolean, boolean)` function in the newest Greenplum version? How can I get all the table partition info? I do not see any helpful functions in pg_catalog.

```
org.postgresql.util.PSQLException: ERROR: function pg_get_partition_def(regclass, boolean, boolean) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:244)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeQuery(JDBCStatementImpl.java:346)
	at org.jkiss.dbeaver.ext.greenplum.model.GreenplumUtils.getPartitionData(GreenplumUtils.java:118)
	at org.jkiss.dbeaver.ext.greenplum.model.GreenplumUtils.addObjectModifiersToDDL(GreenplumUtils.java:150)
	at org.jkiss.dbeaver.ext.greenplum.model.GreenplumTable.appendTableModifiers(GreenplumTable.java:93)
	at org.jkiss.dbeaver.ext.postgresql.model.impls.PostgreServerExtensionBase.getTableModifiers(PostgreServerExtensionBase.java:324)
```

**Comment by SmartKeyerror** [comment]
You can use the following SQL to get the storage type of a table:

```
create table t_heap(a int);
create table t_ao(a int) with (appendonly=true);
create table t_aoco(a int) with (appendonly=true, orientation=column);

SELECT c.relname, am.amname, c.reloptions FROM pg_class c 
JOIN pg_am am on am.oid=c.relam WHERE c.relname like 't_%';
 relname |  amname   |                            reloptions                             
---------+-----------+-------------------------------------------------------------------
 t_heap  | heap      | 
 t_ao    | ao_row    | {blocksize=32768,compresslevel=0,compresstype=none,checksum=true}
 t_aoco  | ao_column | {blocksize=32768,compresslevel=0,compresstype=none,checksum=true}
(3 rows)
```

**Comment by LonwoLonwo** [comment]
Hello @SmartKeyerror 

Thanks for the idea.

But, for now, it is not a convenient way to get this option.

So I am still waiting for the answer.

**Comment by huansong** [comment]
Hi @LonwoLonwo , thanks for the report. The `APPENDONLY` and `ORIENTATION` internally will be translated to corresponding access methods now. The access method concept is the same as [PG](https://www.postgresql.org/docs/12/sql-createtable.html#:~:text=SET%20CONSTRAINTS%20command.-,USING%20method,-This%20optional%20clause). So basically these queries:
```sql
create table t_heap(a int);
create table t_ao(a int) with (appendonly=true);
create table t_aoco(a int) with (appendonly=true, orientation=column);
```
are internally equivalent to:
```sql
create table t_heap(a int) using heap;
create table t_ao(a int) using ao_row;
create table t_aoco(a int) using ao_column;
```

AO and AOCO tables are tables with ao_row and ao_column access methods, respectively. And if you think about it, they are not really "reloptions" per se: an AO table is not a heap table with "appendonly" option - they are totally different storage formats. So we can still specify `APPENDONLY` and `ORIENTATION` in the `WITH` clause for backward-compatibility but they are not stored in `reloptions` anymore. The best way to retrieve the information is like @SmartKeyerror said, check the access method names. It's also preferred that we generate equivalent DDLs with the `USING <access method>` clause to specify if it is an AO or AOCO table.

**Comment by LonwoLonwo** [comment]
Great!
Now it is more apparent. Thanks for the answer.

Could you please also give me the answer to my second question? https://github.com/greenplum-db/gpdb/issues/16093#issuecomment-1655515681

**Comment by huansong** [comment]
@LonwoLonwo There's no equivalent replacement to `pg_get_partition_def` unfortunately, **but** it's not the end of the world because:
* For the background, in GP7 there are two flavors of partition syntax: classic and modern. Classic is the one GP7 inherits from GP6 which is also what you used in your example. Modern is the one that GP7 merged from Postgres. See [blog](https://greenplum.org/partition-in-greenplum-7-whats-new/) and [documentation](https://docs.vmware.com/en/VMware-Greenplum/7/greenplum-database/admin_guide-ddl-ddl-partition.html#:~:text=the%20best%20strategy.-,Choosing%20the%20Partitioning%20Syntax,-Greenplum%20Database%207) for more details. 
* In general, the classic syntax is more specialized and the modern one is more generalized. As a result you can re-create a partitioned table that's originally created by classic syntax using the modern one, but **not necessarily vice versa**. See two examples:
  * The modern syntax allows you to create a partitioned table w/o adding partitions. So we cannot re-create this table in classic syntax:
  ```sql
  create table part(a int, b int) partition by range(b);
  ```  
  *  The classic syntax only allows to create a homogeneous partition hierarchy, like the one you have in your example, where all tables on the same level have the same partition method and key. The modern syntax can allow a heterogenous one, such as below which cannot be done in classic syntax:
  ```sql
  create table part(a int, b int, c int, d int) partition by range(b);
  create table part1 partition of part for values from (0) to (10) partition by range(c);
  create table part2 partition of part for values from (10) to (20) partition by range(d); -- different partition key than part1
  ```
  * On the other hand, modern syntax can express the homogeneous structure just fine. If you run pg_dump against your example you would see the equivalent DDLs. However, it would be more verbose, especially comparing to using convenient classic-style clauses such as `EVERY` in your example. But functionality-wise they are the same. And even if we are using classic syntax, internally it is doing exactly the same things as what you would get from the pg_dump output, so there should be no performance difference.
  ```sql
  pg_dump -s -d postgres --table-and-children='rp_date' -- change db name as needed
  ```
* Back to `pg_get_partition_def`: as an attempt to print a single classic-style partition definition clause for the entire partition hierarchy, it won't be feasible in GP7 where we have all kinds of partitioning structures.
* (So what should I do?) That depends on what's the purpose of using `pg_get_partition_def`.
  * If the purpose is just get equivalent DDLs, pg_dump should be able to do that or whatever method is used for the same purpose in Postgres.
  * If the purpose is to get "a single classic-style partition definition clause for the entire partition hierarchy", that's not feasible unfortunately. But I hope we don't have such a use case?
  * If the purpose is to get misc information about the partition hierarchy, there's other suitable way to do that such as `pg_partition_tree`. Let us know if this is the case and we can provide more help. We are planning to provide more documentation and guidance for that too.

Does this help?

**Comment by LonwoLonwo** [comment]
Wonderful explanation! 
But yes, I have the last question.

The partition part in my example looks relatively tiny:

```
PARTITION BY RANGE(RP_DATE)
(
     START (DATE '2015-06-01') INCLUSIVE
     END (DATE '2016-01-01') EXCLUSIVE EVERY (INTERVAL '1 DAY')
);
```

But if I will use a classic syntax, 214 create partition table statements will be added in my DDL:

![2023-08-03 10_21_12-DBeaver Ultimate 23 1 3 - rp_date](https://github.com/greenplum-db/gpdb/assets/45152336/2e420eea-e31c-4618-8785-b6f54c3df670)

And now I do not have functions to get original compact info about my table. 
This is not very convenient, IMHO.
So, I'm looking for a Greenplum-specific partition table part generator. But it seems there are no such.

**Comment by ashwinstar** [comment]
> So, I'm looking for a Greenplum-specific partition table part generator. But it seems there are no such.

@LonwoLonwo feedback noted and understand the inconvenience. I am thinking not immediately but in some future we do plan to dig into and explore the possibility of generating Classic Table SQL back (obviously for cases when we can only).

There are performance experiments being performed by team and those reveal the benefit of Classic syntax not just for eye (being tiny and easy to read/manipulate) but also helps with partition hierarchy creation faster. So, as we move forward in our journey will keep this issue updated with details. In short term yes this functionality doesn't exist hence changes have to be made to mitigate the same.
