### ISSUE TITLE
gprecoverseg failed when using the non-default database port(5432)

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpdb#17030]
### Greenplum version or build

- 6.26.1

### Actual behavior

```bash
[gpadmin@gp6mdw pg_log]$ cat $MASTER_DATA_DIRECTORY/postgresql.conf | grep port
port=5483 ##port 5432				# sets the database listener port for 
					# each segment has its own port number. 
					# supported by the operating system:
					# supported by the operating system:
#gpperfmon_port=8888		# Port used by the performance monitor daemons
#max_resource_portals_per_transaction = 64	# no. of portals per backend.
[gpadmin@gp6mdw pg_log]$ env | grep PORT
MASTER_PORT=5483
PGPORT=5483
```

```bash
[gpadmin@gp6mdw pg_log]$ gprecoverseg -a -v
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[INFO]:-Starting gprecoverseg with args: -a -v
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-WorkerPool() initialized with 16 workers
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-Obtaining master's port from master data directory
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-Read from postgresql.conf port=5483
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-Read from postgresql.conf max_connections=500
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-Running Command: echo 'START_CMD_OUTPUT';$GPHOME/bin/postgres --gp-version
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[INFO]:-local Greenplum Version: 'postgres (Greenplum Database) 6.26.1 build commit:0ed93c8b0cd523fc85d49b245fe901c063cf3a0b'
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-Connecting to dbname='template1'
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[INFO]:-master Greenplum Version: 'PostgreSQL 9.4.26 (Greenplum Database 6.26.1 build commit:0ed93c8b0cd523fc85d49b245fe901c063cf3a0b) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Dec  6 2023 03:38:31'
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[INFO]:-Obtaining Segment details from master...
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-Connecting to dbname='template1'
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-Validating configuration...
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-WorkerPool() initialized with 3 workers
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-Adding cmd to work_queue: ssh gp6sdw4 'echo gp6sdw4'
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-Adding cmd to work_queue: ssh gp6sdw3 'echo gp6sdw3'
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker0] got cmd: ssh gp6sdw4 'echo gp6sdw4'
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker1] got cmd: ssh gp6sdw3 'echo gp6sdw3'
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-Running Command: ssh gp6sdw4 'echo gp6sdw4'
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-Running Command: ssh gp6sdw3 'echo gp6sdw3'
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker1] finished cmd: check gp6sdw3 is up cmdStr='ssh gp6sdw3 'echo gp6sdw3''  had result: cmd had rc=0 completed=True halted=False
  stdout='gp6sdw3
'
  stderr=''
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker0] finished cmd: check gp6sdw4 is up cmdStr='ssh gp6sdw4 'echo gp6sdw4''  had result: cmd had rc=0 completed=True halted=False
  stdout='gp6sdw4
'
  stderr=''
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-WorkerPool haltWork()
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker0] haltWork
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker1] haltWork
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker2] got a halt cmd
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker1] got a halt cmd
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker2] haltWork
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker0] got a halt cmd
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-Connecting to dbname='template1'
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[ERROR]:-gprecoverseg failed.  exiting...
Traceback (most recent call last):
  File "/usr/local/greenplum-db-6.26.1/lib/python/gppylib/mainUtils.py", line 362, in simple_main_locked
    exitCode = commandObject.run()
  File "/usr/local/greenplum-db-6.26.1/lib/python/gppylib/programs/clsRecoverSegment.py", line 308, in run
    mirrorBuilder = self.getRecoveryActionsBasedOnOptions(gpEnv, gpArray)
  File "/usr/local/greenplum-db-6.26.1/lib/python/gppylib/programs/clsRecoverSegment.py", line 105, in getRecoveryActionsBasedOnOptions
    for t in instance.getTriplets()]
  File "/usr/local/greenplum-db-6.26.1/lib/python/gppylib/programs/clsRecoverSegment_triples.py", line 324, in getTriplets
    return self._convert_requests_to_triplets(requests)
  File "/usr/local/greenplum-db-6.26.1/lib/python/gppylib/programs/clsRecoverSegment_triples.py", line 221, in _convert_requests_to_triplets
    segments_with_running_basebackup = get_segments_with_running_basebackup()
  File "/usr/local/greenplum-db-6.26.1/lib/python/gppylib/programs/clsRecoverSegment_triples.py", line 30, in get_segments_with_running_basebackup
    raise Exception("Failed to query gp_stat_replication: %s" %str(e))
Exception: Failed to query gp_stat_replication: error 'ERROR:  failed to acquire resources on one or more segments
DETAIL:  could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
 (entry db 10.191.7.13:5432)
' in 'select gp_segment_id from gp_stat_replication where application_name = 'pg_basebackup''
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-WorkerPool haltWork()
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker0] haltWork
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker1] haltWork
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker0] got a halt cmd
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker2] haltWork
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker1] got a halt cmd
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker2] got a halt cmd
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker3] haltWork
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker4] haltWork
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker3] got a halt cmd
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker5] haltWork
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker4] got a halt cmd
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker5] got a halt cmd
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker6] haltWork
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker7] haltWork
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker6] got a halt cmd
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker8] haltWork
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker7] got a halt cmd
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker9] haltWork
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker8] got a halt cmd
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker10] haltWork
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker9] got a halt cmd
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker11] haltWork
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker10] got a halt cmd
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker12] haltWork
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker11] got a halt cmd
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker13] haltWork
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker12] got a halt cmd
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker14] haltWork
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker13] got a halt cmd
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker15] haltWork
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker14] got a halt cmd
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-[worker15] got a halt cmd
20240125:14:59:04:018602 gprecoverseg:gp6mdw:gpadmin-[DEBUG]:-Running Command: /bin/sync
```

**Comment by ashwinstar** [comment]
Not using standard port is pretty common practice (even our CI doesn't use standard port). Hence, surprised to see the reported failure, might be something else or logging @nimish350 @shrakesh Please help investigate

**Comment by piyushc01** [comment]
@cobolbaby looks like gp_segment_confgiration was not updated after the port change hence gprecoverseg is still referring to the old port. 
You can confirm this by executing "select * from gp_segment_configuration;" 
And checking the output of "ps -ef | grep postgres" on that host. 

Bring your cluster to original state and to change the port number for master follow the steps mentioned here: https://community.pivotal.io/s/article/How-to-change-data-directory-and-port-of-an-existing-Master-on-Tanzu-Greenplum?language=en_US

In case issue persists, please share the details from gp_segment_configuration table an the output for `ps -ef | grep postgres` from the failing segment pairs and gprecoverseg logs in debug mode.

**Comment by cobolbaby** [comment]
> looks like gp_segment_confgiration was not updated after the port change hence gprecoverseg is still referring to the old port.

Indeed, gp_segment_confgiration was not updated.

After modifying the configuration with the command `PGOPTIONS='-c allow_system_table_mods=on' psql -d postgres -ac "UPDATE gp_segment_configuration SET port=${MASTER_PORT} WHERE content = -1;"`, the execution of gprecoverseg is without any issues.

Thanks @piyushc01

**Comment by nimish350** [comment]
Thank you @cobolbaby I will close this issue if ok.
