### ISSUE TITLE
gp_toolkit.__gp_aocsseg_history crash on non-aocs tables

### ISSUE THREAD

**Issue by avamingli** [greenplum-db/gpdb#17142]
### Greenplum version or build
```sql
gpadmin=# select version();

version

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------
--------
 PostgreSQL 12.12 (Greenplum Database 7.1.0+dev.166.g2b59d35d13a build dev) on x86_64-pc-linux-gnu, compiled by
gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit compiled on Mar  1 2024 17:14:36 (with assert checking) Bhuv
nesh C.
(1 row)
```

### Step to reproduce the behavior
```sql
create table t1(id int);
gpadmin=# SELECT count(*) FROM gp_toolkit.__gp_aocsseg_history('t1');
ERROR:  Error on receive from seg1 slice1 127.0.1.1:7003 pid=1175899: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
gpadmin=#
```
coredump
```go
#0  __pthread_kill_implementation (no_tid=0, signo=11, threadid=140076186518784) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=11, threadid=140076186518784) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140076186518784, signo=signo@entry=11) at ./nptl/pthread_kill.c:89
#3  0x00007f660a16c476 in __GI_raise (sig=11) at ../sysdeps/posix/raise.c:26
#4  0x0000556d2a53229b in StandardHandlerForSigillSigsegvSigbus_OnMainThread (
    processName=0x556d2ac87bec "Segment process", postgres_signal_arg=11) at elog.c:5104
#5  0x0000556d2a34b761 in CdbProgramErrorHandler (postgres_signal_arg=11) at postgres.c:3632
#6  0x0000556d2aa4e1c9 in wrapper_handler (postgres_signal_arg=11) at pqsignal.c:93
#7  <signal handler called>
#8  __strlen_evex () at ../sysdeps/x86_64/multiarch/strlen-evex.S:77
#9  0x0000556d2aa4ff82 in dopr (target=0x7ffe5bf1e210,
    format=0x556d2aae236c "' does not have append-optimized column-oriented storage", args=0x7ffe5bf1e330)
    at snprintf.c:444
#10 0x0000556d2aa4f79f in pg_vsnprintf (str=0x556d315e20e0 "Relation '", '\177' <repeats 190 times>...,
    count=1024, fmt=0x556d2aae2360 "Relation '%s' does not have append-optimized column-oriented storage",
    args=0x7ffe5bf1e330) at snprintf.c:195
#11 0x0000556d2aa5b9ea in pvsnprintf (buf=0x556d315e20e0 "Relation '", '\177' <repeats 190 times>...,
    len=1024, fmt=0x556d2aae2360 "Relation '%s' does not have append-optimized column-oriented storage",
    args=0x7ffe5bf1e330) at psprintf.c:110
#12 0x0000556d2aa5d653 in appendStringInfoVA (str=0x7ffe5bf1e310,
    fmt=0x556d2aae2360 "Relation '%s' does not have append-optimized column-oriented storage",
    args=0x7ffe5bf1e330) at stringinfo.c:165
#13 0x0000556d2a528afb in errmsg (
    fmt=0x556d2aae2360 "Relation '%s' does not have append-optimized column-oriented storage") at elog.c:1027
#14 0x0000556d29e46203 in gp_aocsseg_history (fcinfo=0x556d3178b920) at aocssegfiles.c:1481
#15 0x00007f660ad60342 in gp_aocsseg_history_wrapper (fcinfo=0x556d3178b920) at gp_ao_co_diagnostics.c:232
#16 0x0000556d2a0606e3 in ExecMakeTableFunctionResult (setexpr=0x556d316d48a0, econtext=0x556d316d4788,
    argContext=0x556d3178b7e0, expectedDesc=0x556d31780358, randomAccess=false, operatorMemKB=127900)
    at execSRF.c:238
#17 0x0000556d2a07f01e in FunctionNext_guts (node=0x556d316d4570) at nodeFunctionscan.c:141
#18 0x0000556d2a07f52d in FunctionNext (node=0x556d316d4570) at nodeFunctionscan.c:319
#19 0x0000556d2a05fbdb in ExecScanFetch (node=0x556d316d4570, accessMtd=0x556d2a07f511 <FunctionNext>,
    recheckMtd=0x556d2a07f56e <FunctionRecheck>) at execScan.c:137
#20 0x0000556d2a05fc89 in ExecScan (node=0x556d316d4570, accessMtd=0x556d2a07f511 <FunctionNext>,
    recheckMtd=0x556d2a07f56e <FunctionRecheck>) at execScan.c:189
#21 0x0000556d2a07f5c7 in ExecFunctionScan (pstate=0x556d316d4570) at nodeFunctionscan.c:351
#22 0x0000556d2a05c693 in ExecProcNodeGPDB (node=0x556d316d4570) at execProcnode.c:645
#23 0x0000556d2a05c527 in ExecProcNodeFirst (node=0x556d316d4570) at execProcnode.c:600
#24 0x0000556d2a070c36 in ExecProcNode (node=0x556d316d4570) at ../../../src/include/executor/executor.h:271
#25 0x0000556d2a07128e in fetch_input_tuple (aggstate=0x556d316d3ef8) at nodeAgg.c:602
#26 0x0000556d2a074e1c in agg_retrieve_direct (aggstate=0x556d316d3ef8) at nodeAgg.c:2527
#27 0x0000556d2a074991 in ExecAgg (pstate=0x556d316d3ef8) at nodeAgg.c:2335
#28 0x0000556d2a05c693 in ExecProcNodeGPDB (node=0x556d316d3ef8) at execProcnode.c:645
#29 0x0000556d2a05c527 in ExecProcNodeFirst (node=0x556d316d3ef8) at execProcnode.c:600
#30 0x0000556d2a0bed12 in ExecProcNode (node=0x556d316d3ef8) at ../../../src/include/executor/executor.h:271
#31 0x0000556d2a0bf162 in execMotionSender (node=0x556d316d3be8) at nodeMotion.c:227
#32 0x0000556d2a0bf029 in ExecMotion (pstate=0x556d316d3be8) at nodeMotion.c:191
#33 0x0000556d2a05c693 in ExecProcNodeGPDB (node=0x556d316d3be8) at execProcnode.c:645
#34 0x0000556d2a05c527 in ExecProcNodeFirst (node=0x556d316d3be8) at execProcnode.c:600
#35 0x0000556d2a04d665 in ExecProcNode (node=0x556d316d3be8) at ../../../src/include/executor/executor.h:271
#36 0x0000556d2a0522d3 in ExecutePlan (estate=0x556d316d3990, planstate=0x556d316d3be8,
    use_parallel_mode=false, operation=CMD_SELECT, sendTuples=false, numberTuples=0,
    direction=ForwardScanDirection, dest=0x556d316ba1f8, execute_once=false) at execMain.c:2672
#37 0x0000556d2a04f0ff in standard_ExecutorRun (queryDesc=0x556d31609950, direction=ForwardScanDirection,
    count=0, execute_once=false) at execMain.c:922
#38 0x0000556d2a04ec89 in ExecutorRun (queryDesc=0x556d31609950, direction=ForwardScanDirection, count=0,
    execute_once=false) at execMain.c:793
#39 0x0000556d2a3517d6 in PortalRunSelect (portal=0x556d3169dc30, forward=true, count=0, dest=0x556d316ba1f8)
    at pquery.c:1147
#40 0x0000556d2a3513a2 in PortalRun (portal=0x556d3169dc30, count=9223372036854775807, isTopLevel=true,
    run_once=false, dest=0x556d316ba1f8, altdest=0x556d316ba1f8, completionTag=0x7ffe5bf1f0c0 "")
    at pquery.c:985
#41 0x0000556d2a3477c9 in exec_mpp_query (
    query_string=0x556d315e5342 "SELECT count(*) FROM gp_toolkit.__gp_aocsseg_history('t1');",
    serializedPlantree=0x556d315e537e "(\265/\375`\247\005\355\017", serializedPlantreelen=519,
    serializedQueryDispatchDesc=0x556d315e5585 "(\265/\375`\016", serializedQueryDispatchDesclen=147)
    at postgres.c:1438
#42 0x0000556d2a34e87c in PostgresMain (argc=1, argv=0x556d316266d8, dbname=0x556d31612968 "gpadmin",
    username=0x556d31612948 "gpadmin") at postgres.c:5575
#43 0x0000556d2a26fba2 in BackendRun (port=0x556d31616950) at postmaster.c:4985
#44 0x0000556d2a26f1b7 in BackendStartup (port=0x556d31616950) at postmaster.c:4662
#45 0x0000556d2a26a738 in ServerLoop () at postmaster.c:2016
#46 0x0000556d2a269c40 in PostmasterMain (argc=5, argv=0x556d315dfec0) at postmaster.c:1631
#47 0x0000556d2a105f77 in main (argc=5, argv=0x556d315dfec0) at main.c:240
```

**Comment by kainwen** [comment]
The issue is closed automatically. I have a quick look at 6X, seems not impacted. @avamingli would you help double confirm? Thanks.

**Comment by avamingli** [comment]
> The issue is closed automatically. I have a quick look at 6X, seems not impacted. @avamingli would you help double confirm? Thanks.

confirmed, 6X doesn't have this issue. 
It's introduced by https://github.com/greenplum-db/gpdb/pull/10862 which is part of Merge to PG12.
