### ISSUE TITLE
Segmentation fault on jsonb_array_elements with ordinality

### ISSUE THREAD

**Issue by sakhinov** [greenplum-db/gpdb#17461]
### Greenplum version or build
```
postgres=# SELECT VERSION();
PostgreSQL 12.12 (Greenplum Database 7.0.0-b2 build dev) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit compiled on Oct 31 2023 20:23:34 Bhuvnesh C.
```
### OS version and uname -a
Ubuntu 22.04
```
$ uname -a
Linux gpdbtest 3.10.0-1160.36.2.el7.x86_64 #1 SMP Thu Jul 8 02:53:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
### Installation information ( pg_config )
```
$ pg_config
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib
PKGLIBDIR = /usr/local/gpdb/lib/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /usr/local/gpdb/etc/postgresql
PGXS = /usr/local/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-perl' '--with-python' '--with-libxml' '--enable-gpfdist' '--with-gssapi' '--with-zstd' '--prefix=/usr/local/gpdb'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-but-set-variable -Werror=implicit-fallthrough=3 -Wno-format-truncation -Wno-stringop-truncation -O3  -Werror=uninitialized -Werror=implicit-function-declaration
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lxerces-c -lbz2 -lxml2 -lrt -lgssapi_krb5 -lz -lreadline -lcrypt -lm  -lcurl -lzstd
VERSION = PostgreSQL 12.12
```
### Expected behavior

|value|
|-----|
|"a"  |
|"b"  |
|"c"  |
### Actual behavior
SQL Error [08006]
```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [08006]: An I/O error occurred while sending to the backend.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:607)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:510)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:517)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:971)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4134)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5151)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:383)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
Caused by: java.io.EOFException
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2120)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	... 20 more
```
```
$ cat log/gpdb-2024-05-13_000000.csv
2024-05-13 14:37:06.776894 UTC,,,p231724,th0,,,2024-05-13 14:37:06 UTC,0,con6,cmd2,seg-1,,,,,"PANIC","XX000","Unexpected internal error: Master process received signal SIGSEGV",,,,,,,0,,,,"1    0x55c4397a02c2 postgres StandardHandlerForSigillSigsegvSigbus_OnMainThread +
0x1d2
2    0x7f633f114520 libc.so.6 <symbol not found> + 0x3f114520
3    0x55c439b6a0e3 postgres _ZN5gpdxl16CTranslatorUtils30GetColumnDescriptorsFromRecordEPN4gpos11CMemoryPoolEPNS_12CIdGeneratorEP4ListPNS1_16CDynamicPtrArrayIN4gpmd5IMDIdEXadL_ZNS1_14CleanupReleaseISA_EEvPT_EEEE + 0x133
4    0x55c439b6ae69 postgres _ZN5gpdxl16CTranslatorUtils23ConvertToCDXLLogicalTVFEPN4gpos11CMemoryPoolEPN5gpopt11CMDAccessorEPNS_12CIdGeneratorEPK13RangeTblEntry + 0x3d9
5    0x55c439b84fab postgres _ZN5gpdxl21CTranslatorQueryToDXL17TranslateTVFToDXLEPK13RangeTblEntryjj + 0x7b
6    0x55c439b85b3e postgres _ZN5gpdxl21CTranslatorQueryToDXL22TranslateFromExprToDXLEP8FromExpr + 0x22e
7    0x55c439b8688d postgres _ZN5gpdxl21CTranslatorQueryToDXL21TranslateGroupingSetsEP8FromExprP4ListS4_S4_bPN4gpos8CHashMapIijXadL_ZNS5_9HashValueIiEEjPKT_EEXadL_ZNS5_6EqualsIiEEbSA_SA_EEXadL_ZNS5_13CleanupDeleteIiEEvPS8_EEXadL_ZNSC_IjEEvSD_EEEESF_ + 0x7d
8    0x55c439b86f30 postgres _ZN5gpdxl21CTranslatorQueryToDXL25TranslateSelectQueryToDXLEv + 0x3a0
9    0x55c439b88ed9 postgres _ZN5gpdxl21CTranslatorQueryToDXL19TranslateQueryToDXLEv + 0xd9
10   0x55c439b9d63a postgres _ZN9COptTasks12OptimizeTaskEPv + 0x29a
11   0x55c4398698d4 postgres _ZN4gpos5CTask7ExecuteEv + 0x44
12   0x55c43986a82a postgres _ZN4gpos7CWorker7ExecuteEPNS_5CTaskE + 0x1a
13   0x55c439868eb0 postgres _ZNK4gpos14CAutoTaskProxy7ExecuteEPNS_5CTaskE + 0x60
14   0x55c43986b319 postgres gpos_exec + 0x269
15   0x55c439b9b5cc postgres _ZN9COptTasks7ExecuteEPFPvS0_ES0_ + 0x7c
16   0x55c439b9c93c postgres _ZN9COptTasks18GPOPTOptimizedPlanEP5QueryP11SOptContext + 0x1c
17   0x55c439b9eacf postgres GPOPTOptimizedPlan + 0x3f
18   0x55c439540c79 postgres optimize_query + 0x129
19   0x55c43953524b postgres standard_planner + 0x86b
20   0x55c43961f3d3 postgres pg_plan_queries + 0x53
21   0x55c439779320 postgres <symbol not found> + 0x39779320
22   0x55c439779d7a postgres GetCachedPlan + 0x1ea
23   0x55c43961edb8 postgres <symbol not found> + 0x3961edb8
24   0x55c439620f4f postgres PostgresMain + 0x90f
25   0x55c439586904 postgres <symbol not found> + 0x39586904
26   0x55c4395878da postgres PostmasterMain + 0xd3a
27   0x55c4391e51c0 postgres main + 0x510
28   0x7f633f0fbd90 libc.so.6 <symbol not found> + 0x3f0fbd90
29   0x7f633f0fbe40 libc.so.6 __libc_start_main + 0x80
30   0x55c4391f4715 postgres _start + 0x25
"
2024-05-13 14:37:06.913146 UTC,,,p131,th1012287872,,,,0,,,seg-1,,,,,"LOG","00000","server process (PID 231724) was terminated by signal 11: Segmentation fault","Failed process was running: select * from jsonb_array_elements('[""c"", ""a"", ""b""]'::jsonb) with ordinality
",,,,,,0,,"postmaster.c",4216,
2024-05-13 14:37:06.913185 UTC,,,p131,th1012287872,,,,0,,,seg-1,,,,,"LOG","00000","terminating any other active server processes",,,,,,,0,,"postmaster.c",3944,
```
### Step to reproduce the behavior
`postgres=# SELECT * FROM jsonb_array_elements('["c", "a", "b"]'::jsonb) WITH ORDINALITY;`

**Comment by chrishajas** [comment]
Thanks for the report! Just some notes: it seems Orca doesn't support "WITH ORDINALITY" well (or really at all). If it doesn't crash, it ends up falling back with `Query-to-DXL Translation: No variable entry found due to incorrect normalization of query` which also isn't great. This also affects 6X.

**Comment by chrishajas** [comment]
Fixed with https://github.com/greenplum-db/gpdb/commit/99f0c829398291e0026f1628c6732021f5b7e29b, thanks for the report!
