### ISSUE TITLE
Unable to connect to Beta 2 via JDBC or psycopg2

### ISSUE THREAD

**Issue by kdunn-pivotal** [greenplum-db/gpdb#2701]
It looks like some extra things have been added to the Postgres version string that breaks downstream JDBC  / Python clients:
```
gpadmin=# select version() ;
-[ RECORD 1 ]-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
version | PostgreSQL 8.3.23 (Greenplum Database 5.0.0-beta.2 build commit:7256defe7f6dcf1ff81f1b5c6f62e49388edf1fb) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 6.2.0 compiled on Jun 24 2017 21:16:56
```

When I try and establish a JDBC connection via a Spring application, I receive the following stack trace:
```
Caused by: java.lang.NumberFormatException: For input string: "0-beta"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_45]
	at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_45]
	at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_45]
	at com.pivotal.jdbc.greenplum.GreenplumImplConnection.a6(Unknown Source) ~[greenplum-jdbc-5.1.4.jar!/:na]
	at com.pivotal.jdbc.greenplum.GreenplumImplConnection.d(Unknown Source) ~[greenplum-jdbc-5.1.4.jar!/:na]
	at com.pivotal.jdbc.greenplumbase.BaseConnection.a(Unknown Source) ~[greenplum-jdbc-5.1.4.jar!/:na]
	at com.pivotal.jdbc.greenplumbase.BaseDriver.connect(Unknown Source) ~[greenplum-jdbc-5.1.4.jar!/:na]
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:310) ~[tomcat-jdbc-8.5.11.jar!/:na]
```

I've been able to work around the issue for Python by modifying the client connection code regex, but ultimately we should think about adding a test to validate a simple JDBC or Python connection.

**Comment by davecramer** [comment]
Pretty sure this is not the postgresql jdbc client complaining. This would
be the proprietary client from progress I believe.

Dave Cramer

**Comment by kdunn-pivotal** [comment]
Correct - the open source Postgres JDBC works as expected.

**Comment by ivannovick** [comment]
Hi @kdunn-pivotal , for the Progress driver we need to handle this within Pivotal not in github.  Closing this issue, and will open a JIRA internally at Pivotal
