### ISSUE TITLE
gppkg --remove fails with error "numWorkers should be greater than 0"

### ISSUE THREAD

**Issue by lmugnano** [greenplum-db/gpdb#3166]
GPDB Beta Version 10
Madlib version installed is madlib-ossv1.11_pv1.9.8_gpdb5.0

Trying to remove the madlib-ossv1.11_pv1.9.8_gpdb5.0 package from the database but am getting error:

Here is verbose output of the command:

```
[gpadmin@gpdbsne 5010]$ gppkg -v --remove=madlib-ossv1.11_pv1.9.8_gpdb5.0
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[INFO]:-Starting gppkg with args: -v --remove=madlib-ossv1.11_pv1.9.8_gpdb5.0
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-_get_master_port
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-_get_gpdb_host_list
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Connecting to dbname='template1'
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Starting ListFilesByPattern
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Ending ListFilesByPattern
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Starting ListFilesByPattern
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Ending ListFilesByPattern
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-from_package_path
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Gppkg Constructor
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Starting UninstallPackage
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[INFO]:-Uninstalling package madlib-ossv1.11_pv1.9.8_gpdb5.0-rhel5-x86_64.gppkg
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Starting ExtractPackage
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Starting CleanupDir
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Cleaning up /usr/local/greenplum-db-5.0.0-beta.10/.tmp
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Ending CleanupDir
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Ending ExtractPackage
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Starting ValidateUninstallPackage
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[INFO]:-Validating rpm uninstallation cmdStr='rpm --test -e madlib-1.11-1 --dbpath /usr/local/greenplum-db-5.0.0-beta.10/share/packages/database'
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Starting CheckFile
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Ending CheckFile
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Ending ValidateUninstallPackage
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Starting PerformHooks
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Ending PerformHooks
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Starting HostOperation
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Starting ParallelOperation
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Ending ParallelOperation
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Ending HostOperation
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[DEBUG]:-Ending UninstallPackage
20170905:16:19:05:022534 gppkg:gpdbsne:gpadmin-[ERROR]:-gppkg failed.  exiting...
Traceback (most recent call last):
  File "/usr/local/greenplum-db/lib/python/gppylib/mainUtils.py", line 271, in simple_main_locked
    exitCode = commandObject.run()
  File "/usr/local/greenplum-db/lib/python/gppylib/programs/gppkg.py", line 230, in run
    UninstallPackage(pkg, self.master_host, self.standby_host, self.segment_host_list).run()
  File "/usr/local/greenplum-db/lib/python/gppylib/operations/__init__.py", line 53, in run
    self.ret = self.execute()
  File "/usr/local/greenplum-db/lib/python/gppylib/operations/package.py", line 947, in execute
    HostOperation(UninstallPackageLocally(self.gppkg.pkg), self.segment_host_list).run()
  File "/usr/local/greenplum-db/lib/python/gppylib/operations/__init__.py", line 53, in run
    self.ret = self.execute()
  File "/usr/local/greenplum-db/lib/python/gppylib/operations/package.py", line 1351, in execute
    ParallelOperation(operations).run()
  File "/usr/local/greenplum-db/lib/python/gppylib/operations/__init__.py", line 53, in run
    self.ret = self.execute()
  File "/usr/local/greenplum-db/lib/python/gppylib/operations/utils.py", line 67, in execute
    pool = OperationWorkerPool(numWorkers=self.parallelism, operations=self.operations)
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 172, in __init__
    super(OperationWorkerPool, self).__init__(numWorkers, operations)
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 56, in __init__
    raise Exception("WorkerPool(): numWorkers should be greater than 0.")
Exception: WorkerPool(): numWorkers should be greater than 0.
```

**Comment by Chibin** [comment]
Thanks for reporting this.

Also, this was addressed by the following patch:
https://github.com/greenplum-db/gpdb/commit/686256f63aadebe403a8795b37687336a1afd436

**Comment by d** [comment]
@Chibin the patch in PR #3085 seems to only affect _installing_ packages, not _uninstalling_ packages. Also, OP stated he's using beta 10, which already includes commit 686256f

**Comment by Chibin** [comment]
@d Oh hmm, I must have been looking at the wrong tag. Will take a look into this.

**Comment by Chibin** [comment]
This was also addressed by another patch/commit:
https://github.com/greenplum-db/gpdb/commit/29ad32b62ffb5c6efc2e7c412b35b5b8c1220042

**Comment by hsyuan** [comment]
closing this because it was fixed in 5X_STABLE and master branch.

**Comment by lmugnano** [comment]
Thanks, when will this fix be packaged into the Greenplum product delivered
on pivnet (currently I'm using the latest which is beta 10)?
