### ISSUE TITLE
make create-demo-cluster fails on new macOS machines

### ISSUE THREAD

**Issue by professor** [greenplum-db/gpdb#3397]
The key problem is `ImportError: No module named paramiko`

```
/Library/Developer/CommandLineTools/usr/bin/make -C gpAux/gpdemo create-demo-cluster
======================================================================
            ______  _____  ______  _______ _______  _____
           |  ____ |_____] |     \ |______ |  |  | |     |
           |_____| |       |_____/ |______ |  |  | |_____|

----------------------------------------------------------------------

  This is a demo of the Greenplum Database system.  We will create
  a cluster installation with master and 6 segment instances
  (3 primary & 3 mirror).

    GPHOME ................. : /usr/local/gpdb
    MASTER_DATA_DIRECTORY .. : /Users/pivotal/workspace/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1

    MASTER PORT (PGPORT) ... : 15432
    SEGMENT PORTS .......... : 25432 25433 25434 25435 25436 25437 25438 25439 25440 25441 25442 25443

  NOTE(s):

    * The DB ports identified above must be available for use.
    * An environment file gpdemo-env.sh has been created for your use.

======================================================================

==========================================================================================
executing:
  /usr/local/gpdb/bin/gpinitsystem -a -c clusterConfigFile -l /Users/pivotal/workspace/gpdb/gpAux/gpdemo/datadirs/gpAdminLogs ""
==========================================================================================

20170927:09:28:58:060265 gpinitsystem:pivotals-Mac:pivotal-[INFO]:-Checking configuration parameters, please wait...
20170927:09:28:58:060265 gpinitsystem:pivotals-Mac:pivotal-[INFO]:-Reading Greenplum configuration file clusterConfigFile
20170927:09:28:59:060265 gpinitsystem:pivotals-Mac:pivotal-[INFO]:-Locale has not been set in clusterConfigFile, will set to default value
20170927:09:28:59:060265 gpinitsystem:pivotals-Mac:pivotal-[INFO]:-Locale set to en_US.utf-8
20170927:09:28:59:060265 gpinitsystem:pivotals-Mac:pivotal-[INFO]:-No DATABASE_NAME set, will exit following template1 updates
20170927:09:28:59:060265 gpinitsystem:pivotals-Mac:pivotal-[INFO]:-MASTER_MAX_CONNECT not set, will set to default value 25
20170927:09:28:59:060265 gpinitsystem:pivotals-Mac:pivotal-[INFO]:-Detected a single host GPDB array build, reducing value of BATCH_DEFAULT from 60 to 4
20170927:09:28:59:060265 gpinitsystem:pivotals-Mac:pivotal-[WARN]:-Master open file limit is 4864 should be >= 65535
20170927:09:29:00:060265 gpinitsystem:pivotals-Mac:pivotal-[INFO]:-Checking configuration parameters, Completed
20170927:09:29:00:060265 gpinitsystem:pivotals-Mac:pivotal-[INFO]:-Commencing multi-home checks, please wait...
.
20170927:09:29:00:060265 gpinitsystem:pivotals-Mac:pivotal-[INFO]:-Configuring build for standard array
20170927:09:29:00:060265 gpinitsystem:pivotals-Mac:pivotal-[INFO]:-Commencing multi-home checks, Completed
20170927:09:29:00:060265 gpinitsystem:pivotals-Mac:pivotal-[INFO]:-Building primary segment instance array, please wait...
...
20170927:09:29:01:060265 gpinitsystem:pivotals-Mac:pivotal-[INFO]:-Building group mirror array type , please wait...
...
20170927:09:29:02:060265 gpinitsystem:pivotals-Mac:pivotal-[INFO]:-Checking Master host
20170927:09:29:03:060265 gpinitsystem:pivotals-Mac:pivotal-[INFO]:-Checking new segment hosts, please wait...
20170927:09:29:03:060265 gpinitsystem:pivotals-Mac:pivotal-[WARN]:-Host pivotals-Mac.local open files limit is 4864 should be >= 65535
......
20170927:09:29:05:060265 gpinitsystem:pivotals-Mac:pivotal-[INFO]:-Checking new segment hosts, Completed
20170927:09:29:05:060265 gpinitsystem:pivotals-Mac:pivotal-[INFO]:-Building the Master instance database, please wait...
20170927:09:29:11:060265 gpinitsystem:pivotals-Mac:pivotal-[INFO]:-Starting the Master in admin mode
Traceback (most recent call last):
  File "/usr/local/gpdb/bin/lib/gphostcachelookup.py", line 12, in <module>
    from gppylib.gphostcache import GpInterfaceToHostNameCache
  File "/usr/local/gpdb/lib/python/gppylib/gphostcache.py", line 30, in <module>
    from gppylib.commands import base
  File "/usr/local/gpdb/lib/python/gppylib/commands/base.py", line 36, in <module>
    import paramiko, getpass
ImportError: No module named paramiko
20170927:09:29:15:gpinitsystem:pivotals-Mac:pivotal-[FATAL]:-Unable to contact  Script Exiting!
20170927:09:29:15:060265 gpinitsystem:pivotals-Mac:pivotal-[WARN]:-Script has left Greenplum Database in an incomplete state
20170927:09:29:15:060265 gpinitsystem:pivotals-Mac:pivotal-[WARN]:-Run command /bin/bash /Users/pivotal/workspace/gpdb/gpAux/gpdemo/datadirs/gpAdminLogs/backout_gpinitsystem_pivotal_20170927_092858 to remove these changes
20170927:09:29:15:060265 gpinitsystem:pivotals-Mac:pivotal-[INFO]:-Start Function BACKOUT_COMMAND
20170927:09:29:15:060265 gpinitsystem:pivotals-Mac:pivotal-[INFO]:-End Function BACKOUT_COMMAND
========================================
gpinitsystem returned: 2
========================================

======================================================================
                           OPTIMIZER STATE
----------------------------------------------------------------------
  Optimizer state .. : psql: FATAL:  System was started in master-only utility mode - only utility mode connections are allowed
======================================================================

psql: FATAL:  System was started in master-only utility mode - only utility mode connections are allowed
======================================================================

make[1]: *** [create-demo-cluster] Error 2
make: *** [create-demo-cluster] Error 2
```

**Comment by hsyuan** [comment]
Did you install paramiko on your new mac?

**Comment by professor** [comment]
Yes is is installed here: https://github.com/greenplum-db/gpdb/blob/2ec69545207c06012e5ce8b36e37cf5f95b19eea/README.macOS.bash#L31

`
Collecting paramiko
  Downloading paramiko-2.3.1-py2.py3-none-any.whl (182kB)
`

Looks like pip wasn't recognized by the terminal. I'm going to close this issue and see if I can reproduce it again.

**Comment by professor** [comment]
This pull request fixes this issue: https://github.com/greenplum-db/gpdb/pull/3652
