### ISSUE TITLE
DESTDIR make install

### ISSUE THREAD

**Issue by salahaldin** [greenplum-db/gpdb#3449]
Hello Guys, 

I think there is an issue with DISTDIR, I am trying to install greeplum5 , in  a certain location. it looks like the DESTDIR environmental variable is not set  

`./configure --with-libxml --prefix=/usr/local/gpdb5
`
`make
`
The make install fails with the following:
```
make[2]: Entering directory '/home/salahaldin/gpdb-5.0.0/gpMgmt/bin'
--- PyGreSQL
. /usr/local/gpdb5/greenplum_path.sh && unset PYTHONHOME && \
if [ `uname -s` = 'HP-UX' ]; then \
    cd /home/salahaldin/gpdb-5.0.0/gpMgmt/bin/pythonSrc/PyGreSQL-4.0 && DESTDIR="" CC="gcc" LDFLAGS="-L../../../../gpAux/ext/hpux_ia64/python-2.5.6/lib" python setup.py build; \
elif [  = 'aix7_ppc_64' ]; then \
    cd /home/salahaldin/gpdb-5.0.0/gpMgmt/bin/pythonSrc/PyGreSQL-4.0 && DESTDIR="" CC="gcc" python_64 setup.py build; \
else \
    cd /home/salahaldin/gpdb-5.0.0/gpMgmt/bin/pythonSrc/PyGreSQL-4.0 && DESTDIR="" CC="gcc" python setup.py build; \
fi
/bin/sh: 4: [: =: unexpected operator
Traceback (most recent call last):
  File "setup.py", line 105, in <module>
    mk_include()
  File "setup.py", line 76, in mk_include
    for f in os.listdir(pg_include_dir_server):
OSError: [Errno 2] No such file or directory: '/usr/local/gpdb/include/postgresql/server'
Makefile:60: recipe for target 'pygresql' failed
make[2]: *** [pygresql] Error 1
make[2]: Leaving directory '/home/salahaldin/gpdb-5.0.0/gpMgmt/bin'
Makefile:67: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/home/salahaldin/gpdb-5.0.0/gpMgmt'
GNUmakefile:40: recipe for target 'install' failed
make: *** [install] Error 2
```

To fiix the issue I have exported DIST DIR as follows:

` export DESTDIR=/usr/local/gpdb5
`

**Comment by yydzero** [comment]
I think this has been fixed . Do you still have this issue?

**Comment by ashwinstar** [comment]
closing the issue, as very old and didn't hear back if still a problem
