### ISSUE TITLE
org.postgresql.util.PSQLException: ERROR: Interconnect error reading register message from 183.61.47.108:54531: format not recognized

### ISSUE THREAD

**Issue by DongJianzhi0223** [greenplum-db/gpdb#3642]
when i use bireme import data from mysql to gpdb. i got a org.postgresql.util.PSQLException like this

Caused by: org.postgresql.util.PSQLException: ERROR: Interconnect error reading register message from 183.61.47.108:54531: format not recognized  (seg0 edaddw04:40000 pid=25667)
  Detail: msgBytes=65 expected=32 sockfd=29 local=10.141.19.37:34149
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102) ~[postgresql-9.1-901.jdbc4.jar:?]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835) ~[postgresql-9.1-901.jdbc4.jar:?]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257) ~[postgresql-9.1-901.jdbc4.jar:?]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500) ~[postgresql-9.1-901.jdbc4.jar:?]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:374) ~[postgresql-9.1-901.jdbc4.jar:?]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:302) ~[postgresql-9.1-901.jdbc4.jar:?]
        at cn.hashdata.bireme.ChangeLoader.createTemporaryTable(ChangeLoader.java:500) ~[bireme-1.0.0.jar:?]
        ... 9 more

it happens occasionally

**Comment by yydzero** [comment]
Thanks for reporting! Which version are you using?

**Comment by hlinnaka** [comment]
There is not enough information here to debug this, I'm afraid. Closing, since there's nothing we can do.
