### ISSUE TITLE
[BUG] execute gpconfigurenewsegment failed

### ISSUE THREAD

**Issue by funnyxj** [greenplum-db/gpdb#420]
When I execute gpaddmirrors cmd, sometimes it will fail, see the log, will appear following massage:

```
20160223:15:51:08:003592 gpaddmirrors:127.0.0.1:test-[INFO]:-Validating remote directories
......... 
20160223:15:51:17:003592 gpaddmirrors:127.0.0.1:test-[INFO]:-Copying template directory file
. 
20160223:15:51:18:003592 gpaddmirrors:127.0.0.1:test-[INFO]:-Configuring new segments
......... 
20160223:15:51:27:003592 gpaddmirrors:127.0.0.1:test-[CRITICAL]:-Error occurred: Error Executing Command: 
Command was: '$GPHOME/bin/lib/gpconfigurenewsegment -c "/test/test/3006:3006:false:false:4" -n -t gp_emptySegmentSchema.tar -B 16"'
rc=1, stdout='20160223:15:51:19:019727 gpconfigurenewsegment:127.0.0.1:test-[INFO]:-Starting gpconfigurenewsegment with args: -c /test/test/3006:3006:false:false:4 -n -t gp_emptySegmentSchema.tar -B 16
20160223:15:51:19:019727 gpconfigurenewsegment:127.0.0.1:test-[INFO]:-Validate data directories for new segment
20160223:15:51:19:019727 gpconfigurenewsegment:127.0.0.1:test-[INFO]:-Create or update data directories for new segment
20160223:15:51:19:019727 gpconfigurenewsegment:127.0.0.1:test-[INFO]:-extract tar file to new segment
20160223:15:51:19:019727 gpconfigurenewsegment:127.0.0.1:test-[INFO]:-create gp_dbid file for segment
20160223:15:51:19:019727 gpconfigurenewsegment:127.0.0.1:test-[INFO]:-Updating /test/test/3006/postgresql.conf
', stderr='Traceback (most recent call last):
File "/test/bin/lib/gpconfigurenewsegment", line 393, in 
pool.haltWork()
File "/test/lib/python/gppylib/commands/base.py", line 157, in haltWork
w.haltWork() 
File "/test/lib/python/gppylib/commands/base.py", line 253, in haltWork
c.interrupt()
File "/test/bin/lib/gpconfigurenewsegment", line 239, in interrupt
self.exec_context.interrupt()
TypeError: interrupt() takes exactly 2 arguments (1 given)
```

It is easy to find its reasons, I think it is a bug:
In File gpconfigurenewsegment:

```
    def interrupt(self):
        self.exec_context.interrupt()
```

But exec_context interrupt() function is a different definition:

In File gppylib/commands/base.py

```
class LocalExecutionContext(ExecutionContext):
    def interrupt(self,cmd):
        self.halt=True
        if self.proc:
            self.proc.cancel()
```

exec_context interrupt() need cmd args, so it will fail.

We can fix it through following codes:

```
class LocalExecutionContext(ExecutionContext):
    def interrupt(self,cmd=''):
        self.halt=True
        if self.proc:
            self.proc.cancel()
```

**Comment by berlin-ab** [comment]
@skahler-pivotal Can we triage this issue. Is it still and issue? If not, can we close it?

**Comment by slari-pivotal** [comment]
I don't see gpconfigurenewsegment having an `interrupt()` function in master, 5X_STABLE, or 4.3_STABLE branches.

However, the 4.3.6.0 branch does have the `ConfExpSegCmd.interrupt()` function defined as:

```
    def interrupt(self):
        self.exec_context.interrupt()
```

In this branch, the `interrupt()` functions in `NakedExecutionContext`, `LocalExecutionContext`, and `ExecutionContext` in bin/gppylib/commands/base.py does take two arguments. Same is true for the `cancel(`) function which also takes two arguments, but gpconfigurenewsegment only passes one (the `self` parameter).

**Comment by slari-pivotal** [comment]
Closing the issue as it looks like it is no longer applicable.
