### ISSUE TITLE
'updated tuple is already HEAP_MOVED_OFF' error in gpexpand

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#4298]
On the walreplication branch, we're seeing a failure like this in the `gpexpand` regression tests:

```
20180111:16:00:06:025858 gpexpand:mdw:gpadmin-[INFO]:-Syncing Greenplum Database extensions
20180111:16:00:07:025858 gpexpand:mdw:gpadmin-[INFO]:-The packages on sdw4 are consistent.
20180111:16:00:08:025858 gpexpand:mdw:gpadmin-[INFO]:-The packages on sdw1 are consistent.
20180111:16:00:09:025858 gpexpand:mdw:gpadmin-[INFO]:-The packages on sdw2 are consistent.
20180111:16:00:09:025858 gpexpand:mdw:gpadmin-[INFO]:-The packages on sdw3 are consistent.
20180111:16:00:10:025858 gpexpand:mdw:gpadmin-[INFO]:-Creating segment template
20180111:16:00:10:025858 gpexpand:mdw:gpadmin-[INFO]:-VACUUM FULL on the catalog tables
20180111:16:00:11:025858 gpexpand:mdw:gpadmin-[ERROR]:-gpexpand failed: Traceback (most recent call last):
  File "/usr/local/greenplum-db-devel/bin/gpexpand", line 2795, in main
    _gp_expand.add_segments()
  File "/usr/local/greenplum-db-devel/bin/gpexpand", line 1345, in add_segments
    self.segTemplate.build_segment_template()
  File "/usr/local/greenplum-db-devel/bin/gpexpand", line 688, in build_segment_template
    self._create_template()
  File "/usr/local/greenplum-db-devel/bin/gpexpand", line 707, in _create_template
    catalog.vacuum_catalog(self.dburl, self.conn, full=True, utility=True)
  File "/usr/local/greenplum-db-devel/lib/python/gppylib/db/catalog.py", line 132, in vacuum_catalog
    vac_curs.execute(sql)
  File "/usr/local/greenplum-db-devel/lib/python/pygresql/pgdb.py", line 259, in execute
    self.executemany(operation, (params,))
  File "/usr/local/greenplum-db-devel/lib/python/pygresql/pgdb.py", line 289, in executemany
    raise DatabaseError("error '%s' in '%s'" % (msg, sql))
DatabaseError: error 'ERROR:  updated tuple is already HEAP_MOVED_OFF (vacuum.c:3906)
' in 'VACUUM FULL pg_catalog.pg_stat_last_operation'
```

I don't know why we're suddenly seeing this on the `walreplication` branch, and not on master, but I was able to reproduce this on `master` too, with the attached script.
[updated-tuple-is-already-HEAP_MOVED_OFF-repro.sql.txt](https://github.com/greenplum-db/gpdb/files/1623546/updated-tuple-is-already-HEAP_MOVED_OFF-repro.sql.txt)

**Comment by hlinnaka** [comment]
Reproducible on 5X_STABLE as well.

**Comment by ashwinstar** [comment]
Thank You @hlinnaka for the repro. It made the debugging so simple with it. The issue can happen in utility mode vacuum and also regular distributed vacuum, just is little bit more tricky to repro that scenario.

Below patch fixes the problem. It's basically `repair_frag()` is making the check for movement of tuples during vacuum based on comparing `xmin` with `OldestXmin`. Its coded with assumption that if based on `xmax` tuple was claimed as `RECENTLY_DEAD`, then its perfectly fine to check just `xmins` in chain with `OldestXmin` as for update case `xmax` of deleting tuple has to be `xmin` of inserting tuple.

Which is perfectly fine but this assumption got broken with distributed snapshot usage by vacuum as now even if both `xmin` and `xmax` are lower than `OldestXmin`, we can still return `RECENTLY_DEAD` based on distributed snapshot. So, later distributed snapshot must be consulted for movement of tuples when checking `xmax` and just comparing with `OldestXmin` is not enough.

```
diff --git a/src/backend/commands/vacuum.c b/src/backend/commands/vacuum.c
index c42f85e0f9..d122b92f2d 100644
--- a/src/backend/commands/vacuum.c
+++ b/src/backend/commands/vacuum.c
@@ -3793,8 +3793,9 @@ repair_frag(VRelStats *vacrelstats, Relation onerel,
                         * separately movable chain, ignoring any intervening DEAD ones.
                         */
                        if (((tuple.t_data->t_infomask & HEAP_UPDATED) &&
-                                !TransactionIdPrecedes(HeapTupleHeaderGetXmin(tuple.t_data),
-                                                                               OldestXmin)) ||
+                                (!TransactionIdPrecedes(HeapTupleHeaderGetXmin(tuple.t_data),
+                                                                                OldestXmin) ||
+                                 localXidSatisfiesAnyDistributedSnapshot(HeapTupleHeaderGetXmin(tuple.t_data)))) ||
                                (!(tuple.t_data->t_infomask & (HEAP_XMAX_INVALID |
                                                                                           HEAP_IS_LOCKED)) &&
                                 !(ItemPointerEquals(&(tuple.t_self),
@@ -3982,8 +3983,9 @@ repair_frag(VRelStats *vacrelstats, Relation onerel,

                                        /* Done if at beginning of chain */
                                        if (!(tp.t_data->t_infomask & HEAP_UPDATED) ||
-                                        TransactionIdPrecedes(HeapTupleHeaderGetXmin(tp.t_data),
-                                                                                  OldestXmin))
+                                               (TransactionIdPrecedes(HeapTupleHeaderGetXmin(tp.t_data),
+                                                                                          OldestXmin) &&
+                                                !localXidSatisfiesAnyDistributedSnapshot(HeapTupleHeaderGetXmin(tp.t_data))))
                                                break;  /* out of check-all-items loop */

                                        /* Move to tuple with prior row version */
```

This problem existed since commit introducing usage of distributed snapshots for vacuum in 5.X and master. 

Just a  note in recent master there are more places with latest merge where `OldestXmin` is being used not just for passing to `HeapTupleSatisfiesVacuum()` which needs to be looked into as well for example

```
./backend/access/heap/pruneheap.c:	if (!PageIsPrunable(page, OldestXmin))
./backend/commands/vacuumlazy.c:						if (!TransactionIdPrecedes(xmin, OldestXmin))
```

Will open PR soon to fix all of this.
