### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by renyi1314** [greenplum-db/gpdb#4503]
When I execute this command：
gpinitsystem -c /home/gpadmin/conf/gpinitsystem_config –a
and this is fllowed messages：

20180207:10:18:29:015263 gpstart:GPDB1:gpadmin-[ERROR]:-[Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/home/gpadmin/gpdb/lib/python/gppylib/commands/base.py", line 243, in run
    self.cmd.run()
  File "/home/gpadmin/gpdb/lib/python/gppylib/commands/base.py", line 711, in run
    self.exec_context.execute(self)
  File "/home/gpadmin/gpdb/lib/python/gppylib/commands/base.py", line 655, in execute
    LocalExecutionContext.execute(self, cmd)
  File "/home/gpadmin/gpdb/lib/python/gppylib/commands/base.py", line 433, in execute
    stdout=subprocess.PIPE, close_fds=True)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1224, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
20180207:10:18:29:015263 gpstart:GPDB1:gpadmin-[CRITICAL]:-gpstart failed. (Reason=''NoneType' object has no attribute 'rc'') exiting...

**Comment by lij55** [comment]
Could you try to append '-B 1' with your original command?

**Comment by shubifeng** [comment]
兄弟，问题解决了没有？
