### ISSUE TITLE
gpstop -u or gpstart  output Cannot allocate memory

### ISSUE THREAD

**Issue by shubifeng** [greenplum-db/gpdb#4558]
### Greenplum version or build
v5.4.1
### OS version and uname -a
centos 7.4

4GB memory  of segment 

`gpstop -u`
```
20180220:02:25:08:002854 gpstop:mdw:gpadmin-[INFO]:-Starting gpstop with args: -u
20180220:02:25:08:002854 gpstop:mdw:gpadmin-[INFO]:-Gathering information and validating the environment...
20180220:02:25:08:002854 gpstop:mdw:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20180220:02:25:08:002854 gpstop:mdw:gpadmin-[INFO]:-Obtaining Segment details from master...
20180220:02:25:09:002854 gpstop:mdw:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 5.4.1 build commit:4eb4d57ae59310522d53b5cce47aa505ed0d17d3'
20180220:02:25:09:002854 gpstop:mdw:gpadmin-[INFO]:-Signalling all postmaster processes to reload
20180220:02:25:09:002854 gpstop:mdw:gpadmin-[ERROR]:-[Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 243, in run
    self.cmd.run()
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 711, in run
    self.exec_context.execute(self)
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 655, in execute
    LocalExecutionContext.execute(self, cmd)
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 433, in execute
    stdout=subprocess.PIPE, close_fds=True)
  File "/usr/local/greenplum-db/ext/python/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/local/greenplum-db/ext/python/lib/python2.7/subprocess.py", line 1235, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
20180220:02:25:09:002854 gpstop:mdw:gpadmin-[ERROR]:-[Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 243, in run
    self.cmd.run()
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 711, in run
    self.exec_context.execute(self)
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 655, in execute
    LocalExecutionContext.execute(self, cmd)
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 433, in execute
    stdout=subprocess.PIPE, close_fds=True)
  File "/usr/local/greenplum-db/ext/python/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/local/greenplum-db/ext/python/lib/python2.7/subprocess.py", line 1235, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
20180220:02:25:09:002854 gpstop:mdw:gpadmin-[ERROR]:-[Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 243, in run
    self.cmd.run()
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 711, in run
    self.exec_context.execute(self)
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 655, in execute
    LocalExecutionContext.execute(self, cmd)
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 433, in execute
    stdout=subprocess.PIPE, close_fds=True)
  File "/usr/local/greenplum-db/ext/python/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/local/greenplum-db/ext/python/lib/python2.7/subprocess.py", line 1235, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
20180220:02:25:10:002854 gpstop:mdw:gpadmin-[CRITICAL]:-gpstop failed. (Reason=''NoneType' object has no attribute 'wasSuccessful'') exiting...






```

**Comment by shubifeng** [comment]
this solution :  https://discuss.pivotal.io/hc/en-us/articles/201947018-Pivotal-Greenplum-GPDB-Memory-Configuration
