### ISSUE TITLE
pg-jdbc 9.4

### ISSUE THREAD

**Issue by livingluck** [greenplum-db/gpdb#5356]
### Expected behavior

print proper information.

### Actual behavior

org.postgresql.util.PSQLException: ERROR: deadlock detected
  详细：Process 23946 waits for ExclusiveLock on relation 17376 of database 17370; blocked by process 23945.
Process 23945 waits for ExclusiveLock on relation 17376 of database 17370; blocked by process 23946.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2161)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1890)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:559)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:403)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:331)
	at testHiveinJava.testLongData.testexcute(testLongData.java:141)
	at testHiveinJava.testLongData.run(testLongData.java:116)

### Step to reproduce the behavior
1、create connection betwee Greenplum(Database jdbc Driver use pg-jdbc 9.4)
2、create 10 thread to execute insert statement.  
3、java propgram went wrong. Error is occurred  where output is shown as described above.

**Comment by hlinnaka** [comment]
Looks like you have a deadlock in your database. Perhaps you had transactions updating multiple tables, in different order?

In any case, this doesn't seem to be an issue with the server or the JDBC driver, but the application. I'll close the issue, but feel free to open a new one with more details, or post to the gpdb-users mailing list (https://greenplum.org/mailing-lists/), if you want to discuss this further.
