### ISSUE TITLE
Query fails for default resource group but not for admin resource group

### ISSUE THREAD

**Issue by kaknikhil** [greenplum-db/gpdb#6349]
When resource groups are enabled and the query is run within a newly created postgres user with the default resource group, sometimes we encounter this exception `ERROR:  insufficient memory reserved for statement`

### Greenplum version or build
```
PostgreSQL 8.3.23 (Greenplum Database 5.13.0+dev.30.gc2f693f build dev) on x86_64-pc-linux-gnu, compiled by GCC gcc (Ubuntu 6.5.0-1ubuntu1~16.04) 6.5.0 20181026, 64-bit compiled on Nov 23 2018 11:10:51
```

### Step to reproduce the behavior
1. Enable resource groups https://gpdb.docs.pivotal.io/530/admin_guide/workload_mgmt_resgroups.html
1. Run the following query
```
gpadmin:~$ createdb test
gpadmin:~$ psql test
psql (8.3.23)
DROP TABLE IF EXISTS vertex, edge;
drop user if exists test_user;
create user test_user;
NOTICE:  resource group required -- using default resource group "default_group"
GRANT ALL PRIVILEGES  on schema public TO test_user;
SET ROLE test_user;

CREATE TABLE vertex(
        id INTEGER,
        name TEXT
        );
CREATE TABLE edge(
        src INTEGER,
        dest INTEGER,
        weight FLOAT8
        );
INSERT INTO vertex VALUES
(0, 'A'),
(1, 'B');

INSERT INTO edge VALUES
(0, 1, 1.0);

DROP TABLE IF EXISTS out_degrees;
CREATE TABLE out_degrees AS
SELECT
coalesce(in_q.vertex, out_q.vertex) as id,
coalesce(indegree, 0) as indegree,
coalesce(outdegree, 0) as outdegree
FROM
(
SELECT

    dest as vertex,
    count(*) as indegree
FROM edge
WHERE src != dest AND
      src IS NOT NULL AND
      dest IS NOT NULL
GROUP BY
         dest
) as in_q
FULL OUTER JOIN
(
SELECT

    src as vertex,
    count(*) as outdegree
FROM edge
WHERE src != dest AND
      src IS NOT NULL AND
      dest IS NOT NULL
GROUP BY
         src
) as out_q
USING ( vertex);
ERROR:  insufficient memory reserved for statement
```

Running the same query without setting the `test_user` role uses the `admin_group` resource group which goes through just fine. The `default_group` resource group has more resources than the `admin_group` resource group, so it doesn't make sense that the query fails when running in the `default_group` and not when running in `admin_group`.

 Increasing the memory_limit to 70 for `default_group` makes it work but that's just a workaround.

**Comment by kaknikhil** [comment]
Another way to repro this is to change the resource group of the default superuser from `admin_group` to `default_group`.
```
ALTER ROLE gpadmin  resource group default_group;
```

**Comment by gaos1** [comment]
could you share your complete settings for default and admin group by the following commands?  single query memory quota can be calculated roughly by group memory limit divided by group concurrency. 

```
\x
select * from gp_toolkit.gp_resgroup_config;
```

**Comment by goutamtadi1** [comment]
On a container, we see

```
gpadmin=# select * from gp_toolkit.gp_resgroup_config;
 groupid |   groupname   | concurrency | proposed_concurrency | cpu_rate_limit | memory_limit | proposed_memory_limit | memory_shared_quota | proposed_memor
y_shared_quota | memory_spill_ratio | proposed_memory_spill_ratio
---------+---------------+-------------+----------------------+----------------+--------------+-----------------------+---------------------+---------------
---------------+--------------------+-----------------------------
    6437 | default_group | 20          | 20                   | 30             | 30           | 30                    | 50                  | 50
               | 20                 | 20
    6438 | admin_group   | 10          | 10                   | 10             | 10           | 10                    | 50                  | 50
               | 20                 | 20
(2 rows)
```

**Comment by pivotal-ning-yu** [comment]
Thanks for the report, I can reproduce the issue with @kaknikhil 's reproducer by using the admin_group. It happens when ORCA is on only.

By converting this error report to an assert we got below information with gdb:

```gdb
(gdb) bt
#0  0x00007f6359f04f97 in __GI___select (nfds=0, readfds=0x0, writefds=0x0, exceptfds=0x0, timeout=0x7ffc62f37560) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x0000563953e77b72 in pg_usleep (microsec=30000000) at pgsleep.c:43
#2  0x0000563953c72739 in elog_debug_linger (edata=0x56395425a000 <errordata>) at elog.c:4342
#3  0x0000563953c6994a in errfinish (dummy=0) at elog.c:616
#4  0x0000563953c67fad in ExceptionalCondition (conditionName=0x56395407f710 "!(!\"insufficient memory reserved for statement\")", errorType=0x56395407f38b "FailedAssertion",
    fileName=0x56395407f380 "memquota.c", lineNumber=1022) at assert.c:49
#5  0x0000563953cf7d3e in PolicyEagerFreeAssignOperatorMemoryKB (stmt=0x563956741240, memAvailableBytes=1048576) at memquota.c:1022
#6  0x00005639538fa74b in ExecutorStart (queryDesc=0x563955b73100, eflags=0) at execMain.c:312
#7  0x0000563953b22f22 in ProcessQuery (portal=0x563955991d20, stmt=0x563956741240, params=0x0, dest=0x5639567539f0, completionTag=0x7ffc62f37d40 "") at pquery.c:291
#8  0x0000563953b24f40 in PortalRunMulti (portal=0x563955991d20, isTopLevel=1 '\001', dest=0x5639567539f0, altdest=0x5639567539f0, completionTag=0x7ffc62f37d40 "") at pquery.c:1463
#9  0x0000563953b243ca in PortalRun (portal=0x563955991d20, count=9223372036854775807, isTopLevel=1 '\001', dest=0x5639567539f0, altdest=0x5639567539f0, completionTag=0x7ffc62f37d40 "") at pquery.c:1025
#10 0x0000563953b1bc1e in exec_simple_query (
    query_string=0x56395598dce0 "CREATE TABLE out_degrees AS\nSELECT\ncoalesce(in_q.vertex, out_q.vertex) as id,\ncoalesce(indegree, 0) as indegree,\ncoalesce(outdegree, 0) as outdegree\nFROM\n(\nSELECT\n    dest as vertex,\n    count(*) as i"..., seqServerHost=0x0, seqServerPort=-1) at postgres.c:1776
#11 0x0000563953b20eb1 in PostgresMain (argc=1, argv=0x563955808998, dbname=0x5639558087d8 "u", username=0x563955808798 "u") at postgres.c:4962
#12 0x0000563953aab51c in BackendRun (port=0x5639558107d0) at postmaster.c:6732
#13 0x0000563953aaaaa2 in BackendStartup (port=0x5639558107d0) at postmaster.c:6406
#14 0x0000563953aa2e02 in ServerLoop () at postmaster.c:2444
#15 0x0000563953aa13f5 in PostmasterMain (argc=15, argv=0x5639557df7d0) at postmaster.c:1528
#16 0x00005639539aac7b in main (argc=15, argv=0x5639557df7d0) at main.c:206

(gdb) f 5
#5  0x0000563953cf7d3e in PolicyEagerFreeAssignOperatorMemoryKB (stmt=0x563956741240, memAvailableBytes=1048576) at memquota.c:1022
1022    Assert(!"insufficient memory reserved for statement");

(gdb) l -
1017             * Check if memory exceeds the limit in the root group
1018             */
1019            const uint64 nonMemIntenseOpMemKB = (uint64)(*gp_resmanager_memory_policy_auto_fixed_mem);
1020            if (ctx.groupTree->groupMemKB < ctx.groupTree->numNonMemIntenseOps * nonMemIntenseOpMemKB)
1021            {
1022    Assert(!"insufficient memory reserved for statement");
1023                    ereport(ERROR,
1024                            (errcode(ERRCODE_INSUFFICIENT_RESOURCES),
1025                            errmsg("insufficient memory reserved for statement")));
1026            }

(gdb) p ctx.groupTree->groupMemKB
$9 = 1024

(gdb) p ctx.groupTree->numNonMemIntenseOps
$10 = 13

(gdb) p nonMemIntenseOpMemKB
$11 = 100
```

We can see that this plan contains 13 non-memory-intense operators, 1024 < 13 * 100.  The value 1024 is decided by the group's spill ratio, in my environment the master is granted 879MB in all, so the admin_group has 879M * 10% = 87M memory, each concurrent has 87M * 50% / 10 = 4.35MB, the spill ratio is 20%, so 4.35MB * 20% = 0.87MB.  To run the query successfully we can increase the spill ratio slightly, e.g.

```sql
-- set at session level
set memory_spill_ratio to 40;

-- or set at resgroup level
alter resource group admin_group set memory_spill_ratio 40;
```

**Comment by pivotal-ning-yu** [comment]
Discussed with @gaos1 , we think one improvement is to relax the spill memory check, when the spill memory is too low instead of raising an error a better choice is to increase spill memory slightly.  By doing so the query could run successfully if there is enough shared memory (this is usually the case), and will only fail at execution time when the shared memory is also too low.  I'll work on a PR for this change.
