### ISSUE TITLE
VACUUM FULL causes assertion failure on newly-inited database

### ISSUE THREAD

**Issue by jmcatamney** [greenplum-db/gpdb#6362]
### Greenplum version or build

Master HEAD (commit 909d47d74c20be3501e06592ca41a43ded60d6f7)

### OS version and uname -a

Repro'd on Centos 7 and Ubuntu 18.10

### Configure options used

'--enable-cassert' '--enable-debug' 'CFLAGS=-O0' 'CPPFLAGS=-O0'

### Observed behavior

Immediately after creating a cluster with gpinitsystem, connecting with `psql postgres` and running `VACUUM FULL` results in the following assertion failure:

```
FATAL:  Unexpected internal error (indexam.c:215)
DETAIL:  FailedAssertion("!(!ReindexIsProcessingIndex(((indexRelation)->rd_id)))", File: "indexam.c", Line: 215)
HINT:  Process 3873 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
```
Attaching to the process using `gdb` results in the following backtrace:
```
(gdb) bt
#0  0x00007f02f5189783 in __select_nocancel () from /lib64/libc.so.6
#1  0x0000000000be76ef in pg_usleep (microsec=30000000) at pgsleep.c:53
#2  0x0000000000ad75aa in elog_debug_linger (edata=0x11bf760 <errordata>) at elog.c:5293
#3  0x0000000000acdba4 in errfinish (dummy=0) at elog.c:675
#4  0x0000000000acc3bf in ExceptionalCondition (conditionName=0xc15798 "!(!ReindexIsProcessingIndex(((indexRelation)->rd_id)))", errorType=0xc156ef "FailedAssertion", 
    fileName=0xc156d0 "indexam.c", lineNumber=215) at assert.c:46
#5  0x00000000004fded5 in index_insert (indexRelation=0x7f02f6b6daa0, values=0x7ffdb43915e0, isnull=0x7ffdb43915c0 "", heap_t_ctid=0x240bd64, heapRelation=0x24efa78, 
    checkUnique=UNIQUE_CHECK_YES) at indexam.c:215
#6  0x00000000005bda59 in CatalogIndexInsert (indstate=0x240e5d0, heapTuple=0x240bd60) at indexing.c:136
#7  0x00000000005bdaaa in CatalogUpdateIndexes (heapRel=0x24efa78, heapTuple=0x240bd60) at indexing.c:162
#8  0x00000000005b2203 in MetaTrackAddUpdInternal (classid=1259, objoid=6053, relowner=10, actionname=0xc51543 "VACUUM", subtype=0xc5153b "REINDEX", rel=0x24efa78, 
    old_tuple=0x0) at heap.c:744
#9  0x00000000005b229d in MetaTrackAddObject (classid=1259, objoid=6053, relowner=10, actionname=0xc51543 "VACUUM", subtype=0xc5153b "REINDEX") at heap.c:773
#10 0x00000000005b2553 in MetaTrackUpdObject (classid=1259, objoid=6053, relowner=10, actionname=0xc51543 "VACUUM", subtype=0xc5153b "REINDEX") at heap.c:856
#11 0x00000000005bd271 in reindex_index (indexId=6053, skip_constraint_checks=1 '\001') at index.c:3741
#12 0x00000000005bd418 in reindex_relation (relid=6052, flags=2) at index.c:3870
#13 0x000000000067ba71 in finish_heap_swap (OIDOldHeap=6052, OIDNewHeap=16687, is_system_catalog=1 '\001', swap_toast_by_content=0 '\000', swap_stats=1 '\001', 
    check_constraints=0 '\000', is_internal=1 '\001', frozenXid=821, cutoffMulti=1) at cluster.c:1667
#14 0x0000000000679ed5 in rebuild_relation (OldHeap=0x7f02f6b7a6f0, indexOid=0, verbose=0 '\000') at cluster.c:648
#15 0x0000000000679913 in cluster_rel (tableOid=6052, indexOid=0, recheck=0 '\000', verbose=0 '\000', printError=1 '\001') at cluster.c:461
#16 0x0000000000717580 in vacuum_rel (onerel=0x0, relid=6052, vacstmt=0x2533c38, lmode=8, for_wraparound=0 '\000') at vacuum.c:2315
#17 0x0000000000714ce7 in vacuumStatement_Relation (vacstmt=0x2533c38, relid=6052, relations=0x24c12f8, bstrategy=0x24c1220, do_toast=1 '\001', for_wraparound=0 '\000', 
    isTopLevel=1 '\001') at vacuum.c:787
#18 0x0000000000714303 in vacuum (vacstmt=0x2403260, relid=0, do_toast=1 '\001', bstrategy=0x24c1220, for_wraparound=0 '\000', isTopLevel=1 '\001') at vacuum.c:337
#19 0x0000000000969cd2 in standard_ProcessUtility (parsetree=0x2403260, queryString=0x24027e0 "vacuum full;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, dest=0x2403648, 
    completionTag=0x7ffdb4392550 "") at utility.c:804
#20 0x00000000009691be in ProcessUtility (parsetree=0x2403260, queryString=0x24027e0 "vacuum full;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, dest=0x2403648, 
    completionTag=0x7ffdb4392550 "") at utility.c:373
#21 0x0000000000967ed5 in PortalRunUtility (portal=0x249b8c0, utilityStmt=0x2403260, isTopLevel=1 '\001', dest=0x2403648, completionTag=0x7ffdb4392550 "") at pquery.c:1377
#22 0x000000000096817a in PortalRunMulti (portal=0x249b8c0, isTopLevel=1 '\001', dest=0x2403648, altdest=0x2403648, completionTag=0x7ffdb4392550 "") at pquery.c:1508
#23 0x000000000096765d in PortalRun (portal=0x249b8c0, count=9223372036854775807, isTopLevel=1 '\001', dest=0x2403648, altdest=0x2403648, completionTag=0x7ffdb4392550 "")
    at pquery.c:1014
#24 0x000000000095fab2 in exec_simple_query (query_string=0x24027e0 "vacuum full;") at postgres.c:1813
#25 0x0000000000964908 in PostgresMain (argc=1, argv=0x23e20a0, dbname=0x23e1ec8 "postgres", username=0x23e1ea8 "jamie") at postgres.c:5256
#26 0x00000000008d531d in BackendRun (port=0x2409690) at postmaster.c:4749
#27 0x00000000008d4a06 in BackendStartup (port=0x2409690) at postmaster.c:4411
#28 0x00000000008d07fd in ServerLoop () at postmaster.c:1860
#29 0x00000000008cfd37 in PostmasterMain (argc=11, argv=0x23dfd80) at postmaster.c:1448
#30 0x00000000007cbc5f in main (argc=11, argv=0x23dfd80) at main.c:239
```
The failing relation (oid 6052) is `pg_stat_last_operation`.

**Comment by hlinnaka** [comment]
Fixed by commit de0edeac4b. Thanks for the report!
