### ISSUE TITLE
PXF External Table Hive 3.1 failed with java.io.IOException: Not a file

### ISSUE THREAD

**Issue by timofreenet** [greenplum-db/gpdb#7023]
### HDP 3.1 / Hive 3.1
Hive:
CREATE TABLE sales_info (location string, month string, number_of_orders int, total_sales double)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS textfile;

select * from sales_info;
+----------------------+-------------------+------------------------------+-------------------------+
| sales_info.location  | sales_info.month  | sales_info.number_of_orders  | sales_info.total_sales  |
+----------------------+-------------------+------------------------------+-------------------------+
| Prague               | Jan               | 101                          | 4875.33                 |
| Rome                 | Mar               | 87                           | 1557.39                 |
| Bangalore            | May               | 317                          | 8936.99                 |
| Beijing              | Jul               | 411                          | 11600.67                |
| San Francisco        | Sept              | 156                          | 6846.34                 |
| Paris                | Nov               | 159                          | 7134.56                 |
| San Francisco        | Jan               | 113                          | 5397.89                 |
| Prague               | Dec               | 333                          | 9894.77                 |
| Bangalore            | Jul               | 271                          | 8320.55                 |
| Beijing              | Dec               | 100                          | 4248.41                 |
+----------------------+-------------------+------------------------------+-------------------------+
Greenplum:
CREATE EXTERNAL TABLE salesinfo_hivetextprofile(location text, month text, num_orders int, total_sales float8)
LOCATION ('pxf://default.sales_info?PROFILE=HiveText&DELIMITER=\x2c')
FORMAT 'TEXT' (delimiter=E',');

select * from salesinfo_hivetextprofile;                                                                                                                            ERROR:  remote component error (500) from '127.0.0.1:5888':  type  Exception report   message   javax.servlet.ServletException: java.io.IOException: Not a file: hdfs://hdm1-t.aq3hcc40qdkurot1542u4kjxfd.ax.internal.cloudapp.net:8020/warehouse/tablespace/managed/hive/sales_info/delta_0000001_0000001_0000    description   The server encountered an internal error that prevented it from fulfilling this request.    exception   javax.servlet.ServletException: javax.servlet.ServletException: java.io.IOException: Not a file: hdfs://hdm1-t.aq3hcc40qdkurot1542u4kjxfd.ax.internal.cloudapp.net:8020/warehouse/tablespace/managed/hive/sales_info/delta_0000001_0000001_0000 (libchurl.c:944)  (seg0 slice1 172.16.0.7:6000 pid=52329) (cdbdisp.c:254)
DETAIL:  External table salesinfo_hivetextprofile, file pxf://default.sales_info?PROFILE=HiveText&DELIMITER=\x2c

**Comment by timofreenet** [comment]
Feb 20, 2019 2:46:54 PM com.sun.jersey.spi.container.ContainerResponse mapMappableContainerException
SEVERE: The exception contained within MappableContainerException could not be mapped to a response, re-throwing to the HTTP container
java.io.IOException: Not a file: hdfs://hdm1-t.aq3hcc40qdkurot1542u4kjxfd.ax.internal.cloudapp.net:8020/warehouse/tablespace/managed/hive/sales_info/delta_0000001_0000001_0000
        at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:329)
        at org.greenplum.pxf.plugins.hive.HiveDataFragmenter.fetchMetaData(HiveDataFragmenter.java:302)
        at org.greenplum.pxf.plugins.hive.HiveDataFragmenter.fetchMetaDataForSimpleTable(HiveDataFragmenter.java:263)
        at org.greenplum.pxf.plugins.hive.HiveDataFragmenter.fetchMetaDataForSimpleTable(HiveDataFragmenter.java:257)
        at org.greenplum.pxf.plugins.hive.HiveDataFragmenter.fetchTableMetaData(HiveDataFragmenter.java:229)
        at org.greenplum.pxf.plugins.hive.HiveDataFragmenter.getFragments(HiveDataFragmenter.java:124)
        at org.greenplum.pxf.service.rest.FragmenterResource.getFragments(FragmenterResource.java:92)
        at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.greenplum.pxf.service.servlet.SecurityServletFilter.lambda$doFilter$0(SecurityServletFilter.java:105)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
        at org.greenplum.pxf.service.servlet.SecurityServletFilter.doFilter(SecurityServletFilter.java:120)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Comment by kongyew** [comment]
PXF does NOT support HIVE 2.x or 3.x .  This is a feature enhancement request.

**Comment by timofreenet** [comment]
The support of the currently used standard Hive versions provides a fundamentally necessary functionality.
The Hortonworks HDP 2.5 support will be discontinued mid-year and HDP 2.6 by the end of the year. Thus there is no support for Hive 1.x and Hive 2.x at the end of the year.
Therefore, the support of Hive 3.x within PXF should be prioritized accordingly.

Von: "Kong Yew, Chan" <notifications@github.com>
Antworten an: greenplum-db/gpdb <reply@reply.github.com>
Datum: Donnerstag, 21. Februar 2019 um 17:52
An: greenplum-db/gpdb <gpdb@noreply.github.com>
Cc: Timo Burmeister <Timo.Burmeister@freenet.ag>, Author <author@noreply.github.com>
Betreff: Re: [greenplum-db/gpdb] PXF External Table Hive 3.1 failed with java.io.IOException: Not a file (#7023)


PXF does NOT support HIVE 2.x or 3.x . This is a feature enhancement request.

**Comment by lij55** [comment]
closing this duplicated issue: https://github.com/greenplum-db/pxf/issues/97
