### ISSUE TITLE
gpinitsystem error in docker warm mode

### ISSUE THREAD

**Issue by kebyn** [greenplum-db/gpdb#8510]
### Greenplum version or build
```
5.21.2 build 610b6d7-oss
```
### OS version and uname -a
```
docker version
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:57:09 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
```
docker images
Linux greenplum_master1 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 x86_64 x86_64 GNU/Linux
```
### Installation information ( pg_config )
```
cat gpinitsystem_config
ARRAY_NAME="Greenplum Data Platform"

SEG_PREFIX=gpseg

PORT_BASE=6000

declare -a DATA_DIRECTORY=(/data1/primary /data2/primary)

MASTER_HOSTNAME=greenplum_master1

MASTER_DIRECTORY=/data/master

MASTER_PORT=5432

TRUSTED_SHELL=ssh

CHECK_POINT_SEGMENTS=8

ENCODING=UNICODE

MIRROR_PORT_BASE=7000

REPLICATION_PORT_BASE=8000

MIRROR_REPLICATION_PORT_BASE=9000

declare -a MIRROR_DATA_DIRECTORY=(/data1/mirror /data2/mirror)
```
### Step to reproduce the behavior
```
20190827:10:57:17:029016 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Start Function BACKOUT_COMMAND
20190827:10:57:17:028955 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Copying data for mirror on greenplum_segments1 using remote copy from primary greenplum_master1 ...
20190827:10:57:17:028969 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Start Function BACKOUT_COMMAND
20190827:10:57:17:029016 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-End Function BACKOUT_COMMAND
20190827:10:57:17:028989 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Start Function BACKOUT_COMMAND
20190827:10:57:17:029016 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Start Function BACKOUT_COMMAND
20190827:10:57:17:028955 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Start Function RUN_COMMAND_REMOTE
20190827:10:57:17:028969 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-End Function BACKOUT_COMMAND
20190827:10:57:17:028955 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Commencing remote /usr/bin/ssh greenplum_master1 export GPHOME=/opt/gpdb; . /opt/gpdb/greenplum_path.sh; /opt/gpdb/bin/lib/pysync.py -x pg_log -x postgresql.conf -x postmaster.pid /data1/primary/gpseg0 \[greenplum_segments1\]:/data1/mirror/gpseg0
20190827:10:57:17:028989 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-End Function BACKOUT_COMMAND
20190827:10:57:17:029016 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-End Function BACKOUT_COMMAND
20190827:10:57:17:028969 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Start Function BACKOUT_COMMAND
20190827:10:57:17:028989 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Start Function BACKOUT_COMMAND
20190827:10:57:17:029016 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO][3]:-Completed to start segment instance database greenplum_master1 /data2/mirror/gpseg3
20190827:10:57:17:028969 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-End Function BACKOUT_COMMAND
20190827:10:57:17:028969 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO][1]:-Completed to start segment instance database greenplum_segments2 /data2/mirror/gpseg1
20190827:10:57:17:028989 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-End Function BACKOUT_COMMAND
20190827:10:57:17:029016 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Copying data for mirror on greenplum_master1 using remote copy from primary greenplum_segments1 ...
20190827:10:57:17:028969 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Copying data for mirror on greenplum_segments2 using remote copy from primary greenplum_master1 ...
20190827:10:57:17:028989 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO][2]:-Completed to start segment instance database greenplum_segments2 /data1/mirror/gpseg2
20190827:10:57:17:029016 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Start Function RUN_COMMAND_REMOTE
20190827:10:57:17:028989 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Copying data for mirror on greenplum_segments2 using remote copy from primary greenplum_segments1 ...
20190827:10:57:17:029050 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Start Function BACKOUT_COMMAND
20190827:10:57:17:028969 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Start Function RUN_COMMAND_REMOTE
20190827:10:57:17:029016 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Commencing remote /usr/bin/ssh greenplum_segments1 export GPHOME=/opt/gpdb; . /opt/gpdb/greenplum_path.sh; /opt/gpdb/bin/lib/pysync.py -x pg_log -x postgresql.conf -x postmaster.pid /data2/primary/gpseg3 \[greenplum_master1\]:/data2/mirror/gpseg3
20190827:10:57:17:028989 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Start Function RUN_COMMAND_REMOTE
20190827:10:57:17:029050 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-End Function BACKOUT_COMMAND
20190827:10:57:17:028969 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Commencing remote /usr/bin/ssh greenplum_master1 export GPHOME=/opt/gpdb; . /opt/gpdb/greenplum_path.sh; /opt/gpdb/bin/lib/pysync.py -x pg_log -x postgresql.conf -x postmaster.pid /data2/primary/gpseg1 \[greenplum_segments2\]:/data2/mirror/gpseg1
20190827:10:57:17:028989 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Commencing remote /usr/bin/ssh greenplum_segments1 export GPHOME=/opt/gpdb; . /opt/gpdb/greenplum_path.sh; /opt/gpdb/bin/lib/pysync.py -x pg_log -x postgresql.conf -x postmaster.pid /data1/primary/gpseg2 \[greenplum_segments2\]:/data1/mirror/gpseg2
20190827:10:57:17:029050 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Start Function BACKOUT_COMMAND
20190827:10:57:17:029050 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-End Function BACKOUT_COMMAND
20190827:10:57:17:029050 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO][4]:-Completed to start segment instance database greenplum_master1 /data1/mirror/gpseg4
20190827:10:57:17:029082 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Start Function BACKOUT_COMMAND
20190827:10:57:17:029050 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Copying data for mirror on greenplum_master1 using remote copy from primary greenplum_segments2 ...
20190827:10:57:17:029050 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Start Function RUN_COMMAND_REMOTE
20190827:10:57:17:029082 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-End Function BACKOUT_COMMAND
20190827:10:57:17:029050 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Commencing remote /usr/bin/ssh greenplum_segments2 export GPHOME=/opt/gpdb; . /opt/gpdb/greenplum_path.sh; /opt/gpdb/bin/lib/pysync.py -x pg_log -x postgresql.conf -x postmaster.pid /data1/primary/gpseg4 \[greenplum_master1\]:/data1/mirror/gpseg4
20190827:10:57:17:029082 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Start Function BACKOUT_COMMAND
20190827:10:57:17:029082 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-End Function BACKOUT_COMMAND
20190827:10:57:17:029082 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO][5]:-Completed to start segment instance database greenplum_segments1 /data2/mirror/gpseg5
20190827:10:57:17:029082 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Copying data for mirror on greenplum_segments1 using remote copy from primary greenplum_segments2 ...
20190827:10:57:17:029082 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Start Function RUN_COMMAND_REMOTE
20190827:10:57:17:029082 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-Commencing remote /usr/bin/ssh greenplum_segments2 export GPHOME=/opt/gpdb; . /opt/gpdb/greenplum_path.sh; /opt/gpdb/bin/lib/pysync.py -x pg_log -x postgresql.conf -x postmaster.pid /data2/primary/gpseg5 \[greenplum_segments1\]:/data2/mirror/gpseg5
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "<string>", line 788, in <module>
  File "<string>", line 778, in run
  File "<string>", line 711, in copyData
  File "<string>", line 636, in getData
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "<string>", line 788, in <module>
  File "<string>", line 778, in run
  File "<string>", line 711, in copyData
  File "<string>", line 636, in getData
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "<string>", line 788, in <module>
  File "<string>", line 778, in run
  File "<string>", line 711, in copyData
  File "<string>", line 636, in getData
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
[FATAL]:-Unexpected EOF on RemotePysync output stream
Exception in thread ProgressTimer (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "<string>", line 421, in run
  File "<string>", line 316, in _emitProgress
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'copy'
[FATAL]:-Unexpected EOF on RemotePysync output stream
[FATAL]:-Unexpected EOF on RemotePysync output stream
20190827:10:57:19:029082 gpcreateseg.sh:greenplum_master1:gpadmin-[FATAL]:- Command export GPHOME=/opt/gpdb; . /opt/gpdb/greenplum_path.sh; /opt/gpdb/bin/lib/pysync.py -x pg_log -x postgresql.conf -x postmaster.pid /data2/primary/gpseg5 \[greenplum_segments1\]:/data2/mirror/gpseg5 on greenplum_segments2 failed with error status 3
20190827:10:57:19:029082 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-End Function RUN_COMMAND_REMOTE
20190827:10:57:19:028989 gpcreateseg.sh:greenplum_master1:gpadmin-[FATAL]:- Command export GPHOME=/opt/gpdb; . /opt/gpdb/greenplum_path.sh; /opt/gpdb/bin/lib/pysync.py -x pg_log -x postgresql.conf -x postmaster.pid /data1/primary/gpseg2 \[greenplum_segments2\]:/data1/mirror/gpseg2 on greenplum_segments1 failed with error status 3
20190827:10:57:19:029016 gpcreateseg.sh:greenplum_master1:gpadmin-[FATAL]:- Command export GPHOME=/opt/gpdb; . /opt/gpdb/greenplum_path.sh; /opt/gpdb/bin/lib/pysync.py -x pg_log -x postgresql.conf -x postmaster.pid /data2/primary/gpseg3 \[greenplum_master1\]:/data2/mirror/gpseg3 on greenplum_segments1 failed with error status 3
20190827:10:57:19:029082 gpcreateseg.sh:greenplum_master1:gpadmin-[FATAL][5]:-Failed remote copy of segment data directory from greenplum_segments2 to greenplum_segments1
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "<string>", line 788, in <module>
  File "<string>", line 778, in run
  File "<string>", line 711, in copyData
  File "<string>", line 636, in getData
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
20190827:10:57:19:028989 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-End Function RUN_COMMAND_REMOTE
[FATAL]:-Unexpected EOF on RemotePysync output stream
20190827:10:57:19:029016 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-End Function RUN_COMMAND_REMOTE
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "<string>", line 788, in <module>
  File "<string>", line 778, in run
  File "<string>", line 711, in copyData
  File "<string>", line 636, in getData
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
20190827:10:57:19:028989 gpcreateseg.sh:greenplum_master1:gpadmin-[FATAL][2]:-Failed remote copy of segment data directory from greenplum_segments1 to greenplum_segments2
[FATAL]:-Unexpected EOF on RemotePysync output stream
20190827:10:57:19:029016 gpcreateseg.sh:greenplum_master1:gpadmin-[FATAL][3]:-Failed remote copy of segment data directory from greenplum_segments1 to greenplum_master1
20190827:10:57:19:028955 gpcreateseg.sh:greenplum_master1:gpadmin-[FATAL]:- Command export GPHOME=/opt/gpdb; . /opt/gpdb/greenplum_path.sh; /opt/gpdb/bin/lib/pysync.py -x pg_log -x postgresql.conf -x postmaster.pid /data1/primary/gpseg0 \[greenplum_segments1\]:/data1/mirror/gpseg0 on greenplum_master1 failed with error status 3
20190827:10:57:19:028955 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-End Function RUN_COMMAND_REMOTE
20190827:10:57:19:028955 gpcreateseg.sh:greenplum_master1:gpadmin-[FATAL][0]:-Failed remote copy of segment data directory from greenplum_master1 to greenplum_segments1
20190827:10:57:19:029050 gpcreateseg.sh:greenplum_master1:gpadmin-[FATAL]:- Command export GPHOME=/opt/gpdb; . /opt/gpdb/greenplum_path.sh; /opt/gpdb/bin/lib/pysync.py -x pg_log -x postgresql.conf -x postmaster.pid /data1/primary/gpseg4 \[greenplum_master1\]:/data1/mirror/gpseg4 on greenplum_segments2 failed with error status 3
20190827:10:57:19:029050 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-End Function RUN_COMMAND_REMOTE
20190827:10:57:19:029050 gpcreateseg.sh:greenplum_master1:gpadmin-[FATAL][4]:-Failed remote copy of segment data directory from greenplum_segments2 to greenplum_master1
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "<string>", line 788, in <module>
  File "<string>", line 778, in run
  File "<string>", line 711, in copyData
  File "<string>", line 636, in getData
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
[FATAL]:-Unexpected EOF on RemotePysync output stream
20190827:10:57:19:028969 gpcreateseg.sh:greenplum_master1:gpadmin-[FATAL]:- Command export GPHOME=/opt/gpdb; . /opt/gpdb/greenplum_path.sh; /opt/gpdb/bin/lib/pysync.py -x pg_log -x postgresql.conf -x postmaster.pid /data2/primary/gpseg1 \[greenplum_segments2\]:/data2/mirror/gpseg1 on greenplum_master1 failed with error status 3
20190827:10:57:19:028969 gpcreateseg.sh:greenplum_master1:gpadmin-[INFO]:-End Function RUN_COMMAND_REMOTE
20190827:10:57:19:028969 gpcreateseg.sh:greenplum_master1:gpadmin-[FATAL][1]:-Failed remote copy of segment data directory from greenplum_master1 to greenplum_segments2
20190827:10:57:19:021913 gpinitsystem:greenplum_master1:gpadmin-[INFO]:-End Function PARALLEL_WAIT
20190827:10:57:19:021913 gpinitsystem:greenplum_master1:gpadmin-[INFO]:-End Function PARALLEL_COUNT
20190827:10:57:19:021913 gpinitsystem:greenplum_master1:gpadmin-[INFO]:-Start Function PARALLEL_SUMMARY_STATUS_REPORT
20190827:10:57:19:021913 gpinitsystem:greenplum_master1:gpadmin-[INFO]:------------------------------------------------
20190827:10:57:19:021913 gpinitsystem:greenplum_master1:gpadmin-[INFO]:-Parallel process exit status
20190827:10:57:19:021913 gpinitsystem:greenplum_master1:gpadmin-[INFO]:------------------------------------------------
20190827:10:57:19:021913 gpinitsystem:greenplum_master1:gpadmin-[INFO]:-Total processes marked as completed           = 0
20190827:10:57:19:021913 gpinitsystem:greenplum_master1:gpadmin-[INFO]:-Total processes marked as killed              = 0
20190827:10:57:19:021913 gpinitsystem:greenplum_master1:gpadmin-[WARN]:-Total processes marked as failed              = 6 <<<<<
20190827:10:57:19:021913 gpinitsystem:greenplum_master1:gpadmin-[INFO]:------------------------------------------------
20190827:10:57:19:021913 gpinitsystem:greenplum_master1:gpadmin-[INFO]:-End Function PARALLEL_SUMMARY_STATUS_REPORT
FAILED:greenplum_segments1~7001~/data2/mirror/gpseg5~13~5~9001
FAILED:greenplum_segments2~7000~/data1/mirror/gpseg2~10~2~9000
FAILED:greenplum_master1~7001~/data2/mirror/gpseg3~11~3~9001
FAILED:greenplum_segments1~7000~/data1/mirror/gpseg0~8~0~9000
FAILED:greenplum_master1~7000~/data1/mirror/gpseg4~12~4~9000
FAILED:greenplum_segments2~7001~/data2/mirror/gpseg1~9~1~9001
20190827:10:57:19:021913 gpinitsystem:greenplum_master1:gpadmin-[INFO]:-End Function CREATE_QES_MIRROR
INSERT 0 1
20190827:10:57:19:021913 gpinitsystem:greenplum_master1:gpadmin-[FATAL]:-Errors generated from parallel processes
20190827:10:57:19:021913 gpinitsystem:greenplum_master1:gpadmin-[INFO]:-Dumped contents of status file to the log file
20190827:10:57:19:021913 gpinitsystem:greenplum_master1:gpadmin-[INFO]:-Building composite backout file
20190827:10:57:19:021913 gpinitsystem:greenplum_master1:gpadmin-[INFO]:-Start Function ERROR_EXIT
20190827:10:57:19:gpinitsystem:greenplum_master1:gpadmin-[FATAL]:-Failures detected, see log file /opt/gpdb/gpAdminLogs/gpinitsystem_20190827.log for more detail Script Exiting!
20190827:10:57:19:021913 gpinitsystem:greenplum_master1:gpadmin-[WARN]:-Script has left Greenplum Database in an incomplete state
20190827:10:57:19:021913 gpinitsystem:greenplum_master1:gpadmin-[WARN]:-Run command /bin/bash /opt/gpdb/gpAdminLogs/backout_gpinitsystem_gpadmin_20190827_105415 to remove these changes
20190827:10:57:19:021913 gpinitsystem:greenplum_master1:gpadmin-[INFO]:-Start Function BACKOUT_COMMAND
20190827:10:57:19:021913 gpinitsystem:greenplum_master1:gpadmin-[INFO]:-End Function BACKOUT_COMMAND
```

**Comment by kebyn** [comment]
when I directly execute this error command, the content is as follows
```
gpadmin@greenplum_master1:~$ export GPHOME=/opt/gpdb; . /opt/gpdb/greenplum_path.sh; /opt/gpdb/bin/lib/pysync.py -x pg_log -x postgresql.conf -x postmaster.pid /data1/primary/gpseg0 \[greenplum_segments1\]:/data1/mirror/gpseg0
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "<string>", line 788, in <module>
  File "<string>", line 778, in run
  File "<string>", line 711, in copyData
  File "<string>", line 636, in getData
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
[FATAL]:-Unexpected EOF on RemotePysync output stream
```

**Comment by kebyn** [comment]
```
gpadmin@greenplum_master1:~$
gpadmin@greenplum_master1:~$ export GPHOME=/opt/gpdb; . /opt/gpdb/greenplum_path.sh; /opt/gpdb/bin/lib/pysync.py -x pg_log -x postgresql.conf -x postmaster.pid /data1/primary/gpseg0 \[greenplum_segments1\]:/data1/mirror/gpseg0
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "<string>", line 788, in <module>
  File "<string>", line 778, in run
  File "<string>", line 711, in copyData
  File "<string>", line 636, in getData
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
[FATAL]:-Unexpected EOF on RemotePysync output stream
gpadmin@greenplum_master1:~$
gpadmin@greenplum_master1:~$
gpadmin@greenplum_master1:~$ scp -qr /data1/primary/gpseg0 greenplum_segments1:/data1/mirror/gpseg0
scp: /data1/mirror/gpseg0/gpseg0/gp_dbid: Permission denied
gpadmin@greenplum_master1:~$
gpadmin@greenplum_master1:~$
```

**Comment by tylarb** [comment]
This looks like an issue with your docker configuration - considering you cannot use the scp command, I expect that you don't have access to read on filesystem, or bind to ports. I would make sure that, inside your containers, you can create files using `touch`, read files using `cat`, and ping other hosts in the local cluster (or container cluster). Given that greenplum requires ssh access, ensuring that you can use the `scp` command would be a great start.
