### ISSUE TITLE
Spark connector to greenplum

### ISSUE THREAD

**Issue by sunnn** [greenplum-db/gpdb#8772]
### Greenplum version or build
Gp 5.19
### OS version and uname -a
Centos 7
### components used for connecting
1.greenplum-spark-connector 1.6.1 jar
2.postgresql latets jar
3.spark version 2.2
4.scala version 2.11

### Expected behavior
I'm trying to connect greenplum through spark in local and cluster mode
Local mode working fine but cluster mode fails saying incompatible class def found

**Comment by vraghavan78** [comment]
@sunnn there is hardly any information here. What have you tried and what is working?

**Comment by sunnn** [comment]
I have used below commands while connecting to greenplum in local and cluster mode
1. val gscWriteOptionMap = Map("url" -> "jdbc:postgresql://gpadmin:5432/foo","user" -> "changeme","password" -> "changeme","dbschema" -> "example_schema","dbtable" -> "tf","server.hostEnv" -> "10.x.x.x")
2.df.write.format("greenplum").options(gscWriteOptionMap).mode(SaveMode.Overwrite).save()
This works fine in local mode 
but gives me an error while running it on cluster mode as below
Caused by: java.lang.IncompatibleClassChangeError: org/eclipse/jetty/server/HttpConnectionFactory
  at org.eclipse.jetty.server.ServerConnector.<init>(ServerConnector.java:96)
  at io.pivotal.greenplum.spark.externaltable.GpfdistService.start(GpfdistService.scala:63)
  at io.pivotal.greenplum.spark.externaltable.GpfdistServiceManager$.getService(GpfdistServiceManager.scala:54)
  at io.pivotal.greenplum.spark.externaltable.PartitionWriter.gpfdistService$lzycompute(PartitionWriter.scala:23)
  at io.pivotal.greenplum.spark.externaltable.PartitionWriter.gpfdistService(PartitionWriter.scala:22)
  at io.pivotal.greenplum.spark.externaltable.PartitionWriter$$anonfun$getClosure$1.apply(PartitionWriter.scala:32)
  at io.pivotal.greenplum.spark.externaltable.PartitionWriter$$anonfun$getClosure$1.apply(PartitionWriter.scala:31)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$26.apply(RDD.scala:844)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$26.apply(RDD.scala:844)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
  at org.apache.spark.scheduler.Task.run(Task.scala:108)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)

**Comment by sunnn** [comment]
Closing the issue as no one responding it out here
