### ISSUE TITLE
gprecoverseg -F command execution failed

### ISSUE THREAD

**Issue by quentinliu** [greenplum-db/gpdb#9141]
### Greenplum version or build
Greenplum Database 6.0.1
### OS version and uname -a
3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### Actual behavior
20191127:13:35:31:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-Starting gprecoverseg with args: -F
20191127:13:35:31:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-local Greenplum Version: 'postgres (Greenplum Database) 6.0.1 build commit:053a66ae19cd7301ec8c8910ed85ec2c20ad60cc'
20191127:13:35:31:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-master Greenplum Version: 'PostgreSQL 9.4.24 (Greenplum Database 6.0.1 build commit:053a66ae19cd7301ec8c8910ed85ec2c20ad60cc) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Oct 10 2019 15:27:29'
20191127:13:35:31:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-Obtaining Segment details from master...
20191127:13:35:32:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-Heap checksum setting is consistent between master and the segments that are candidates for recoverseg
20191127:13:35:32:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-Greenplum instance recovery parameters
20191127:13:35:32:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:----------------------------------------------------------
20191127:13:35:32:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-Recovery type              = Standard
20191127:13:35:32:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:----------------------------------------------------------
20191127:13:35:32:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-Recovery 1 of 1
20191127:13:35:32:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:----------------------------------------------------------
20191127:13:35:32:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-   Synchronization mode                 = Full
20191127:13:35:32:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-   Failed instance host                 = bjcsi-dell-0-21
20191127:13:35:32:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-   Failed instance address              = bjcsi-dell-0-21
20191127:13:35:32:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-   Failed instance directory            = /data/primary/gpseg1
20191127:13:35:32:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-   Failed instance port                 = 6001
20191127:13:35:32:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-   Recovery Source instance host        = bjcsi-dell-0-23
20191127:13:35:32:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-   Recovery Source instance address     = bjcsi-dell-0-23
20191127:13:35:32:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-   Recovery Source instance directory   = /data/mirror/gpseg1
20191127:13:35:32:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-   Recovery Source instance port        = 7001
20191127:13:35:32:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-   Recovery Target                      = in-place
20191127:13:35:32:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:----------------------------------------------------------
20191127:13:35:36:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-1 segment(s) to recover
20191127:13:35:36:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-Ensuring 1 failed segment(s) are stopped
20191127:13:35:37:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-Ensuring that shared memory is cleaned up for stopped segments
20191127:13:35:38:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-Validating remote directories
20191127:13:35:38:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[INFO]:-Configuring new segments
20191127:13:37:24:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[CRITICAL]:-gprecoverseg failed. (Reason='[Errno 5] Input/output error') exiting...
20191127:13:37:24:2791794 gprecoverseg:bjcsi-dell-0-21:gpadmin-[ERROR]:-%d format: a number is required, not NoneType
Traceback (most recent call last):
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 279, in run
    self.logger.debug("[%s] finished cmd: %s" % (self.name, self.cmd))
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 539, in __str__
    return "%s cmdStr='%s'  had result: %s" % (self.name, self.cmdStr, self.results)
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 358, in __str__
    return self.printResult()
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 345, in printResult
    "stderr='%s'" % (self.rc, str(self.completed), str(self.halt), self.stdout, self.stderr)
TypeError: %d format: a number is required, not NoneType

[gpadmin@bjcsi-dell-0-21 gpAdminLogs]$ more pg_basebackup.20191127_133538.dbid3.out
pg_basebackup: initiating base backup, waiting for checkpoint to complete
pg_basebackup: checkpoint completed
transaction log start point: 103/84000028 on timeline 2
pg_basebackup: starting background WAL receiver
   968024/819806861 kB (0%), 1/2 tablespaces (...imary/gpseg1/base/16384/120881.1)
  2554251/819806861 kB (0%), 1/2 tablespaces (...imary/gpseg1/base/16384/121105.1)
  3367243/819806861 kB (0%), 1/2 tablespaces (...imary/gpseg1/base/16384/121105.1)
  5116907/819806861 kB (0%), 1/2 tablespaces (...imary/gpseg1/base/16384/121105.1)
  6656139/819806861 kB (0%), 1/2 tablespaces (...imary/gpseg1/base/16384/121105.1)
  7896843/819806861 kB (0%), 1/2 tablespaces (...imary/gpseg1/base/16384/121105.1)
  8594091/819806861 kB (1%), 1/2 tablespaces (...imary/gpseg1/base/16384/121105.1)
  9466027/819806861 kB (1%), 1/2 tablespaces (...imary/gpseg1/base/16384/121105.1)
 10870619/819806861 kB (1%), 1/2 tablespaces (...imary/gpseg1/base/16384/121105.1)
 12345451/819806861 kB (1%), 1/2 tablespaces (...imary/gpseg1/base/16384/121105.1)
 13925192/819806861 kB (1%), 1/2 tablespaces (...imary/gpseg1/base/16384/121356.2)
 15113416/819806861 kB (1%), 1/2 tablespaces (...imary/gpseg1/base/16384/121356.4)
 16449401/819806861 kB (2%), 1/2 tablespaces (...imary/gpseg1/base/16384/121105.2)
 17055513/819806861 kB (2%), 1/2 tablespaces (...imary/gpseg1/base/16384/121105.2)
 17947993/819806861 kB (2%), 1/2 tablespaces (...imary/gpseg1/base/16384/121105.2)
 18938585/819806861 kB (2%), 1/2 tablespaces (...imary/gpseg1/base/16384/121105.2)
 19746873/819806861 kB (2%), 1/2 tablespaces (...imary/gpseg1/base/16384/121105.2)
 20496793/819806861 kB (2%), 1/2 tablespaces (...imary/gpseg1/base/16384/121105.2)
 21167097/819806861 kB (2%), 1/2 tablespaces (...imary/gpseg1/base/16384/121105.2)
 22314009/819806861 kB (2%), 1/2 tablespaces (...imary/gpseg1/base/16384/121105.2)
 24432749/819806861 kB (2%), 1/2 tablespaces (...imary/gpseg1/base/16384/121045.1)
 25714829/819806861 kB (3%), 1/2 tablespaces (...imary/gpseg1/base/16384/121045.1)
 27322093/819806861 kB (3%), 1/2 tablespaces (...imary/gpseg1/base/16384/121045.1)
 29453517/819806861 kB (3%), 1/2 tablespaces (...imary/gpseg1/base/16384/121045.1)
 31689773/819806861 kB (3%), 1/2 tablespaces (...imary/gpseg1/base/16384/121045.1)
 32807373/819806861 kB (4%), 1/2 tablespaces (...imary/gpseg1/base/16384/121045.1)
 34096269/819806861 kB (4%), 1/2 tablespaces (...imary/gpseg1/base/16384/121045.1)
 35511821/819806861 kB (4%), 1/2 tablespaces (...imary/gpseg1/base/16384/121045.1)
 36949997/819806861 kB (4%), 1/2 tablespaces (...imary/gpseg1/base/16384/121045.1)
 38185485/819806861 kB (4%), 1/2 tablespaces (...imary/gpseg1/base/16384/121045.1)
 39886093/819806861 kB (4%), 1/2 tablespaces (...imary/gpseg1/base/16384/121045.1)
pg_basebackup: could not read COPY data: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
### Step to reproduce the behavior
When there is a large amount of appendonly table in the GP database, this problem can be reproduced.
Test table ttest6 has 72g data. CREATE TABLE statement:
CREATE TABLE ttest6
(
  length numeric(19,0),
  localprovince numeric(19,0),
  localcity numeric(19,0),
  ownerprovince numeric(19,0),
  ownercity numeric(19,0),
  roamingtype numeric(19,0),
  texterface numeric(19,0),
  xdrid numeric(19,0),
  rat numeric(19,0),
  imsi character varying(19),
  imei character varying(19),
  msisdn character varying(19),
  proceduretype numeric(19,0),
  tsstart timestamp without time zone,
  tsend timestamp without time zone,
  sneip numeric(19,0),
  sneport numeric(19,0),
  dneip numeric(19,0),
  dneport numeric(19,0),
  roam_dir numeric(19,0),
  home_mcc numeric(19,0),
  home_mnc numeric(19,0),
  mcc numeric(19,0),
  mnc numeric(19,0),
  target_lac character varying(19),
  source_tac character varying(19),
  source_eci character varying(19),
  sv_flags numeric(19,0),
  ul_c_msc_ip numeric(19,0),
  dl_c_mme_ip numeric(19,0),
  ul_c_msc_teid numeric(19,0),
  dl_c_mme_teid numeric(19,0),
  stn_sr character varying(19),
  target_rnc_id numeric(19,0),
  target_cell_id numeric(19,0),
  arp numeric(19,0),
  request_result numeric(19,0),
  result numeric(19,0),
  sv_cause numeric(19,0),
  post_failure_cause numeric(19,0),
  resp_delay numeric(19,0),
  sv_delay numeric(19,0)
)
WITH (APPENDONLY=true, COMPRESSLEVEL=3, ORIENTATION=row, BLOCKSIZE=524288, 
  OIDS=FALSE
)
DISTRIBUTED RANDOMLY;

**Comment by quentinliu** [comment]
This is a test environment issue.
